/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

#line 71 "/usr/include/assert.h"
extern  __attribute__((__nothrow__, __noreturn__)) void __assert_fail(char const   *__assertion ,
                                                                      char const   *__file ,
                                                                      unsigned int __line ,
                                                                      char const   *__function ) ;
#line 3 "simple-thr1-safe-modular.c"
int g  =    0;
#line 4 "simple-thr1-safe-modular.c"
int cs1  =    0;
#line 5 "simple-thr1-safe-modular.c"
int cs2  =    0;
#line 7 "simple-thr1-safe-modular.c"
void main(void)
{ int tmp ;

  {
#line 9
    tmp = 0;
    {
#line 10
      while (1) {
      while_0_continue: /* CIL Label */ ;
#line 10
        if (g != 1) {

        } else {
          goto while_0_break;
        }
      }
    while_0_break: /* CIL Label */ ;
    }
#line 11
    g = 0;
#line 12
    cs2 = 1;
#line 13
    if (cs1 == 0) {

    } else {
      {
#line 13
        __assert_fail("cs1 == 0", "simple-thr1-safe-modular.c", 13U, "main");
      }
    }
#line 14
    return;
  }
}
