/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

#line 1 "basic2-thr2.c"
int g  ;
#line 2 "basic2-thr2.c"
int y  ;
#line 3 "basic2-thr2.c"
void main(void) 
{ 

  {
#line 4
  y = 0;
#line 5
  g = y * 2;
#line 6
  return;
}
}
