/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

#line 211 "/usr/lib/gcc/x86_64-linux-gnu/4.4.3/include/stddef.h"
typedef unsigned long size_t;
#line 134 "/usr/include/bits/types.h"
typedef unsigned long __dev_t;
#line 135 "/usr/include/bits/types.h"
typedef unsigned int __uid_t;
#line 136 "/usr/include/bits/types.h"
typedef unsigned int __gid_t;
#line 137 "/usr/include/bits/types.h"
typedef unsigned long __ino_t;
#line 139 "/usr/include/bits/types.h"
typedef unsigned int __mode_t;
#line 140 "/usr/include/bits/types.h"
typedef unsigned long __nlink_t;
#line 141 "/usr/include/bits/types.h"
typedef long __off_t;
#line 149 "/usr/include/bits/types.h"
typedef long __time_t;
#line 164 "/usr/include/bits/types.h"
typedef long __blksize_t;
#line 169 "/usr/include/bits/types.h"
typedef long __blkcnt_t;
#line 180 "/usr/include/bits/types.h"
typedef long __ssize_t;
#line 82 "/usr/include/sys/types.h"
typedef __uid_t uid_t;
#line 110 "/usr/include/sys/types.h"
typedef __ssize_t ssize_t;
#line 29 "/usr/include/bits/sigset.h"
struct __anonstruct___sigset_t_9 {
   unsigned long __val[1024UL / (8UL * sizeof(unsigned long ))] ;
};
#line 29 "/usr/include/bits/sigset.h"
typedef struct __anonstruct___sigset_t_9 __sigset_t;
#line 38 "/usr/include/sys/select.h"
typedef __sigset_t sigset_t;
#line 120 "/usr/include/time.h"
struct timespec {
   __time_t tv_sec ;
   long tv_nsec ;
};
#line 43 "/usr/include/bits/stat.h"
struct stat {
   __dev_t st_dev ;
   __ino_t st_ino ;
   __nlink_t st_nlink ;
   __mode_t st_mode ;
   __uid_t st_uid ;
   __gid_t st_gid ;
   int __pad0 ;
   __dev_t st_rdev ;
   __off_t st_size ;
   __blksize_t st_blksize ;
   __blkcnt_t st_blocks ;
   struct timespec st_atim ;
   struct timespec st_mtim ;
   struct timespec st_ctim ;
   long __unused[3] ;
};
#line 339 "/usr/include/stdio.h"
extern int printf(char const   * __restrict  __format  , ...) ;
#line 127 "/usr/include/string.h"
extern  __attribute__((__nothrow__)) char *strcpy(char * __restrict  __dest , char const   * __restrict  __src )  __attribute__((__nonnull__(1,2))) ;
#line 130
extern  __attribute__((__nothrow__)) char *strncpy(char * __restrict  __dest , char const   * __restrict  __src ,
                                                   size_t __n )  __attribute__((__nonnull__(1,2))) ;
#line 135
extern  __attribute__((__nothrow__)) char *strcat(char * __restrict  __dest , char const   * __restrict  __src )  __attribute__((__nonnull__(1,2))) ;
#line 138
extern  __attribute__((__nothrow__)) char *strncat(char * __restrict  __dest , char const   * __restrict  __src ,
                                                   size_t __n )  __attribute__((__nonnull__(1,2))) ;
#line 142
extern  __attribute__((__nothrow__)) int strcmp(char const   *__s1 , char const   *__s2 )  __attribute__((__pure__,
__nonnull__(1,2))) ;
#line 145
extern  __attribute__((__nothrow__)) int strncmp(char const   *__s1 , char const   *__s2 ,
                                                 size_t __n )  __attribute__((__pure__,
__nonnull__(1,2))) ;
#line 233
extern  __attribute__((__nothrow__)) char *strchr(char const   *__s , int __c )  __attribute__((__pure__,
__nonnull__(1))) ;
#line 397
extern  __attribute__((__nothrow__)) size_t strlen(char const   *__s )  __attribute__((__pure__,
__nonnull__(1))) ;
#line 507 "/usr/include/unistd.h"
extern  __attribute__((__nothrow__)) char *getcwd(char *__buf , size_t __size ) ;
#line 695
extern  __attribute__((__nothrow__)) __uid_t geteuid(void) ;
#line 727
extern  __attribute__((__nothrow__)) int seteuid(__uid_t __uid ) ;
#line 825
extern  __attribute__((__nothrow__)) ssize_t readlink(char const   * __restrict  __path ,
                                                      char * __restrict  __buf , size_t __len )  __attribute__((__nonnull__(1,2))) ;
#line 222 "/usr/include/signal.h"
extern  __attribute__((__nothrow__)) int sigemptyset(sigset_t *__set )  __attribute__((__nonnull__(1))) ;
#line 228
extern  __attribute__((__nothrow__)) int sigaddset(sigset_t *__set , int __signo )  __attribute__((__nonnull__(1))) ;
#line 255
extern  __attribute__((__nothrow__)) int sigprocmask(int __how , sigset_t const   * __restrict  __set ,
                                                     sigset_t * __restrict  __oset ) ;
#line 209 "/usr/include/sys/stat.h"
extern  __attribute__((__nothrow__)) int stat(char const   * __restrict  __file ,
                                              struct stat * __restrict  __buf )  __attribute__((__nonnull__(1,2))) ;
#line 120 "realpath-2.4.2-ok.c"
static sigset_t saved_sigmask  ;
#line 121 "realpath-2.4.2-ok.c"
static sigset_t block_sigmask  ;
#line 122 "realpath-2.4.2-ok.c"
static int delaying  ;
#line 123 "realpath-2.4.2-ok.c"
static int init_done  ;
#line 127 "realpath-2.4.2-ok.c"
static void init_mask(void) 
{ int sig ;

  {
  {
#line 131
  init_done = 1;
#line 132
  sigemptyset(& block_sigmask);
#line 133
  sig = 1;
  }
  {
#line 133
  while (1) {
    while_continue: /* CIL Label */ ;
#line 133
    if (sig < 65) {

    } else {
#line 133
      goto while_break;
    }
    {
#line 134
    sigaddset(& block_sigmask, sig);
#line 133
    sig = sig + 1;
    }
  }
  while_break: /* CIL Label */ ;
  }
#line 135
  return;
}
}
#line 139 "realpath-2.4.2-ok.c"
int enable_signaling(void) 
{ int tmp ;
  sigset_t const   * __restrict  __cil_tmp2 ;
  sigset_t *__cil_tmp3 ;
  sigset_t * __restrict  __cil_tmp4 ;

  {
#line 141
  if (delaying != 0) {
    {
#line 142
    delaying = 0;
#line 143
    __cil_tmp2 = (sigset_t const   * __restrict  )(& saved_sigmask);
#line 143
    __cil_tmp3 = (sigset_t *)0;
#line 143
    __cil_tmp4 = (sigset_t * __restrict  )__cil_tmp3;
#line 143
    tmp = sigprocmask(2, __cil_tmp2, __cil_tmp4);
    }
#line 143
    if (tmp < 0) {
#line 145
      return (-1);
    } else {

    }
  } else {

  }
#line 148
  return (0);
}
}
#line 153 "realpath-2.4.2-ok.c"
int delay_signaling(void) 
{ int tmp ;
  sigset_t const   * __restrict  __cil_tmp2 ;
  sigset_t * __restrict  __cil_tmp3 ;

  {
#line 155
  if (init_done == 0) {
    {
#line 156
    init_mask();
    }
  } else {

  }
#line 157
  if (delaying == 0) {
    {
#line 158
    delaying = 1;
#line 159
    __cil_tmp2 = (sigset_t const   * __restrict  )(& block_sigmask);
#line 159
    __cil_tmp3 = (sigset_t * __restrict  )(& saved_sigmask);
#line 159
    tmp = sigprocmask(0, __cil_tmp2, __cil_tmp3);
    }
#line 159
    if (tmp < 0) {
#line 161
      return (-1);
    } else {

    }
  } else {

  }
#line 164
  return (0);
}
}
#line 170 "realpath-2.4.2-ok.c"
char *my_realpath(char const   *pathname , char *result , char *chroot_path ) 
{ struct stat sbuf ;
  char canary[5] ;
  char curpath[46] ;
  char workpath[46] ;
  char linkpath[46] ;
  char namebuf[46] ;
  char *where ;
  char *ptr ;
  char *last ;
  int len ;
  uid_t userid ;
  int resultcode ;
  uid_t userid___0 ;
  char *tmp ;
  char *tmp___0 ;
  int tmp___1 ;
  int tmp___2 ;
  int tmp___3 ;
  size_t tmp___4 ;
  size_t tmp___5 ;
  size_t tmp___6 ;
  size_t tmp___7 ;
  size_t tmp___8 ;
  size_t tmp___9 ;
  size_t tmp___10 ;
  size_t tmp___11 ;
  size_t tmp___12 ;
  size_t tmp___13 ;
  size_t tmp___14 ;
  size_t tmp___15 ;
  size_t tmp___16 ;
  size_t tmp___17 ;
  ssize_t tmp___18 ;
  size_t tmp___19 ;
  size_t tmp___20 ;
  size_t tmp___21 ;
  size_t tmp___22 ;
  size_t tmp___23 ;
  size_t tmp___24 ;
  size_t tmp___25 ;
  size_t tmp___26 ;
  size_t tmp___27 ;
  size_t tmp___28 ;
  size_t tmp___29 ;
  size_t tmp___30 ;
  size_t tmp___31 ;
  size_t tmp___32 ;
  size_t tmp___33 ;
  size_t tmp___34 ;
  size_t tmp___35 ;
  size_t tmp___36 ;
  size_t tmp___37 ;
  size_t tmp___38 ;
  size_t tmp___39 ;
  size_t tmp___40 ;
  size_t tmp___41 ;
  size_t tmp___42 ;
  size_t tmp___43 ;
  size_t tmp___44 ;
  size_t tmp___45 ;
  size_t tmp___46 ;
  size_t tmp___47 ;
  size_t tmp___48 ;
  size_t tmp___49 ;
  unsigned long __cil_tmp68 ;
  unsigned long __cil_tmp69 ;
  unsigned long __cil_tmp70 ;
  unsigned long __cil_tmp71 ;
  unsigned long __cil_tmp72 ;
  unsigned long __cil_tmp73 ;
  unsigned long __cil_tmp74 ;
  unsigned long __cil_tmp75 ;
  unsigned long __cil_tmp76 ;
  unsigned long __cil_tmp77 ;
  void *__cil_tmp78 ;
  unsigned long __cil_tmp79 ;
  unsigned long __cil_tmp80 ;
  void *__cil_tmp81 ;
  void *__cil_tmp82 ;
  unsigned long __cil_tmp83 ;
  unsigned long __cil_tmp84 ;
  void *__cil_tmp85 ;
  char const   * __restrict  __cil_tmp86 ;
  unsigned long __cil_tmp87 ;
  unsigned long __cil_tmp88 ;
  char *__cil_tmp89 ;
  char * __restrict  __cil_tmp90 ;
  char const   * __restrict  __cil_tmp91 ;
  size_t __cil_tmp92 ;
  char const   * __restrict  __cil_tmp93 ;
  unsigned long __cil_tmp94 ;
  unsigned long __cil_tmp95 ;
  char *__cil_tmp96 ;
  char __cil_tmp97 ;
  int __cil_tmp98 ;
  unsigned long __cil_tmp99 ;
  unsigned long __cil_tmp100 ;
  char *__cil_tmp101 ;
  size_t __cil_tmp102 ;
  __uid_t __cil_tmp103 ;
  unsigned long __cil_tmp104 ;
  unsigned long __cil_tmp105 ;
  char *__cil_tmp106 ;
  size_t __cil_tmp107 ;
  char * __restrict  __cil_tmp108 ;
  char const   * __restrict  __cil_tmp109 ;
  size_t __cil_tmp110 ;
  void *__cil_tmp111 ;
  unsigned long __cil_tmp112 ;
  unsigned long __cil_tmp113 ;
  unsigned long __cil_tmp114 ;
  unsigned long __cil_tmp115 ;
  char __cil_tmp116 ;
  int __cil_tmp117 ;
  char const   *__cil_tmp118 ;
  char const   *__cil_tmp119 ;
  size_t __cil_tmp120 ;
  char const   *__cil_tmp121 ;
  size_t __cil_tmp122 ;
  unsigned long __cil_tmp123 ;
  unsigned long __cil_tmp124 ;
  char __cil_tmp125 ;
  int __cil_tmp126 ;
  char __cil_tmp127 ;
  int __cil_tmp128 ;
  char const   *__cil_tmp129 ;
  void *__cil_tmp130 ;
  char *__cil_tmp131 ;
  unsigned long __cil_tmp132 ;
  unsigned long __cil_tmp133 ;
  char const   *__cil_tmp134 ;
  char *__cil_tmp135 ;
  unsigned long __cil_tmp136 ;
  unsigned long __cil_tmp137 ;
  char *__cil_tmp138 ;
  char const   *__cil_tmp139 ;
  void *__cil_tmp140 ;
  unsigned long __cil_tmp141 ;
  unsigned long __cil_tmp142 ;
  char *__cil_tmp143 ;
  char * __restrict  __cil_tmp144 ;
  unsigned long __cil_tmp145 ;
  unsigned long __cil_tmp146 ;
  char *__cil_tmp147 ;
  char const   * __restrict  __cil_tmp148 ;
  unsigned long __cil_tmp149 ;
  unsigned long __cil_tmp150 ;
  unsigned long __cil_tmp151 ;
  unsigned long __cil_tmp152 ;
  char *__cil_tmp153 ;
  unsigned long __cil_tmp154 ;
  unsigned long __cil_tmp155 ;
  char __cil_tmp156 ;
  int __cil_tmp157 ;
  unsigned long __cil_tmp158 ;
  unsigned long __cil_tmp159 ;
  char *__cil_tmp160 ;
  char const   *__cil_tmp161 ;
  unsigned long __cil_tmp162 ;
  unsigned long __cil_tmp163 ;
  char *__cil_tmp164 ;
  char * __restrict  __cil_tmp165 ;
  char const   * __restrict  __cil_tmp166 ;
  size_t __cil_tmp167 ;
  size_t __cil_tmp168 ;
  char const   * __restrict  __cil_tmp169 ;
  unsigned long __cil_tmp170 ;
  unsigned long __cil_tmp171 ;
  char *__cil_tmp172 ;
  unsigned long __cil_tmp173 ;
  unsigned long __cil_tmp174 ;
  char *__cil_tmp175 ;
  char const   *__cil_tmp176 ;
  unsigned long __cil_tmp177 ;
  unsigned long __cil_tmp178 ;
  char *__cil_tmp179 ;
  char * __restrict  __cil_tmp180 ;
  char const   * __restrict  __cil_tmp181 ;
  size_t __cil_tmp182 ;
  size_t __cil_tmp183 ;
  char const   * __restrict  __cil_tmp184 ;
  unsigned long __cil_tmp185 ;
  unsigned long __cil_tmp186 ;
  char *__cil_tmp187 ;
  unsigned long __cil_tmp188 ;
  unsigned long __cil_tmp189 ;
  char *__cil_tmp190 ;
  char const   *__cil_tmp191 ;
  char const   *__cil_tmp192 ;
  size_t __cil_tmp193 ;
  char const   * __restrict  __cil_tmp194 ;
  void *__cil_tmp195 ;
  __uid_t __cil_tmp196 ;
  unsigned long __cil_tmp197 ;
  unsigned long __cil_tmp198 ;
  char *__cil_tmp199 ;
  char const   * __restrict  __cil_tmp200 ;
  struct stat * __restrict  __cil_tmp201 ;
  void *__cil_tmp202 ;
  unsigned long __cil_tmp203 ;
  unsigned long __cil_tmp204 ;
  unsigned long __cil_tmp205 ;
  unsigned long __cil_tmp206 ;
  char *__cil_tmp207 ;
  char const   *__cil_tmp208 ;
  char const   * __restrict  __cil_tmp209 ;
  void *__cil_tmp210 ;
  char * __restrict  __cil_tmp211 ;
  unsigned long __cil_tmp212 ;
  unsigned long __cil_tmp213 ;
  char *__cil_tmp214 ;
  char const   * __restrict  __cil_tmp215 ;
  char const   * __restrict  __cil_tmp216 ;
  unsigned long __cil_tmp217 ;
  unsigned long __cil_tmp218 ;
  char *__cil_tmp219 ;
  char const   *__cil_tmp220 ;
  char const   * __restrict  __cil_tmp221 ;
  void *__cil_tmp222 ;
  char * __restrict  __cil_tmp223 ;
  char const   * __restrict  __cil_tmp224 ;
  char const   * __restrict  __cil_tmp225 ;
  unsigned long __cil_tmp226 ;
  unsigned long __cil_tmp227 ;
  char *__cil_tmp228 ;
  unsigned long __cil_tmp229 ;
  unsigned long __cil_tmp230 ;
  char __cil_tmp231 ;
  int __cil_tmp232 ;
  unsigned long __cil_tmp233 ;
  unsigned long __cil_tmp234 ;
  char *__cil_tmp235 ;
  char const   *__cil_tmp236 ;
  char const   *__cil_tmp237 ;
  size_t __cil_tmp238 ;
  char const   * __restrict  __cil_tmp239 ;
  void *__cil_tmp240 ;
  char * __restrict  __cil_tmp241 ;
  unsigned long __cil_tmp242 ;
  unsigned long __cil_tmp243 ;
  char *__cil_tmp244 ;
  char const   * __restrict  __cil_tmp245 ;
  char const   * __restrict  __cil_tmp246 ;
  unsigned long __cil_tmp247 ;
  unsigned long __cil_tmp248 ;
  char *__cil_tmp249 ;
  unsigned long __cil_tmp250 ;
  unsigned long __cil_tmp251 ;
  char __cil_tmp252 ;
  int __cil_tmp253 ;
  char __cil_tmp254 ;
  int __cil_tmp255 ;
  unsigned long __cil_tmp256 ;
  unsigned long __cil_tmp257 ;
  char __cil_tmp258 ;
  int __cil_tmp259 ;
  unsigned long __cil_tmp260 ;
  unsigned long __cil_tmp261 ;
  char *__cil_tmp262 ;
  char const   *__cil_tmp263 ;
  char const   *__cil_tmp264 ;
  size_t __cil_tmp265 ;
  char const   * __restrict  __cil_tmp266 ;
  void *__cil_tmp267 ;
  char * __restrict  __cil_tmp268 ;
  unsigned long __cil_tmp269 ;
  unsigned long __cil_tmp270 ;
  char *__cil_tmp271 ;
  char const   * __restrict  __cil_tmp272 ;
  char const   * __restrict  __cil_tmp273 ;
  unsigned long __cil_tmp274 ;
  unsigned long __cil_tmp275 ;
  char *__cil_tmp276 ;
  unsigned long __cil_tmp277 ;
  unsigned long __cil_tmp278 ;
  char *__cil_tmp279 ;
  char const   *__cil_tmp280 ;
  char const   *__cil_tmp281 ;
  size_t __cil_tmp282 ;
  char const   * __restrict  __cil_tmp283 ;
  void *__cil_tmp284 ;
  char * __restrict  __cil_tmp285 ;
  unsigned long __cil_tmp286 ;
  unsigned long __cil_tmp287 ;
  char *__cil_tmp288 ;
  char const   * __restrict  __cil_tmp289 ;
  char const   * __restrict  __cil_tmp290 ;
  unsigned long __cil_tmp291 ;
  unsigned long __cil_tmp292 ;
  char *__cil_tmp293 ;
  void *__cil_tmp294 ;
  unsigned long __cil_tmp295 ;
  __mode_t __cil_tmp296 ;
  unsigned int __cil_tmp297 ;
  __uid_t __cil_tmp298 ;
  unsigned long __cil_tmp299 ;
  unsigned long __cil_tmp300 ;
  char *__cil_tmp301 ;
  char const   * __restrict  __cil_tmp302 ;
  unsigned long __cil_tmp303 ;
  unsigned long __cil_tmp304 ;
  char *__cil_tmp305 ;
  char * __restrict  __cil_tmp306 ;
  size_t __cil_tmp307 ;
  void *__cil_tmp308 ;
  unsigned long __cil_tmp309 ;
  unsigned long __cil_tmp310 ;
  unsigned long __cil_tmp311 ;
  unsigned long __cil_tmp312 ;
  char *__cil_tmp313 ;
  char const   *__cil_tmp314 ;
  char const   * __restrict  __cil_tmp315 ;
  void *__cil_tmp316 ;
  char * __restrict  __cil_tmp317 ;
  unsigned long __cil_tmp318 ;
  unsigned long __cil_tmp319 ;
  char *__cil_tmp320 ;
  char const   * __restrict  __cil_tmp321 ;
  char const   * __restrict  __cil_tmp322 ;
  unsigned long __cil_tmp323 ;
  unsigned long __cil_tmp324 ;
  char *__cil_tmp325 ;
  char const   *__cil_tmp326 ;
  char const   * __restrict  __cil_tmp327 ;
  void *__cil_tmp328 ;
  char * __restrict  __cil_tmp329 ;
  char const   * __restrict  __cil_tmp330 ;
  char const   * __restrict  __cil_tmp331 ;
  unsigned long __cil_tmp332 ;
  unsigned long __cil_tmp333 ;
  char *__cil_tmp334 ;
  unsigned long __cil_tmp335 ;
  unsigned long __cil_tmp336 ;
  char __cil_tmp337 ;
  int __cil_tmp338 ;
  unsigned long __cil_tmp339 ;
  unsigned long __cil_tmp340 ;
  char *__cil_tmp341 ;
  char const   *__cil_tmp342 ;
  char const   *__cil_tmp343 ;
  size_t __cil_tmp344 ;
  void *__cil_tmp345 ;
  char * __restrict  __cil_tmp346 ;
  unsigned long __cil_tmp347 ;
  unsigned long __cil_tmp348 ;
  char *__cil_tmp349 ;
  char const   * __restrict  __cil_tmp350 ;
  char const   * __restrict  __cil_tmp351 ;
  unsigned long __cil_tmp352 ;
  unsigned long __cil_tmp353 ;
  char *__cil_tmp354 ;
  unsigned long __cil_tmp355 ;
  unsigned long __cil_tmp356 ;
  char __cil_tmp357 ;
  int __cil_tmp358 ;
  char __cil_tmp359 ;
  int __cil_tmp360 ;
  unsigned long __cil_tmp361 ;
  unsigned long __cil_tmp362 ;
  char __cil_tmp363 ;
  int __cil_tmp364 ;
  unsigned long __cil_tmp365 ;
  unsigned long __cil_tmp366 ;
  char *__cil_tmp367 ;
  char const   *__cil_tmp368 ;
  char const   *__cil_tmp369 ;
  size_t __cil_tmp370 ;
  void *__cil_tmp371 ;
  char * __restrict  __cil_tmp372 ;
  unsigned long __cil_tmp373 ;
  unsigned long __cil_tmp374 ;
  char *__cil_tmp375 ;
  char const   * __restrict  __cil_tmp376 ;
  char const   * __restrict  __cil_tmp377 ;
  unsigned long __cil_tmp378 ;
  unsigned long __cil_tmp379 ;
  char *__cil_tmp380 ;
  unsigned long __cil_tmp381 ;
  unsigned long __cil_tmp382 ;
  char *__cil_tmp383 ;
  char const   *__cil_tmp384 ;
  char const   *__cil_tmp385 ;
  size_t __cil_tmp386 ;
  void *__cil_tmp387 ;
  char * __restrict  __cil_tmp388 ;
  unsigned long __cil_tmp389 ;
  unsigned long __cil_tmp390 ;
  char *__cil_tmp391 ;
  char const   * __restrict  __cil_tmp392 ;
  char const   * __restrict  __cil_tmp393 ;
  unsigned long __cil_tmp394 ;
  unsigned long __cil_tmp395 ;
  char *__cil_tmp396 ;
  void *__cil_tmp397 ;
  unsigned long __cil_tmp398 ;
  unsigned long __cil_tmp399 ;
  char *__cil_tmp400 ;
  char *__cil_tmp401 ;
  unsigned long __cil_tmp402 ;
  unsigned long __cil_tmp403 ;
  char __cil_tmp404 ;
  int __cil_tmp405 ;
  unsigned long __cil_tmp406 ;
  unsigned long __cil_tmp407 ;
  unsigned long __cil_tmp408 ;
  unsigned long __cil_tmp409 ;
  char *__cil_tmp410 ;
  char const   *__cil_tmp411 ;
  unsigned long __cil_tmp412 ;
  unsigned long __cil_tmp413 ;
  char *__cil_tmp414 ;
  char * __restrict  __cil_tmp415 ;
  char const   * __restrict  __cil_tmp416 ;
  size_t __cil_tmp417 ;
  size_t __cil_tmp418 ;
  char const   * __restrict  __cil_tmp419 ;
  unsigned long __cil_tmp420 ;
  unsigned long __cil_tmp421 ;
  char *__cil_tmp422 ;
  unsigned long __cil_tmp423 ;
  unsigned long __cil_tmp424 ;
  char *__cil_tmp425 ;
  char const   *__cil_tmp426 ;
  char const   *__cil_tmp427 ;
  size_t __cil_tmp428 ;
  char const   * __restrict  __cil_tmp429 ;
  void *__cil_tmp430 ;
  unsigned long __cil_tmp431 ;
  unsigned long __cil_tmp432 ;
  char *__cil_tmp433 ;
  char const   *__cil_tmp434 ;
  unsigned long __cil_tmp435 ;
  unsigned long __cil_tmp436 ;
  char *__cil_tmp437 ;
  char * __restrict  __cil_tmp438 ;
  char const   * __restrict  __cil_tmp439 ;
  size_t __cil_tmp440 ;
  size_t __cil_tmp441 ;
  char const   * __restrict  __cil_tmp442 ;
  unsigned long __cil_tmp443 ;
  unsigned long __cil_tmp444 ;
  char *__cil_tmp445 ;
  unsigned long __cil_tmp446 ;
  unsigned long __cil_tmp447 ;
  char *__cil_tmp448 ;
  char const   *__cil_tmp449 ;
  char const   * __restrict  __cil_tmp450 ;
  void *__cil_tmp451 ;
  unsigned long __cil_tmp452 ;
  unsigned long __cil_tmp453 ;
  char *__cil_tmp454 ;
  char * __restrict  __cil_tmp455 ;
  unsigned long __cil_tmp456 ;
  unsigned long __cil_tmp457 ;
  char *__cil_tmp458 ;
  char const   * __restrict  __cil_tmp459 ;
  char const   * __restrict  __cil_tmp460 ;
  unsigned long __cil_tmp461 ;
  unsigned long __cil_tmp462 ;
  char *__cil_tmp463 ;
  unsigned long __cil_tmp464 ;
  unsigned long __cil_tmp465 ;
  unsigned long __cil_tmp466 ;
  __mode_t __cil_tmp467 ;
  unsigned int __cil_tmp468 ;
  unsigned long __cil_tmp469 ;
  unsigned long __cil_tmp470 ;
  char *__cil_tmp471 ;
  char const   *__cil_tmp472 ;
  char const   * __restrict  __cil_tmp473 ;
  void *__cil_tmp474 ;
  unsigned long __cil_tmp475 ;
  unsigned long __cil_tmp476 ;
  char *__cil_tmp477 ;
  char * __restrict  __cil_tmp478 ;
  unsigned long __cil_tmp479 ;
  unsigned long __cil_tmp480 ;
  char *__cil_tmp481 ;
  char const   * __restrict  __cil_tmp482 ;
  char const   * __restrict  __cil_tmp483 ;
  unsigned long __cil_tmp484 ;
  unsigned long __cil_tmp485 ;
  char *__cil_tmp486 ;
  void *__cil_tmp487 ;
  unsigned long __cil_tmp488 ;
  unsigned long __cil_tmp489 ;
  unsigned long __cil_tmp490 ;
  unsigned long __cil_tmp491 ;
  char *__cil_tmp492 ;
  char const   *__cil_tmp493 ;
  char const   * __restrict  __cil_tmp494 ;
  void *__cil_tmp495 ;
  char * __restrict  __cil_tmp496 ;
  unsigned long __cil_tmp497 ;
  unsigned long __cil_tmp498 ;
  char *__cil_tmp499 ;
  char const   * __restrict  __cil_tmp500 ;
  char const   * __restrict  __cil_tmp501 ;
  unsigned long __cil_tmp502 ;
  unsigned long __cil_tmp503 ;
  char *__cil_tmp504 ;
  char const   *__cil_tmp505 ;
  char const   * __restrict  __cil_tmp506 ;
  void *__cil_tmp507 ;
  char * __restrict  __cil_tmp508 ;
  char const   * __restrict  __cil_tmp509 ;
  unsigned long __cil_tmp510 ;
  unsigned long __cil_tmp511 ;
  char __cil_tmp512 ;
  int __cil_tmp513 ;
  unsigned long __cil_tmp514 ;
  unsigned long __cil_tmp515 ;
  char *__cil_tmp516 ;
  char const   *__cil_tmp517 ;
  char const   *__cil_tmp518 ;
  size_t __cil_tmp519 ;
  char const   * __restrict  __cil_tmp520 ;
  void *__cil_tmp521 ;
  char * __restrict  __cil_tmp522 ;
  unsigned long __cil_tmp523 ;
  unsigned long __cil_tmp524 ;
  char *__cil_tmp525 ;
  char const   * __restrict  __cil_tmp526 ;
  char const   * __restrict  __cil_tmp527 ;
  unsigned long __cil_tmp528 ;
  unsigned long __cil_tmp529 ;
  char *__cil_tmp530 ;
  unsigned long __cil_tmp531 ;
  unsigned long __cil_tmp532 ;
  char __cil_tmp533 ;
  int __cil_tmp534 ;
  char __cil_tmp535 ;
  int __cil_tmp536 ;
  unsigned long __cil_tmp537 ;
  unsigned long __cil_tmp538 ;
  char __cil_tmp539 ;
  int __cil_tmp540 ;
  unsigned long __cil_tmp541 ;
  unsigned long __cil_tmp542 ;
  char *__cil_tmp543 ;
  char const   *__cil_tmp544 ;
  char const   *__cil_tmp545 ;
  size_t __cil_tmp546 ;
  char const   * __restrict  __cil_tmp547 ;
  void *__cil_tmp548 ;
  char * __restrict  __cil_tmp549 ;
  unsigned long __cil_tmp550 ;
  unsigned long __cil_tmp551 ;
  char *__cil_tmp552 ;
  char const   * __restrict  __cil_tmp553 ;
  char const   * __restrict  __cil_tmp554 ;
  unsigned long __cil_tmp555 ;
  unsigned long __cil_tmp556 ;
  char *__cil_tmp557 ;
  unsigned long __cil_tmp558 ;
  unsigned long __cil_tmp559 ;
  char *__cil_tmp560 ;
  char const   *__cil_tmp561 ;
  char const   *__cil_tmp562 ;
  size_t __cil_tmp563 ;
  char const   * __restrict  __cil_tmp564 ;
  void *__cil_tmp565 ;
  char * __restrict  __cil_tmp566 ;
  unsigned long __cil_tmp567 ;
  unsigned long __cil_tmp568 ;
  char *__cil_tmp569 ;
  char const   * __restrict  __cil_tmp570 ;
  char const   * __restrict  __cil_tmp571 ;
  unsigned long __cil_tmp572 ;
  unsigned long __cil_tmp573 ;
  char *__cil_tmp574 ;
  void *__cil_tmp575 ;
  unsigned long __cil_tmp576 ;
  unsigned long __cil_tmp577 ;
  char *__cil_tmp578 ;
  char const   *__cil_tmp579 ;
  char const   * __restrict  __cil_tmp580 ;
  void *__cil_tmp581 ;
  unsigned long __cil_tmp582 ;
  unsigned long __cil_tmp583 ;
  char *__cil_tmp584 ;
  char * __restrict  __cil_tmp585 ;
  unsigned long __cil_tmp586 ;
  unsigned long __cil_tmp587 ;
  char *__cil_tmp588 ;
  char const   * __restrict  __cil_tmp589 ;
  char const   * __restrict  __cil_tmp590 ;
  unsigned long __cil_tmp591 ;
  unsigned long __cil_tmp592 ;
  char *__cil_tmp593 ;
  void *__cil_tmp594 ;
  unsigned long __cil_tmp595 ;
  unsigned long __cil_tmp596 ;
  unsigned long __cil_tmp597 ;
  unsigned long __cil_tmp598 ;
  char *__cil_tmp599 ;
  char const   *__cil_tmp600 ;
  char const   * __restrict  __cil_tmp601 ;
  void *__cil_tmp602 ;
  char * __restrict  __cil_tmp603 ;
  unsigned long __cil_tmp604 ;
  unsigned long __cil_tmp605 ;
  char *__cil_tmp606 ;
  char const   * __restrict  __cil_tmp607 ;
  char const   * __restrict  __cil_tmp608 ;
  unsigned long __cil_tmp609 ;
  unsigned long __cil_tmp610 ;
  char *__cil_tmp611 ;
  char const   *__cil_tmp612 ;
  char const   * __restrict  __cil_tmp613 ;
  void *__cil_tmp614 ;
  char * __restrict  __cil_tmp615 ;
  char const   * __restrict  __cil_tmp616 ;
  char const   * __restrict  __cil_tmp617 ;
  unsigned long __cil_tmp618 ;
  unsigned long __cil_tmp619 ;
  char *__cil_tmp620 ;
  unsigned long __cil_tmp621 ;
  unsigned long __cil_tmp622 ;
  char __cil_tmp623 ;
  int __cil_tmp624 ;
  unsigned long __cil_tmp625 ;
  unsigned long __cil_tmp626 ;
  char *__cil_tmp627 ;
  char const   *__cil_tmp628 ;
  char const   *__cil_tmp629 ;
  size_t __cil_tmp630 ;
  char const   * __restrict  __cil_tmp631 ;
  void *__cil_tmp632 ;
  char * __restrict  __cil_tmp633 ;
  unsigned long __cil_tmp634 ;
  unsigned long __cil_tmp635 ;
  char *__cil_tmp636 ;
  char const   * __restrict  __cil_tmp637 ;
  char const   * __restrict  __cil_tmp638 ;
  unsigned long __cil_tmp639 ;
  unsigned long __cil_tmp640 ;
  char *__cil_tmp641 ;
  unsigned long __cil_tmp642 ;
  unsigned long __cil_tmp643 ;
  char __cil_tmp644 ;
  int __cil_tmp645 ;
  char __cil_tmp646 ;
  int __cil_tmp647 ;
  unsigned long __cil_tmp648 ;
  unsigned long __cil_tmp649 ;
  char __cil_tmp650 ;
  int __cil_tmp651 ;
  unsigned long __cil_tmp652 ;
  unsigned long __cil_tmp653 ;
  char *__cil_tmp654 ;
  char const   *__cil_tmp655 ;
  char const   *__cil_tmp656 ;
  size_t __cil_tmp657 ;
  char const   * __restrict  __cil_tmp658 ;
  void *__cil_tmp659 ;
  char * __restrict  __cil_tmp660 ;
  unsigned long __cil_tmp661 ;
  unsigned long __cil_tmp662 ;
  char *__cil_tmp663 ;
  char const   * __restrict  __cil_tmp664 ;
  char const   * __restrict  __cil_tmp665 ;
  unsigned long __cil_tmp666 ;
  unsigned long __cil_tmp667 ;
  char *__cil_tmp668 ;
  unsigned long __cil_tmp669 ;
  unsigned long __cil_tmp670 ;
  char *__cil_tmp671 ;
  char const   *__cil_tmp672 ;
  char const   *__cil_tmp673 ;
  size_t __cil_tmp674 ;
  char const   * __restrict  __cil_tmp675 ;
  void *__cil_tmp676 ;
  char * __restrict  __cil_tmp677 ;
  unsigned long __cil_tmp678 ;
  unsigned long __cil_tmp679 ;
  char *__cil_tmp680 ;
  char const   * __restrict  __cil_tmp681 ;
  char const   * __restrict  __cil_tmp682 ;
  unsigned long __cil_tmp683 ;
  unsigned long __cil_tmp684 ;
  char *__cil_tmp685 ;

  {
#line 172
  __cil_tmp68 = 0 * 1UL;
#line 172
  __cil_tmp69 = (unsigned long )(canary) + __cil_tmp68;
#line 172
  *((char *)__cil_tmp69) = (char )'G';
#line 172
  __cil_tmp70 = 1 * 1UL;
#line 172
  __cil_tmp71 = (unsigned long )(canary) + __cil_tmp70;
#line 172
  *((char *)__cil_tmp71) = (char )'O';
#line 172
  __cil_tmp72 = 2 * 1UL;
#line 172
  __cil_tmp73 = (unsigned long )(canary) + __cil_tmp72;
#line 172
  *((char *)__cil_tmp73) = (char )'O';
#line 172
  __cil_tmp74 = 3 * 1UL;
#line 172
  __cil_tmp75 = (unsigned long )(canary) + __cil_tmp74;
#line 172
  *((char *)__cil_tmp75) = (char )'D';
#line 172
  __cil_tmp76 = 4 * 1UL;
#line 172
  __cil_tmp77 = (unsigned long )(canary) + __cil_tmp76;
#line 172
  *((char *)__cil_tmp77) = (char )'\000';
  {
#line 180
  __cil_tmp78 = (void *)0;
#line 180
  __cil_tmp79 = (unsigned long )__cil_tmp78;
#line 180
  __cil_tmp80 = (unsigned long )result;
#line 180
  if (__cil_tmp80 == __cil_tmp79) {
    {
#line 181
    __cil_tmp81 = (void *)0;
#line 181
    return ((char *)__cil_tmp81);
    }
  } else {

  }
  }
  {
#line 183
  __cil_tmp82 = (void *)0;
#line 183
  __cil_tmp83 = (unsigned long )__cil_tmp82;
#line 183
  __cil_tmp84 = (unsigned long )pathname;
#line 183
  if (__cil_tmp84 == __cil_tmp83) {
#line 184
    *result = (char )'\000';
    {
#line 185
    __cil_tmp85 = (void *)0;
#line 185
    return ((char *)__cil_tmp85);
    }
  } else {

  }
  }
  {
#line 188
  __cil_tmp86 = (char const   * __restrict  )"MY_REALPATH: pathname passed in = %s\n";
#line 188
  printf(__cil_tmp86, pathname);
  }
  {
#line 193
  __cil_tmp87 = 0 * 1UL;
#line 193
  __cil_tmp88 = (unsigned long )(curpath) + __cil_tmp87;
#line 193
  __cil_tmp89 = (char *)__cil_tmp88;
#line 193
  __cil_tmp90 = (char * __restrict  )__cil_tmp89;
#line 193
  __cil_tmp91 = (char const   * __restrict  )pathname;
#line 193
  __cil_tmp92 = (size_t )46;
#line 193
  strncpy(__cil_tmp90, __cil_tmp91, __cil_tmp92);
#line 194
  __cil_tmp93 = (char const   * __restrict  )"canary=[%s]\n";
#line 194
  __cil_tmp94 = 0 * 1UL;
#line 194
  __cil_tmp95 = (unsigned long )(canary) + __cil_tmp94;
#line 194
  __cil_tmp96 = (char *)__cil_tmp95;
#line 194
  printf(__cil_tmp93, __cil_tmp96);
  }
  {
#line 196
  __cil_tmp97 = *pathname;
#line 196
  __cil_tmp98 = (int const   )__cil_tmp97;
#line 196
  if (__cil_tmp98 != 47) {
    {
#line 201
    __cil_tmp99 = 0 * 1UL;
#line 201
    __cil_tmp100 = (unsigned long )(workpath) + __cil_tmp99;
#line 201
    __cil_tmp101 = (char *)__cil_tmp100;
#line 201
    __cil_tmp102 = (size_t )46;
#line 201
    tmp___0 = getcwd(__cil_tmp101, __cil_tmp102);
    }
#line 201
    if (tmp___0) {

    } else {
      {
#line 205
      userid___0 = geteuid();
#line 206
      delay_signaling();
#line 207
      __cil_tmp103 = (__uid_t )0;
#line 207
      seteuid(__cil_tmp103);
#line 209
      __cil_tmp104 = 0 * 1UL;
#line 209
      __cil_tmp105 = (unsigned long )(workpath) + __cil_tmp104;
#line 209
      __cil_tmp106 = (char *)__cil_tmp105;
#line 209
      __cil_tmp107 = (size_t )46;
#line 209
      tmp = getcwd(__cil_tmp106, __cil_tmp107);
      }
#line 209
      if (tmp) {

      } else {
        {
#line 213
        __cil_tmp108 = (char * __restrict  )result;
#line 213
        __cil_tmp109 = (char const   * __restrict  )".";
#line 213
        __cil_tmp110 = (size_t )47;
#line 213
        strncpy(__cil_tmp108, __cil_tmp109, __cil_tmp110);
#line 214
        seteuid(userid___0);
#line 215
        enable_signaling();
        }
        {
#line 216
        __cil_tmp111 = (void *)0;
#line 216
        return ((char *)__cil_tmp111);
        }
      }
      {
#line 218
      seteuid(userid___0);
#line 219
      enable_signaling();
      }
    }
  } else {
#line 222
    __cil_tmp112 = 0 * 1UL;
#line 222
    __cil_tmp113 = (unsigned long )(workpath) + __cil_tmp112;
#line 222
    *((char *)__cil_tmp113) = (char )'\000';
  }
  }
#line 231
  __cil_tmp114 = 0 * 1UL;
#line 231
  __cil_tmp115 = (unsigned long )(curpath) + __cil_tmp114;
#line 231
  where = (char *)__cil_tmp115;
  {
#line 233
  while (1) {
    while_continue: /* CIL Label */ ;
    {
#line 233
    __cil_tmp116 = *where;
#line 233
    __cil_tmp117 = (int )__cil_tmp116;
#line 233
    if (__cil_tmp117 != 0) {

    } else {
#line 233
      goto while_break;
    }
    }
    {
#line 234
    __cil_tmp118 = (char const   *)where;
#line 234
    tmp___1 = strcmp(__cil_tmp118, ".");
    }
#line 234
    if (tmp___1) {

    } else {
#line 235
      where = where + 1;
#line 236
      goto while_continue;
    }
    {
#line 239
    __cil_tmp119 = (char const   *)where;
#line 239
    __cil_tmp120 = (size_t )2;
#line 239
    tmp___2 = strncmp(__cil_tmp119, "./", __cil_tmp120);
    }
#line 239
    if (tmp___2) {

    } else {
#line 240
      where = where + 2;
#line 241
      goto while_continue;
    }
    {
#line 244
    __cil_tmp121 = (char const   *)where;
#line 244
    __cil_tmp122 = (size_t )3;
#line 244
    tmp___3 = strncmp(__cil_tmp121, "../", __cil_tmp122);
    }
#line 244
    if (tmp___3) {

    } else {
#line 245
      where = where + 3;
#line 246
      __cil_tmp123 = 0 * 1UL;
#line 246
      __cil_tmp124 = (unsigned long )(workpath) + __cil_tmp123;
#line 246
      last = (char *)__cil_tmp124;
#line 246
      ptr = last;
      {
#line 247
      while (1) {
        while_continue___0: /* CIL Label */ ;
        {
#line 247
        __cil_tmp125 = *ptr;
#line 247
        __cil_tmp126 = (int )__cil_tmp125;
#line 247
        if (__cil_tmp126 != 0) {

        } else {
#line 247
          goto while_break___0;
        }
        }
        {
#line 248
        __cil_tmp127 = *ptr;
#line 248
        __cil_tmp128 = (int )__cil_tmp127;
#line 248
        if (__cil_tmp128 == 47) {
#line 249
          last = ptr;
        } else {

        }
        }
#line 250
        ptr = ptr + 1;
      }
      while_break___0: /* CIL Label */ ;
      }
#line 252
      *last = (char )'\000';
#line 253
      goto while_continue;
    }
    {
#line 255
    __cil_tmp129 = (char const   *)where;
#line 255
    ptr = strchr(__cil_tmp129, '/');
    }
    {
#line 256
    __cil_tmp130 = (void *)0;
#line 256
    __cil_tmp131 = (char *)__cil_tmp130;
#line 256
    __cil_tmp132 = (unsigned long )__cil_tmp131;
#line 256
    __cil_tmp133 = (unsigned long )ptr;
#line 256
    if (__cil_tmp133 == __cil_tmp132) {
      {
#line 257
      __cil_tmp134 = (char const   *)where;
#line 257
      tmp___4 = strlen(__cil_tmp134);
#line 257
      __cil_tmp135 = where + tmp___4;
#line 257
      ptr = __cil_tmp135 - 1;
      }
    } else {
#line 259
      *ptr = (char )'\000';
    }
    }
    {
#line 261
    __cil_tmp136 = 0 * 1UL;
#line 261
    __cil_tmp137 = (unsigned long )(workpath) + __cil_tmp136;
#line 261
    __cil_tmp138 = (char *)__cil_tmp137;
#line 261
    __cil_tmp139 = (char const   *)__cil_tmp138;
#line 261
    tmp___5 = strlen(__cil_tmp139);
    }
#line 261
    if (tmp___5 >= 46UL) {
      {
#line 262
      __cil_tmp140 = (void *)0;
#line 262
      return ((char *)__cil_tmp140);
      }
    } else {
      {
#line 265
      __cil_tmp141 = 0 * 1UL;
#line 265
      __cil_tmp142 = (unsigned long )(namebuf) + __cil_tmp141;
#line 265
      __cil_tmp143 = (char *)__cil_tmp142;
#line 265
      __cil_tmp144 = (char * __restrict  )__cil_tmp143;
#line 265
      __cil_tmp145 = 0 * 1UL;
#line 265
      __cil_tmp146 = (unsigned long )(workpath) + __cil_tmp145;
#line 265
      __cil_tmp147 = (char *)__cil_tmp146;
#line 265
      __cil_tmp148 = (char const   * __restrict  )__cil_tmp147;
#line 265
      strcpy(__cil_tmp144, __cil_tmp148);
      }
    }
#line 267
    __cil_tmp149 = 0 * 1UL;
#line 267
    __cil_tmp150 = (unsigned long )(namebuf) + __cil_tmp149;
#line 267
    last = (char *)__cil_tmp150;
    {
#line 267
    while (1) {
      while_continue___1: /* CIL Label */ ;
#line 267
      if (*last) {

      } else {
#line 267
        goto while_break___1;
      }
#line 268
      goto __Cont;
      __Cont: /* CIL Label */ 
#line 267
      last = last + 1;
    }
    while_break___1: /* CIL Label */ ;
    }
    {
#line 269
    __cil_tmp151 = 0 * 1UL;
#line 269
    __cil_tmp152 = (unsigned long )(namebuf) + __cil_tmp151;
#line 269
    __cil_tmp153 = (char *)__cil_tmp152;
#line 269
    __cil_tmp154 = (unsigned long )__cil_tmp153;
#line 269
    __cil_tmp155 = (unsigned long )last;
#line 269
    if (__cil_tmp155 == __cil_tmp154) {
#line 269
      goto __TESTCLAIM_2;
    } else {
#line 269
      last = last - 1;
      {
#line 269
      __cil_tmp156 = *last;
#line 269
      __cil_tmp157 = (int )__cil_tmp156;
#line 269
      if (__cil_tmp157 != 47) {
        __TESTCLAIM_2: 
        {
#line 272
        __cil_tmp158 = 0 * 1UL;
#line 272
        __cil_tmp159 = (unsigned long )(namebuf) + __cil_tmp158;
#line 272
        __cil_tmp160 = (char *)__cil_tmp159;
#line 272
        __cil_tmp161 = (char const   *)__cil_tmp160;
#line 272
        tmp___6 = strlen(__cil_tmp161);
#line 272
        __cil_tmp162 = 0 * 1UL;
#line 272
        __cil_tmp163 = (unsigned long )(namebuf) + __cil_tmp162;
#line 272
        __cil_tmp164 = (char *)__cil_tmp163;
#line 272
        __cil_tmp165 = (char * __restrict  )__cil_tmp164;
#line 272
        __cil_tmp166 = (char const   * __restrict  )"/";
#line 272
        __cil_tmp167 = 46UL - tmp___6;
#line 272
        __cil_tmp168 = __cil_tmp167 - 1UL;
#line 272
        strncat(__cil_tmp165, __cil_tmp166, __cil_tmp168);
#line 273
        __cil_tmp169 = (char const   * __restrict  )"canary=[%s]\n";
#line 273
        __cil_tmp170 = 0 * 1UL;
#line 273
        __cil_tmp171 = (unsigned long )(canary) + __cil_tmp170;
#line 273
        __cil_tmp172 = (char *)__cil_tmp171;
#line 273
        printf(__cil_tmp169, __cil_tmp172);
        }
      } else {

      }
      }
    }
    }
    {
#line 277
    __cil_tmp173 = 0 * 1UL;
#line 277
    __cil_tmp174 = (unsigned long )(namebuf) + __cil_tmp173;
#line 277
    __cil_tmp175 = (char *)__cil_tmp174;
#line 277
    __cil_tmp176 = (char const   *)__cil_tmp175;
#line 277
    tmp___7 = strlen(__cil_tmp176);
#line 277
    __cil_tmp177 = 0 * 1UL;
#line 277
    __cil_tmp178 = (unsigned long )(namebuf) + __cil_tmp177;
#line 277
    __cil_tmp179 = (char *)__cil_tmp178;
#line 277
    __cil_tmp180 = (char * __restrict  )__cil_tmp179;
#line 277
    __cil_tmp181 = (char const   * __restrict  )where;
#line 277
    __cil_tmp182 = 46UL - tmp___7;
#line 277
    __cil_tmp183 = __cil_tmp182 - 1UL;
#line 277
    strncat(__cil_tmp180, __cil_tmp181, __cil_tmp183);
#line 278
    __cil_tmp184 = (char const   * __restrict  )"canary=[%s]\n";
#line 278
    __cil_tmp185 = 0 * 1UL;
#line 278
    __cil_tmp186 = (unsigned long )(canary) + __cil_tmp185;
#line 278
    __cil_tmp187 = (char *)__cil_tmp186;
#line 278
    printf(__cil_tmp184, __cil_tmp187);
#line 280
    __cil_tmp188 = 0 * 1UL;
#line 280
    __cil_tmp189 = (unsigned long )(namebuf) + __cil_tmp188;
#line 280
    __cil_tmp190 = (char *)__cil_tmp189;
#line 280
    __cil_tmp191 = (char const   *)__cil_tmp190;
#line 280
    tmp___8 = strlen(__cil_tmp191);
#line 280
    __cil_tmp192 = (char const   *)where;
#line 280
    tmp___9 = strlen(__cil_tmp192);
    }
    {
#line 280
    __cil_tmp193 = tmp___8 + tmp___9;
#line 280
    if (__cil_tmp193 >= 46UL) {
      {
#line 282
      __cil_tmp194 = (char const   * __restrict  )"BUFFER OVERFLOW ATTEMPTED...exiting\n";
#line 282
      printf(__cil_tmp194);
      }
      {
#line 283
      __cil_tmp195 = (void *)0;
#line 283
      return ((char *)__cil_tmp195);
      }
    } else {

    }
    }
    {
#line 286
    ptr = ptr + 1;
#line 286
    where = ptr;
#line 288
    userid = geteuid();
#line 289
    delay_signaling();
#line 290
    __cil_tmp196 = (__uid_t )0;
#line 290
    seteuid(__cil_tmp196);
#line 291
    __cil_tmp197 = 0 * 1UL;
#line 291
    __cil_tmp198 = (unsigned long )(namebuf) + __cil_tmp197;
#line 291
    __cil_tmp199 = (char *)__cil_tmp198;
#line 291
    __cil_tmp200 = (char const   * __restrict  )__cil_tmp199;
#line 291
    __cil_tmp201 = (struct stat * __restrict  )(& sbuf);
#line 291
    resultcode = stat(__cil_tmp200, __cil_tmp201);
#line 292
    seteuid(userid);
#line 293
    enable_signaling();
    }
#line 295
    if (resultcode == -1) {
      {
#line 296
      __cil_tmp202 = (void *)0;
#line 296
      __cil_tmp203 = (unsigned long )__cil_tmp202;
#line 296
      __cil_tmp204 = (unsigned long )chroot_path;
#line 296
      if (__cil_tmp204 == __cil_tmp203) {
        {
#line 297
        __cil_tmp205 = 0 * 1UL;
#line 297
        __cil_tmp206 = (unsigned long )(namebuf) + __cil_tmp205;
#line 297
        __cil_tmp207 = (char *)__cil_tmp206;
#line 297
        __cil_tmp208 = (char const   *)__cil_tmp207;
#line 297
        tmp___10 = strlen(__cil_tmp208);
        }
#line 297
        if (tmp___10 >= 46UL) {
          {
#line 299
          __cil_tmp209 = (char const   * __restrict  )"BUFFER OVERFLOW ATTEMPTED...exiting\n";
#line 299
          printf(__cil_tmp209);
          }
          {
#line 300
          __cil_tmp210 = (void *)0;
#line 300
          return ((char *)__cil_tmp210);
          }
        } else {
          {
#line 305
          __cil_tmp211 = (char * __restrict  )result;
#line 305
          __cil_tmp212 = 0 * 1UL;
#line 305
          __cil_tmp213 = (unsigned long )(namebuf) + __cil_tmp212;
#line 305
          __cil_tmp214 = (char *)__cil_tmp213;
#line 305
          __cil_tmp215 = (char const   * __restrict  )__cil_tmp214;
#line 305
          strcpy(__cil_tmp211, __cil_tmp215);
#line 306
          __cil_tmp216 = (char const   * __restrict  )"canary=[%s]\n";
#line 306
          __cil_tmp217 = 0 * 1UL;
#line 306
          __cil_tmp218 = (unsigned long )(canary) + __cil_tmp217;
#line 306
          __cil_tmp219 = (char *)__cil_tmp218;
#line 306
          printf(__cil_tmp216, __cil_tmp219);
          }
        }
      } else {
        {
#line 310
        __cil_tmp220 = (char const   *)chroot_path;
#line 310
        tmp___17 = strlen(__cil_tmp220);
        }
#line 310
        if (tmp___17 >= 46UL) {
          {
#line 311
          __cil_tmp221 = (char const   * __restrict  )"BUFFER OVERFLOW ATTEMPTED...exiting\n";
#line 311
          printf(__cil_tmp221);
          }
          {
#line 312
          __cil_tmp222 = (void *)0;
#line 312
          return ((char *)__cil_tmp222);
          }
        } else {
          {
#line 317
          __cil_tmp223 = (char * __restrict  )result;
#line 317
          __cil_tmp224 = (char const   * __restrict  )chroot_path;
#line 317
          strcpy(__cil_tmp223, __cil_tmp224);
#line 318
          __cil_tmp225 = (char const   * __restrict  )"canary=[%s]\n";
#line 318
          __cil_tmp226 = 0 * 1UL;
#line 318
          __cil_tmp227 = (unsigned long )(canary) + __cil_tmp226;
#line 318
          __cil_tmp228 = (char *)__cil_tmp227;
#line 318
          printf(__cil_tmp225, __cil_tmp228);
          }
          {
#line 320
          __cil_tmp229 = 0 * 1UL;
#line 320
          __cil_tmp230 = (unsigned long )(namebuf) + __cil_tmp229;
#line 320
          __cil_tmp231 = *((char *)__cil_tmp230);
#line 320
          __cil_tmp232 = (int )__cil_tmp231;
#line 320
          if (__cil_tmp232 != 47) {
            {
#line 322
            __cil_tmp233 = 0 * 1UL;
#line 322
            __cil_tmp234 = (unsigned long )(namebuf) + __cil_tmp233;
#line 322
            __cil_tmp235 = (char *)__cil_tmp234;
#line 322
            __cil_tmp236 = (char const   *)__cil_tmp235;
#line 322
            tmp___11 = strlen(__cil_tmp236);
#line 322
            __cil_tmp237 = (char const   *)result;
#line 322
            tmp___12 = strlen(__cil_tmp237);
            }
            {
#line 322
            __cil_tmp238 = tmp___11 + tmp___12;
#line 322
            if (__cil_tmp238 > 46UL) {
              {
#line 323
              __cil_tmp239 = (char const   * __restrict  )"BUFFER OVERFLOW ATTEMPTED...exiting\n";
#line 323
              printf(__cil_tmp239);
              }
              {
#line 324
              __cil_tmp240 = (void *)0;
#line 324
              return ((char *)__cil_tmp240);
              }
            } else {
              {
#line 329
              __cil_tmp241 = (char * __restrict  )result;
#line 329
              __cil_tmp242 = 0 * 1UL;
#line 329
              __cil_tmp243 = (unsigned long )(namebuf) + __cil_tmp242;
#line 329
              __cil_tmp244 = (char *)__cil_tmp243;
#line 329
              __cil_tmp245 = (char const   * __restrict  )__cil_tmp244;
#line 329
              strcat(__cil_tmp241, __cil_tmp245);
#line 330
              __cil_tmp246 = (char const   * __restrict  )"canary=[%s]\n";
#line 330
              __cil_tmp247 = 0 * 1UL;
#line 330
              __cil_tmp248 = (unsigned long )(canary) + __cil_tmp247;
#line 330
              __cil_tmp249 = (char *)__cil_tmp248;
#line 330
              printf(__cil_tmp246, __cil_tmp249);
              }
            }
            }
          } else {
            {
#line 334
            __cil_tmp250 = 1 * 1UL;
#line 334
            __cil_tmp251 = (unsigned long )(namebuf) + __cil_tmp250;
#line 334
            __cil_tmp252 = *((char *)__cil_tmp251);
#line 334
            __cil_tmp253 = (int )__cil_tmp252;
#line 334
            if (__cil_tmp253 != 0) {
#line 335
              ptr = result;
              {
#line 335
              while (1) {
                while_continue___2: /* CIL Label */ ;
                {
#line 335
                __cil_tmp254 = *ptr;
#line 335
                __cil_tmp255 = (int )__cil_tmp254;
#line 335
                if (__cil_tmp255 != 0) {

                } else {
#line 335
                  goto while_break___2;
                }
                }
#line 335
                ptr = ptr + 1;
              }
              while_break___2: /* CIL Label */ ;
              }
              {
#line 336
              __cil_tmp256 = (unsigned long )result;
#line 336
              __cil_tmp257 = (unsigned long )ptr;
#line 336
              if (__cil_tmp257 == __cil_tmp256) {
#line 336
                goto _L___0;
              } else {
#line 336
                ptr = ptr - 1;
                {
#line 336
                __cil_tmp258 = *ptr;
#line 336
                __cil_tmp259 = (int )__cil_tmp258;
#line 336
                if (__cil_tmp259 != 47) {
                  _L___0: /* CIL Label */ 
                  {
#line 338
                  __cil_tmp260 = 0 * 1UL;
#line 338
                  __cil_tmp261 = (unsigned long )(namebuf) + __cil_tmp260;
#line 338
                  __cil_tmp262 = (char *)__cil_tmp261;
#line 338
                  __cil_tmp263 = (char const   *)__cil_tmp262;
#line 338
                  tmp___13 = strlen(__cil_tmp263);
#line 338
                  __cil_tmp264 = (char const   *)result;
#line 338
                  tmp___14 = strlen(__cil_tmp264);
                  }
                  {
#line 338
                  __cil_tmp265 = tmp___13 + tmp___14;
#line 338
                  if (__cil_tmp265 > 46UL) {
                    {
#line 340
                    __cil_tmp266 = (char const   * __restrict  )"BUFFER OVERFLOW ATTEMPTED...exiting\n";
#line 340
                    printf(__cil_tmp266);
                    }
                    {
#line 341
                    __cil_tmp267 = (void *)0;
#line 341
                    return ((char *)__cil_tmp267);
                    }
                  } else {
                    {
#line 346
                    __cil_tmp268 = (char * __restrict  )result;
#line 346
                    __cil_tmp269 = 0 * 1UL;
#line 346
                    __cil_tmp270 = (unsigned long )(namebuf) + __cil_tmp269;
#line 346
                    __cil_tmp271 = (char *)__cil_tmp270;
#line 346
                    __cil_tmp272 = (char const   * __restrict  )__cil_tmp271;
#line 346
                    strcat(__cil_tmp268, __cil_tmp272);
#line 347
                    __cil_tmp273 = (char const   * __restrict  )"canary=[%s]\n";
#line 347
                    __cil_tmp274 = 0 * 1UL;
#line 347
                    __cil_tmp275 = (unsigned long )(canary) + __cil_tmp274;
#line 347
                    __cil_tmp276 = (char *)__cil_tmp275;
#line 347
                    printf(__cil_tmp273, __cil_tmp276);
                    }
                  }
                  }
                } else {
                  {
#line 351
                  __cil_tmp277 = 0 * 1UL;
#line 351
                  __cil_tmp278 = (unsigned long )(namebuf) + __cil_tmp277;
#line 351
                  __cil_tmp279 = (char *)__cil_tmp278;
#line 351
                  __cil_tmp280 = (char const   *)__cil_tmp279;
#line 351
                  tmp___15 = strlen(__cil_tmp280);
#line 351
                  __cil_tmp281 = (char const   *)result;
#line 351
                  tmp___16 = strlen(__cil_tmp281);
                  }
                  {
#line 351
                  __cil_tmp282 = tmp___15 + tmp___16;
#line 351
                  if (__cil_tmp282 > 47UL) {
                    {
#line 353
                    __cil_tmp283 = (char const   * __restrict  )"BUFFER OVERFLOW ATTEMPTED...exiting\n";
#line 353
                    printf(__cil_tmp283);
                    }
                    {
#line 354
                    __cil_tmp284 = (void *)0;
#line 354
                    return ((char *)__cil_tmp284);
                    }
                  } else {
                    {
#line 359
                    __cil_tmp285 = (char * __restrict  )result;
#line 359
                    __cil_tmp286 = 1 * 1UL;
#line 359
                    __cil_tmp287 = (unsigned long )(namebuf) + __cil_tmp286;
#line 359
                    __cil_tmp288 = (char *)__cil_tmp287;
#line 359
                    __cil_tmp289 = (char const   * __restrict  )__cil_tmp288;
#line 359
                    strcat(__cil_tmp285, __cil_tmp289);
#line 360
                    __cil_tmp290 = (char const   * __restrict  )"canary=[%s]\n";
#line 360
                    __cil_tmp291 = 0 * 1UL;
#line 360
                    __cil_tmp292 = (unsigned long )(canary) + __cil_tmp291;
#line 360
                    __cil_tmp293 = (char *)__cil_tmp292;
#line 360
                    printf(__cil_tmp290, __cil_tmp293);
                    }
                  }
                  }
                }
                }
              }
              }
            } else {

            }
            }
          }
          }
        }
      }
      }
      {
#line 366
      __cil_tmp294 = (void *)0;
#line 366
      return ((char *)__cil_tmp294);
      }
    } else {

    }
    {
#line 371
    __cil_tmp295 = (unsigned long )(& sbuf) + 24;
#line 371
    __cil_tmp296 = *((__mode_t *)__cil_tmp295);
#line 371
    __cil_tmp297 = __cil_tmp296 & 61440U;
#line 371
    if (__cil_tmp297 == 40960U) {
      {
#line 372
      userid = geteuid();
#line 373
      delay_signaling();
#line 374
      __cil_tmp298 = (__uid_t )0;
#line 374
      seteuid(__cil_tmp298);
#line 376
      __cil_tmp299 = 0 * 1UL;
#line 376
      __cil_tmp300 = (unsigned long )(namebuf) + __cil_tmp299;
#line 376
      __cil_tmp301 = (char *)__cil_tmp300;
#line 376
      __cil_tmp302 = (char const   * __restrict  )__cil_tmp301;
#line 376
      __cil_tmp303 = 0 * 1UL;
#line 376
      __cil_tmp304 = (unsigned long )(linkpath) + __cil_tmp303;
#line 376
      __cil_tmp305 = (char *)__cil_tmp304;
#line 376
      __cil_tmp306 = (char * __restrict  )__cil_tmp305;
#line 376
      __cil_tmp307 = (size_t )46;
#line 376
      tmp___18 = readlink(__cil_tmp302, __cil_tmp306, __cil_tmp307);
#line 376
      len = (int )tmp___18;
#line 377
      seteuid(userid);
#line 378
      enable_signaling();
      }
#line 379
      if (len == 0) {
        {
#line 380
        __cil_tmp308 = (void *)0;
#line 380
        __cil_tmp309 = (unsigned long )__cil_tmp308;
#line 380
        __cil_tmp310 = (unsigned long )chroot_path;
#line 380
        if (__cil_tmp310 == __cil_tmp309) {
          {
#line 382
          __cil_tmp311 = 0 * 1UL;
#line 382
          __cil_tmp312 = (unsigned long )(namebuf) + __cil_tmp311;
#line 382
          __cil_tmp313 = (char *)__cil_tmp312;
#line 382
          __cil_tmp314 = (char const   *)__cil_tmp313;
#line 382
          tmp___19 = strlen(__cil_tmp314);
          }
#line 382
          if (tmp___19 > 46UL) {
            {
#line 383
            __cil_tmp315 = (char const   * __restrict  )"strlen(namebuf) > MAXPATHLEN\n";
#line 383
            printf(__cil_tmp315);
            }
            {
#line 384
            __cil_tmp316 = (void *)0;
#line 384
            return ((char *)__cil_tmp316);
            }
          } else {
            {
#line 389
            __cil_tmp317 = (char * __restrict  )result;
#line 389
            __cil_tmp318 = 0 * 1UL;
#line 389
            __cil_tmp319 = (unsigned long )(namebuf) + __cil_tmp318;
#line 389
            __cil_tmp320 = (char *)__cil_tmp319;
#line 389
            __cil_tmp321 = (char const   * __restrict  )__cil_tmp320;
#line 389
            strcpy(__cil_tmp317, __cil_tmp321);
#line 390
            __cil_tmp322 = (char const   * __restrict  )"canary=[%s]\n";
#line 390
            __cil_tmp323 = 0 * 1UL;
#line 390
            __cil_tmp324 = (unsigned long )(canary) + __cil_tmp323;
#line 390
            __cil_tmp325 = (char *)__cil_tmp324;
#line 390
            printf(__cil_tmp322, __cil_tmp325);
            }
          }
        } else {
          {
#line 395
          __cil_tmp326 = (char const   *)chroot_path;
#line 395
          tmp___20 = strlen(__cil_tmp326);
          }
#line 395
          if (tmp___20 >= 46UL) {
            {
#line 397
            __cil_tmp327 = (char const   * __restrict  )"strlen(chroot_path) >= MAXPATHLEN\n";
#line 397
            printf(__cil_tmp327);
            }
            {
#line 398
            __cil_tmp328 = (void *)0;
#line 398
            return ((char *)__cil_tmp328);
            }
          } else {
            {
#line 403
            __cil_tmp329 = (char * __restrict  )result;
#line 403
            __cil_tmp330 = (char const   * __restrict  )chroot_path;
#line 403
            strcpy(__cil_tmp329, __cil_tmp330);
#line 404
            __cil_tmp331 = (char const   * __restrict  )"canary=[%s]\n";
#line 404
            __cil_tmp332 = 0 * 1UL;
#line 404
            __cil_tmp333 = (unsigned long )(canary) + __cil_tmp332;
#line 404
            __cil_tmp334 = (char *)__cil_tmp333;
#line 404
            printf(__cil_tmp331, __cil_tmp334);
            }
          }
          {
#line 407
          __cil_tmp335 = 0 * 1UL;
#line 407
          __cil_tmp336 = (unsigned long )(namebuf) + __cil_tmp335;
#line 407
          __cil_tmp337 = *((char *)__cil_tmp336);
#line 407
          __cil_tmp338 = (int )__cil_tmp337;
#line 407
          if (__cil_tmp338 != 47) {
            {
#line 409
            __cil_tmp339 = 0 * 1UL;
#line 409
            __cil_tmp340 = (unsigned long )(namebuf) + __cil_tmp339;
#line 409
            __cil_tmp341 = (char *)__cil_tmp340;
#line 409
            __cil_tmp342 = (char const   *)__cil_tmp341;
#line 409
            tmp___21 = strlen(__cil_tmp342);
#line 409
            __cil_tmp343 = (char const   *)result;
#line 409
            tmp___22 = strlen(__cil_tmp343);
            }
            {
#line 409
            __cil_tmp344 = tmp___21 + tmp___22;
#line 409
            if (__cil_tmp344 > 46UL) {
              {
#line 410
              __cil_tmp345 = (void *)0;
#line 410
              return ((char *)__cil_tmp345);
              }
            } else {
              {
#line 414
              __cil_tmp346 = (char * __restrict  )result;
#line 414
              __cil_tmp347 = 0 * 1UL;
#line 414
              __cil_tmp348 = (unsigned long )(namebuf) + __cil_tmp347;
#line 414
              __cil_tmp349 = (char *)__cil_tmp348;
#line 414
              __cil_tmp350 = (char const   * __restrict  )__cil_tmp349;
#line 414
              strcat(__cil_tmp346, __cil_tmp350);
#line 415
              __cil_tmp351 = (char const   * __restrict  )"canary=[%s]\n";
#line 415
              __cil_tmp352 = 0 * 1UL;
#line 415
              __cil_tmp353 = (unsigned long )(canary) + __cil_tmp352;
#line 415
              __cil_tmp354 = (char *)__cil_tmp353;
#line 415
              printf(__cil_tmp351, __cil_tmp354);
              }
            }
            }
          } else {
            {
#line 419
            __cil_tmp355 = 1 * 1UL;
#line 419
            __cil_tmp356 = (unsigned long )(namebuf) + __cil_tmp355;
#line 419
            __cil_tmp357 = *((char *)__cil_tmp356);
#line 419
            __cil_tmp358 = (int )__cil_tmp357;
#line 419
            if (__cil_tmp358 != 0) {
#line 420
              ptr = result;
              {
#line 420
              while (1) {
                while_continue___3: /* CIL Label */ ;
                {
#line 420
                __cil_tmp359 = *ptr;
#line 420
                __cil_tmp360 = (int )__cil_tmp359;
#line 420
                if (__cil_tmp360 != 0) {

                } else {
#line 420
                  goto while_break___3;
                }
                }
#line 420
                ptr = ptr + 1;
              }
              while_break___3: /* CIL Label */ ;
              }
              {
#line 421
              __cil_tmp361 = (unsigned long )result;
#line 421
              __cil_tmp362 = (unsigned long )ptr;
#line 421
              if (__cil_tmp362 == __cil_tmp361) {
#line 421
                goto _L___1;
              } else {
#line 421
                ptr = ptr - 1;
                {
#line 421
                __cil_tmp363 = *ptr;
#line 421
                __cil_tmp364 = (int )__cil_tmp363;
#line 421
                if (__cil_tmp364 != 47) {
                  _L___1: /* CIL Label */ 
                  {
#line 423
                  __cil_tmp365 = 0 * 1UL;
#line 423
                  __cil_tmp366 = (unsigned long )(namebuf) + __cil_tmp365;
#line 423
                  __cil_tmp367 = (char *)__cil_tmp366;
#line 423
                  __cil_tmp368 = (char const   *)__cil_tmp367;
#line 423
                  tmp___23 = strlen(__cil_tmp368);
#line 423
                  __cil_tmp369 = (char const   *)result;
#line 423
                  tmp___24 = strlen(__cil_tmp369);
                  }
                  {
#line 423
                  __cil_tmp370 = tmp___23 + tmp___24;
#line 423
                  if (__cil_tmp370 > 46UL) {
                    {
#line 424
                    __cil_tmp371 = (void *)0;
#line 424
                    return ((char *)__cil_tmp371);
                    }
                  } else {
                    {
#line 428
                    __cil_tmp372 = (char * __restrict  )result;
#line 428
                    __cil_tmp373 = 0 * 1UL;
#line 428
                    __cil_tmp374 = (unsigned long )(namebuf) + __cil_tmp373;
#line 428
                    __cil_tmp375 = (char *)__cil_tmp374;
#line 428
                    __cil_tmp376 = (char const   * __restrict  )__cil_tmp375;
#line 428
                    strcat(__cil_tmp372, __cil_tmp376);
#line 429
                    __cil_tmp377 = (char const   * __restrict  )"canary=[%s]\n";
#line 429
                    __cil_tmp378 = 0 * 1UL;
#line 429
                    __cil_tmp379 = (unsigned long )(canary) + __cil_tmp378;
#line 429
                    __cil_tmp380 = (char *)__cil_tmp379;
#line 429
                    printf(__cil_tmp377, __cil_tmp380);
                    }
                  }
                  }
                } else {
                  {
#line 434
                  __cil_tmp381 = 0 * 1UL;
#line 434
                  __cil_tmp382 = (unsigned long )(namebuf) + __cil_tmp381;
#line 434
                  __cil_tmp383 = (char *)__cil_tmp382;
#line 434
                  __cil_tmp384 = (char const   *)__cil_tmp383;
#line 434
                  tmp___25 = strlen(__cil_tmp384);
#line 434
                  __cil_tmp385 = (char const   *)result;
#line 434
                  tmp___26 = strlen(__cil_tmp385);
                  }
                  {
#line 434
                  __cil_tmp386 = tmp___25 + tmp___26;
#line 434
                  if (__cil_tmp386 > 47UL) {
                    {
#line 435
                    __cil_tmp387 = (void *)0;
#line 435
                    return ((char *)__cil_tmp387);
                    }
                  } else {
                    {
#line 439
                    __cil_tmp388 = (char * __restrict  )result;
#line 439
                    __cil_tmp389 = 1 * 1UL;
#line 439
                    __cil_tmp390 = (unsigned long )(namebuf) + __cil_tmp389;
#line 439
                    __cil_tmp391 = (char *)__cil_tmp390;
#line 439
                    __cil_tmp392 = (char const   * __restrict  )__cil_tmp391;
#line 439
                    strcat(__cil_tmp388, __cil_tmp392);
#line 440
                    __cil_tmp393 = (char const   * __restrict  )"canary=[%s]\n";
#line 440
                    __cil_tmp394 = 0 * 1UL;
#line 440
                    __cil_tmp395 = (unsigned long )(canary) + __cil_tmp394;
#line 440
                    __cil_tmp396 = (char *)__cil_tmp395;
#line 440
                    printf(__cil_tmp393, __cil_tmp396);
                    }
                  }
                  }
                }
                }
              }
              }
            } else {

            }
            }
          }
          }
        }
        }
        {
#line 445
        __cil_tmp397 = (void *)0;
#line 445
        return ((char *)__cil_tmp397);
        }
      } else {

      }
#line 447
      __cil_tmp398 = 0 * 1UL;
#line 447
      __cil_tmp399 = (unsigned long )(linkpath) + __cil_tmp398;
#line 447
      __cil_tmp400 = (char *)__cil_tmp399;
#line 447
      __cil_tmp401 = __cil_tmp400 + len;
#line 447
      *__cil_tmp401 = (char )'\000';
      {
#line 449
      __cil_tmp402 = 0 * 1UL;
#line 449
      __cil_tmp403 = (unsigned long )(linkpath) + __cil_tmp402;
#line 449
      __cil_tmp404 = *((char *)__cil_tmp403);
#line 449
      __cil_tmp405 = (int )__cil_tmp404;
#line 449
      if (__cil_tmp405 == 47) {
#line 450
        __cil_tmp406 = 0 * 1UL;
#line 450
        __cil_tmp407 = (unsigned long )(workpath) + __cil_tmp406;
#line 450
        *((char *)__cil_tmp407) = (char )'\000';
      } else {

      }
      }
#line 451
      if (*where) {
        {
#line 454
        __cil_tmp408 = 0 * 1UL;
#line 454
        __cil_tmp409 = (unsigned long )(linkpath) + __cil_tmp408;
#line 454
        __cil_tmp410 = (char *)__cil_tmp409;
#line 454
        __cil_tmp411 = (char const   *)__cil_tmp410;
#line 454
        tmp___27 = strlen(__cil_tmp411);
#line 454
        __cil_tmp412 = 0 * 1UL;
#line 454
        __cil_tmp413 = (unsigned long )(linkpath) + __cil_tmp412;
#line 454
        __cil_tmp414 = (char *)__cil_tmp413;
#line 454
        __cil_tmp415 = (char * __restrict  )__cil_tmp414;
#line 454
        __cil_tmp416 = (char const   * __restrict  )"/";
#line 454
        __cil_tmp417 = 46UL - tmp___27;
#line 454
        __cil_tmp418 = __cil_tmp417 - 1UL;
#line 454
        strncat(__cil_tmp415, __cil_tmp416, __cil_tmp418);
#line 455
        __cil_tmp419 = (char const   * __restrict  )"canary=[%s]\n";
#line 455
        __cil_tmp420 = 0 * 1UL;
#line 455
        __cil_tmp421 = (unsigned long )(canary) + __cil_tmp420;
#line 455
        __cil_tmp422 = (char *)__cil_tmp421;
#line 455
        printf(__cil_tmp419, __cil_tmp422);
#line 457
        __cil_tmp423 = 0 * 1UL;
#line 457
        __cil_tmp424 = (unsigned long )(linkpath) + __cil_tmp423;
#line 457
        __cil_tmp425 = (char *)__cil_tmp424;
#line 457
        __cil_tmp426 = (char const   *)__cil_tmp425;
#line 457
        tmp___28 = strlen(__cil_tmp426);
#line 457
        __cil_tmp427 = (char const   *)where;
#line 457
        tmp___29 = strlen(__cil_tmp427);
        }
        {
#line 457
        __cil_tmp428 = tmp___28 + tmp___29;
#line 457
        if (__cil_tmp428 >= 46UL) {
          {
#line 459
          __cil_tmp429 = (char const   * __restrict  )"BUFFER OVERFLOW ATTEMPTED.. exiting\n";
#line 459
          printf(__cil_tmp429);
          }
          {
#line 460
          __cil_tmp430 = (void *)0;
#line 460
          return ((char *)__cil_tmp430);
          }
        } else {

        }
        }
        {
#line 465
        __cil_tmp431 = 0 * 1UL;
#line 465
        __cil_tmp432 = (unsigned long )(linkpath) + __cil_tmp431;
#line 465
        __cil_tmp433 = (char *)__cil_tmp432;
#line 465
        __cil_tmp434 = (char const   *)__cil_tmp433;
#line 465
        tmp___30 = strlen(__cil_tmp434);
#line 465
        __cil_tmp435 = 0 * 1UL;
#line 465
        __cil_tmp436 = (unsigned long )(linkpath) + __cil_tmp435;
#line 465
        __cil_tmp437 = (char *)__cil_tmp436;
#line 465
        __cil_tmp438 = (char * __restrict  )__cil_tmp437;
#line 465
        __cil_tmp439 = (char const   * __restrict  )where;
#line 465
        __cil_tmp440 = 46UL - tmp___30;
#line 465
        __cil_tmp441 = __cil_tmp440 - 1UL;
#line 465
        strncat(__cil_tmp438, __cil_tmp439, __cil_tmp441);
#line 466
        __cil_tmp442 = (char const   * __restrict  )"canary=[%s]\n";
#line 466
        __cil_tmp443 = 0 * 1UL;
#line 466
        __cil_tmp444 = (unsigned long )(canary) + __cil_tmp443;
#line 466
        __cil_tmp445 = (char *)__cil_tmp444;
#line 466
        printf(__cil_tmp442, __cil_tmp445);
        }
      } else {

      }
      {
#line 469
      __cil_tmp446 = 0 * 1UL;
#line 469
      __cil_tmp447 = (unsigned long )(linkpath) + __cil_tmp446;
#line 469
      __cil_tmp448 = (char *)__cil_tmp447;
#line 469
      __cil_tmp449 = (char const   *)__cil_tmp448;
#line 469
      tmp___31 = strlen(__cil_tmp449);
      }
#line 469
      if (tmp___31 >= 46UL) {
        {
#line 471
        __cil_tmp450 = (char const   * __restrict  )"strlen(linkpath) >= MAXPATHLEN! Exiting..\n";
#line 471
        printf(__cil_tmp450);
        }
        {
#line 472
        __cil_tmp451 = (void *)0;
#line 472
        return ((char *)__cil_tmp451);
        }
      } else {

      }
      {
#line 477
      __cil_tmp452 = 0 * 1UL;
#line 477
      __cil_tmp453 = (unsigned long )(curpath) + __cil_tmp452;
#line 477
      __cil_tmp454 = (char *)__cil_tmp453;
#line 477
      __cil_tmp455 = (char * __restrict  )__cil_tmp454;
#line 477
      __cil_tmp456 = 0 * 1UL;
#line 477
      __cil_tmp457 = (unsigned long )(linkpath) + __cil_tmp456;
#line 477
      __cil_tmp458 = (char *)__cil_tmp457;
#line 477
      __cil_tmp459 = (char const   * __restrict  )__cil_tmp458;
#line 477
      strcpy(__cil_tmp455, __cil_tmp459);
#line 478
      __cil_tmp460 = (char const   * __restrict  )"canary=[%s]\n";
#line 478
      __cil_tmp461 = 0 * 1UL;
#line 478
      __cil_tmp462 = (unsigned long )(canary) + __cil_tmp461;
#line 478
      __cil_tmp463 = (char *)__cil_tmp462;
#line 478
      printf(__cil_tmp460, __cil_tmp463);
#line 485
      __cil_tmp464 = 0 * 1UL;
#line 485
      __cil_tmp465 = (unsigned long )(curpath) + __cil_tmp464;
#line 485
      where = (char *)__cil_tmp465;
      }
#line 486
      goto while_continue;
    } else {

    }
    }
    {
#line 490
    __cil_tmp466 = (unsigned long )(& sbuf) + 24;
#line 490
    __cil_tmp467 = *((__mode_t *)__cil_tmp466);
#line 490
    __cil_tmp468 = __cil_tmp467 & 16384U;
#line 490
    if (__cil_tmp468 == 16384U) {
      {
#line 492
      __cil_tmp469 = 0 * 1UL;
#line 492
      __cil_tmp470 = (unsigned long )(namebuf) + __cil_tmp469;
#line 492
      __cil_tmp471 = (char *)__cil_tmp470;
#line 492
      __cil_tmp472 = (char const   *)__cil_tmp471;
#line 492
      tmp___32 = strlen(__cil_tmp472);
      }
#line 492
      if (tmp___32 >= 46UL) {
        {
#line 494
        __cil_tmp473 = (char const   * __restrict  )"strlen(namebuf) >= sizeof(workpath)\n";
#line 494
        printf(__cil_tmp473);
        }
        {
#line 495
        __cil_tmp474 = (void *)0;
#line 495
        return ((char *)__cil_tmp474);
        }
      } else {
        {
#line 500
        __cil_tmp475 = 0 * 1UL;
#line 500
        __cil_tmp476 = (unsigned long )(workpath) + __cil_tmp475;
#line 500
        __cil_tmp477 = (char *)__cil_tmp476;
#line 500
        __cil_tmp478 = (char * __restrict  )__cil_tmp477;
#line 500
        __cil_tmp479 = 0 * 1UL;
#line 500
        __cil_tmp480 = (unsigned long )(namebuf) + __cil_tmp479;
#line 500
        __cil_tmp481 = (char *)__cil_tmp480;
#line 500
        __cil_tmp482 = (char const   * __restrict  )__cil_tmp481;
#line 500
        strcpy(__cil_tmp478, __cil_tmp482);
#line 501
        __cil_tmp483 = (char const   * __restrict  )"canary=[%s]\n";
#line 501
        __cil_tmp484 = 0 * 1UL;
#line 501
        __cil_tmp485 = (unsigned long )(canary) + __cil_tmp484;
#line 501
        __cil_tmp486 = (char *)__cil_tmp485;
#line 501
        printf(__cil_tmp483, __cil_tmp486);
        }
      }
#line 503
      goto while_continue;
    } else {

    }
    }
#line 506
    if (*where) {
      {
#line 507
      __cil_tmp487 = (void *)0;
#line 507
      __cil_tmp488 = (unsigned long )__cil_tmp487;
#line 507
      __cil_tmp489 = (unsigned long )chroot_path;
#line 507
      if (__cil_tmp489 == __cil_tmp488) {
        {
#line 509
        __cil_tmp490 = 0 * 1UL;
#line 509
        __cil_tmp491 = (unsigned long )(namebuf) + __cil_tmp490;
#line 509
        __cil_tmp492 = (char *)__cil_tmp491;
#line 509
        __cil_tmp493 = (char const   *)__cil_tmp492;
#line 509
        tmp___33 = strlen(__cil_tmp493);
        }
#line 509
        if (tmp___33 >= 46UL) {
          {
#line 510
          __cil_tmp494 = (char const   * __restrict  )"strlen(namebuf) > MAXPATHLEN\n";
#line 510
          printf(__cil_tmp494);
          }
          {
#line 511
          __cil_tmp495 = (void *)0;
#line 511
          return ((char *)__cil_tmp495);
          }
        } else {

        }
        {
#line 515
        __cil_tmp496 = (char * __restrict  )result;
#line 515
        __cil_tmp497 = 0 * 1UL;
#line 515
        __cil_tmp498 = (unsigned long )(namebuf) + __cil_tmp497;
#line 515
        __cil_tmp499 = (char *)__cil_tmp498;
#line 515
        __cil_tmp500 = (char const   * __restrict  )__cil_tmp499;
#line 515
        strcpy(__cil_tmp496, __cil_tmp500);
#line 516
        __cil_tmp501 = (char const   * __restrict  )"canary=[%s]\n";
#line 516
        __cil_tmp502 = 0 * 1UL;
#line 516
        __cil_tmp503 = (unsigned long )(canary) + __cil_tmp502;
#line 516
        __cil_tmp504 = (char *)__cil_tmp503;
#line 516
        printf(__cil_tmp501, __cil_tmp504);
        }
      } else {
        {
#line 520
        __cil_tmp505 = (char const   *)chroot_path;
#line 520
        tmp___34 = strlen(__cil_tmp505);
        }
#line 520
        if (tmp___34 >= 46UL) {
          {
#line 521
          __cil_tmp506 = (char const   * __restrict  )"strlen(chroot_path) > MAXPATHLEN\n";
#line 521
          printf(__cil_tmp506);
          }
          {
#line 522
          __cil_tmp507 = (void *)0;
#line 522
          return ((char *)__cil_tmp507);
          }
        } else {

        }
        {
#line 525
        __cil_tmp508 = (char * __restrict  )result;
#line 525
        __cil_tmp509 = (char const   * __restrict  )chroot_path;
#line 525
        strcpy(__cil_tmp508, __cil_tmp509);
        }
        {
#line 527
        __cil_tmp510 = 0 * 1UL;
#line 527
        __cil_tmp511 = (unsigned long )(namebuf) + __cil_tmp510;
#line 527
        __cil_tmp512 = *((char *)__cil_tmp511);
#line 527
        __cil_tmp513 = (int )__cil_tmp512;
#line 527
        if (__cil_tmp513 != 47) {
          {
#line 529
          __cil_tmp514 = 0 * 1UL;
#line 529
          __cil_tmp515 = (unsigned long )(namebuf) + __cil_tmp514;
#line 529
          __cil_tmp516 = (char *)__cil_tmp515;
#line 529
          __cil_tmp517 = (char const   *)__cil_tmp516;
#line 529
          tmp___35 = strlen(__cil_tmp517);
#line 529
          __cil_tmp518 = (char const   *)result;
#line 529
          tmp___36 = strlen(__cil_tmp518);
          }
          {
#line 529
          __cil_tmp519 = tmp___35 + tmp___36;
#line 529
          if (__cil_tmp519 > 46UL) {
            {
#line 531
            __cil_tmp520 = (char const   * __restrict  )"strlen(namebuf) + strlen(result) > MAXPATHLEN\n";
#line 531
            printf(__cil_tmp520);
            }
            {
#line 532
            __cil_tmp521 = (void *)0;
#line 532
            return ((char *)__cil_tmp521);
            }
          } else {

          }
          }
          {
#line 537
          __cil_tmp522 = (char * __restrict  )result;
#line 537
          __cil_tmp523 = 0 * 1UL;
#line 537
          __cil_tmp524 = (unsigned long )(namebuf) + __cil_tmp523;
#line 537
          __cil_tmp525 = (char *)__cil_tmp524;
#line 537
          __cil_tmp526 = (char const   * __restrict  )__cil_tmp525;
#line 537
          strcat(__cil_tmp522, __cil_tmp526);
#line 538
          __cil_tmp527 = (char const   * __restrict  )"canary=[%s]\n";
#line 538
          __cil_tmp528 = 0 * 1UL;
#line 538
          __cil_tmp529 = (unsigned long )(canary) + __cil_tmp528;
#line 538
          __cil_tmp530 = (char *)__cil_tmp529;
#line 538
          printf(__cil_tmp527, __cil_tmp530);
          }
        } else {
          {
#line 540
          __cil_tmp531 = 1 * 1UL;
#line 540
          __cil_tmp532 = (unsigned long )(namebuf) + __cil_tmp531;
#line 540
          __cil_tmp533 = *((char *)__cil_tmp532);
#line 540
          __cil_tmp534 = (int )__cil_tmp533;
#line 540
          if (__cil_tmp534 != 0) {
#line 541
            ptr = result;
            {
#line 541
            while (1) {
              while_continue___4: /* CIL Label */ ;
              {
#line 541
              __cil_tmp535 = *ptr;
#line 541
              __cil_tmp536 = (int )__cil_tmp535;
#line 541
              if (__cil_tmp536 != 0) {

              } else {
#line 541
                goto while_break___4;
              }
              }
#line 541
              ptr = ptr + 1;
            }
            while_break___4: /* CIL Label */ ;
            }
            {
#line 542
            __cil_tmp537 = (unsigned long )result;
#line 542
            __cil_tmp538 = (unsigned long )ptr;
#line 542
            if (__cil_tmp538 == __cil_tmp537) {
#line 542
              goto _L___2;
            } else {
#line 542
              ptr = ptr - 1;
              {
#line 542
              __cil_tmp539 = *ptr;
#line 542
              __cil_tmp540 = (int )__cil_tmp539;
#line 542
              if (__cil_tmp540 != 47) {
                _L___2: /* CIL Label */ 
                {
#line 544
                __cil_tmp541 = 0 * 1UL;
#line 544
                __cil_tmp542 = (unsigned long )(namebuf) + __cil_tmp541;
#line 544
                __cil_tmp543 = (char *)__cil_tmp542;
#line 544
                __cil_tmp544 = (char const   *)__cil_tmp543;
#line 544
                tmp___37 = strlen(__cil_tmp544);
#line 544
                __cil_tmp545 = (char const   *)result;
#line 544
                tmp___38 = strlen(__cil_tmp545);
                }
                {
#line 544
                __cil_tmp546 = tmp___37 + tmp___38;
#line 544
                if (__cil_tmp546 > 46UL) {
                  {
#line 546
                  __cil_tmp547 = (char const   * __restrict  )"strlen(namebuf) + strlen(result) > MAXPATHLEN\n";
#line 546
                  printf(__cil_tmp547);
                  }
                  {
#line 547
                  __cil_tmp548 = (void *)0;
#line 547
                  return ((char *)__cil_tmp548);
                  }
                } else {

                }
                }
                {
#line 552
                __cil_tmp549 = (char * __restrict  )result;
#line 552
                __cil_tmp550 = 0 * 1UL;
#line 552
                __cil_tmp551 = (unsigned long )(namebuf) + __cil_tmp550;
#line 552
                __cil_tmp552 = (char *)__cil_tmp551;
#line 552
                __cil_tmp553 = (char const   * __restrict  )__cil_tmp552;
#line 552
                strcat(__cil_tmp549, __cil_tmp553);
#line 553
                __cil_tmp554 = (char const   * __restrict  )"canary=[%s]\n";
#line 553
                __cil_tmp555 = 0 * 1UL;
#line 553
                __cil_tmp556 = (unsigned long )(canary) + __cil_tmp555;
#line 553
                __cil_tmp557 = (char *)__cil_tmp556;
#line 553
                printf(__cil_tmp554, __cil_tmp557);
                }
              } else {
                {
#line 557
                __cil_tmp558 = 0 * 1UL;
#line 557
                __cil_tmp559 = (unsigned long )(namebuf) + __cil_tmp558;
#line 557
                __cil_tmp560 = (char *)__cil_tmp559;
#line 557
                __cil_tmp561 = (char const   *)__cil_tmp560;
#line 557
                tmp___39 = strlen(__cil_tmp561);
#line 557
                __cil_tmp562 = (char const   *)result;
#line 557
                tmp___40 = strlen(__cil_tmp562);
                }
                {
#line 557
                __cil_tmp563 = tmp___39 + tmp___40;
#line 557
                if (__cil_tmp563 > 47UL) {
                  {
#line 559
                  __cil_tmp564 = (char const   * __restrict  )"strlen(namebuf) + strlen(result) > MAXPATHLEN + 1\n";
#line 559
                  printf(__cil_tmp564);
                  }
                  {
#line 560
                  __cil_tmp565 = (void *)0;
#line 560
                  return ((char *)__cil_tmp565);
                  }
                } else {

                }
                }
                {
#line 565
                __cil_tmp566 = (char * __restrict  )result;
#line 565
                __cil_tmp567 = 1 * 1UL;
#line 565
                __cil_tmp568 = (unsigned long )(namebuf) + __cil_tmp567;
#line 565
                __cil_tmp569 = (char *)__cil_tmp568;
#line 565
                __cil_tmp570 = (char const   * __restrict  )__cil_tmp569;
#line 565
                strcat(__cil_tmp566, __cil_tmp570);
#line 566
                __cil_tmp571 = (char const   * __restrict  )"canary=[%s]\n";
#line 566
                __cil_tmp572 = 0 * 1UL;
#line 566
                __cil_tmp573 = (unsigned long )(canary) + __cil_tmp572;
#line 566
                __cil_tmp574 = (char *)__cil_tmp573;
#line 566
                printf(__cil_tmp571, __cil_tmp574);
                }
              }
              }
            }
            }
          } else {

          }
          }
        }
        }
      }
      }
      {
#line 571
      __cil_tmp575 = (void *)0;
#line 571
      return ((char *)__cil_tmp575);
      }
    } else {
      {
#line 574
      __cil_tmp576 = 0 * 1UL;
#line 574
      __cil_tmp577 = (unsigned long )(namebuf) + __cil_tmp576;
#line 574
      __cil_tmp578 = (char *)__cil_tmp577;
#line 574
      __cil_tmp579 = (char const   *)__cil_tmp578;
#line 574
      tmp___41 = strlen(__cil_tmp579);
      }
#line 574
      if (tmp___41 >= 46UL) {
        {
#line 576
        __cil_tmp580 = (char const   * __restrict  )"strlen(namebuf) >= sizeof(workpath)\n";
#line 576
        printf(__cil_tmp580);
        }
        {
#line 577
        __cil_tmp581 = (void *)0;
#line 577
        return ((char *)__cil_tmp581);
        }
      } else {

      }
      {
#line 582
      __cil_tmp582 = 0 * 1UL;
#line 582
      __cil_tmp583 = (unsigned long )(workpath) + __cil_tmp582;
#line 582
      __cil_tmp584 = (char *)__cil_tmp583;
#line 582
      __cil_tmp585 = (char * __restrict  )__cil_tmp584;
#line 582
      __cil_tmp586 = 0 * 1UL;
#line 582
      __cil_tmp587 = (unsigned long )(namebuf) + __cil_tmp586;
#line 582
      __cil_tmp588 = (char *)__cil_tmp587;
#line 582
      __cil_tmp589 = (char const   * __restrict  )__cil_tmp588;
#line 582
      strcpy(__cil_tmp585, __cil_tmp589);
#line 583
      __cil_tmp590 = (char const   * __restrict  )"canary=[%s]\n";
#line 583
      __cil_tmp591 = 0 * 1UL;
#line 583
      __cil_tmp592 = (unsigned long )(canary) + __cil_tmp591;
#line 583
      __cil_tmp593 = (char *)__cil_tmp592;
#line 583
      printf(__cil_tmp590, __cil_tmp593);
      }
    }
  }
  while_break: /* CIL Label */ ;
  }
  {
#line 587
  __cil_tmp594 = (void *)0;
#line 587
  __cil_tmp595 = (unsigned long )__cil_tmp594;
#line 587
  __cil_tmp596 = (unsigned long )chroot_path;
#line 587
  if (__cil_tmp596 == __cil_tmp595) {
    {
#line 588
    __cil_tmp597 = 0 * 1UL;
#line 588
    __cil_tmp598 = (unsigned long )(workpath) + __cil_tmp597;
#line 588
    __cil_tmp599 = (char *)__cil_tmp598;
#line 588
    __cil_tmp600 = (char const   *)__cil_tmp599;
#line 588
    tmp___42 = strlen(__cil_tmp600);
    }
#line 588
    if (tmp___42 >= 46UL) {
      {
#line 589
      __cil_tmp601 = (char const   * __restrict  )"strlen(workpath) > MAXPATHLEN!\n";
#line 589
      printf(__cil_tmp601);
      }
      {
#line 590
      __cil_tmp602 = (void *)0;
#line 590
      return ((char *)__cil_tmp602);
      }
    } else {

    }
    {
#line 595
    __cil_tmp603 = (char * __restrict  )result;
#line 595
    __cil_tmp604 = 0 * 1UL;
#line 595
    __cil_tmp605 = (unsigned long )(workpath) + __cil_tmp604;
#line 595
    __cil_tmp606 = (char *)__cil_tmp605;
#line 595
    __cil_tmp607 = (char const   * __restrict  )__cil_tmp606;
#line 595
    strcpy(__cil_tmp603, __cil_tmp607);
#line 596
    __cil_tmp608 = (char const   * __restrict  )"canary=[%s]\n";
#line 596
    __cil_tmp609 = 0 * 1UL;
#line 596
    __cil_tmp610 = (unsigned long )(canary) + __cil_tmp609;
#line 596
    __cil_tmp611 = (char *)__cil_tmp610;
#line 596
    printf(__cil_tmp608, __cil_tmp611);
    }
  } else {
    {
#line 599
    __cil_tmp612 = (char const   *)chroot_path;
#line 599
    tmp___43 = strlen(__cil_tmp612);
    }
#line 599
    if (tmp___43 >= 46UL) {
      {
#line 600
      __cil_tmp613 = (char const   * __restrict  )"strlen(chroot_path) >= MAXPATHLEN\n";
#line 600
      printf(__cil_tmp613);
      }
      {
#line 601
      __cil_tmp614 = (void *)0;
#line 601
      return ((char *)__cil_tmp614);
      }
    } else {

    }
    {
#line 605
    __cil_tmp615 = (char * __restrict  )result;
#line 605
    __cil_tmp616 = (char const   * __restrict  )chroot_path;
#line 605
    strcpy(__cil_tmp615, __cil_tmp616);
#line 606
    __cil_tmp617 = (char const   * __restrict  )"canary=[%s]\n";
#line 606
    __cil_tmp618 = 0 * 1UL;
#line 606
    __cil_tmp619 = (unsigned long )(canary) + __cil_tmp618;
#line 606
    __cil_tmp620 = (char *)__cil_tmp619;
#line 606
    printf(__cil_tmp617, __cil_tmp620);
    }
    {
#line 608
    __cil_tmp621 = 0 * 1UL;
#line 608
    __cil_tmp622 = (unsigned long )(workpath) + __cil_tmp621;
#line 608
    __cil_tmp623 = *((char *)__cil_tmp622);
#line 608
    __cil_tmp624 = (int )__cil_tmp623;
#line 608
    if (__cil_tmp624 != 47) {
      {
#line 610
      __cil_tmp625 = 0 * 1UL;
#line 610
      __cil_tmp626 = (unsigned long )(workpath) + __cil_tmp625;
#line 610
      __cil_tmp627 = (char *)__cil_tmp626;
#line 610
      __cil_tmp628 = (char const   *)__cil_tmp627;
#line 610
      tmp___44 = strlen(__cil_tmp628);
#line 610
      __cil_tmp629 = (char const   *)result;
#line 610
      tmp___45 = strlen(__cil_tmp629);
      }
      {
#line 610
      __cil_tmp630 = tmp___44 + tmp___45;
#line 610
      if (__cil_tmp630 > 46UL) {
        {
#line 612
        __cil_tmp631 = (char const   * __restrict  )"strlen(workpath) + strlen(result) > MAXPATHLEN\n";
#line 612
        printf(__cil_tmp631);
        }
        {
#line 613
        __cil_tmp632 = (void *)0;
#line 613
        return ((char *)__cil_tmp632);
        }
      } else {

      }
      }
      {
#line 617
      __cil_tmp633 = (char * __restrict  )result;
#line 617
      __cil_tmp634 = 0 * 1UL;
#line 617
      __cil_tmp635 = (unsigned long )(workpath) + __cil_tmp634;
#line 617
      __cil_tmp636 = (char *)__cil_tmp635;
#line 617
      __cil_tmp637 = (char const   * __restrict  )__cil_tmp636;
#line 617
      strcat(__cil_tmp633, __cil_tmp637);
#line 618
      __cil_tmp638 = (char const   * __restrict  )"canary=[%s]\n";
#line 618
      __cil_tmp639 = 0 * 1UL;
#line 618
      __cil_tmp640 = (unsigned long )(canary) + __cil_tmp639;
#line 618
      __cil_tmp641 = (char *)__cil_tmp640;
#line 618
      printf(__cil_tmp638, __cil_tmp641);
      }
    } else {
      {
#line 620
      __cil_tmp642 = 1 * 1UL;
#line 620
      __cil_tmp643 = (unsigned long )(workpath) + __cil_tmp642;
#line 620
      __cil_tmp644 = *((char *)__cil_tmp643);
#line 620
      __cil_tmp645 = (int )__cil_tmp644;
#line 620
      if (__cil_tmp645 != 0) {
#line 621
        ptr = result;
        {
#line 621
        while (1) {
          while_continue___5: /* CIL Label */ ;
          {
#line 621
          __cil_tmp646 = *ptr;
#line 621
          __cil_tmp647 = (int )__cil_tmp646;
#line 621
          if (__cil_tmp647 != 0) {

          } else {
#line 621
            goto while_break___5;
          }
          }
#line 621
          ptr = ptr + 1;
        }
        while_break___5: /* CIL Label */ ;
        }
        {
#line 622
        __cil_tmp648 = (unsigned long )result;
#line 622
        __cil_tmp649 = (unsigned long )ptr;
#line 622
        if (__cil_tmp649 == __cil_tmp648) {
#line 622
          goto _L___3;
        } else {
#line 622
          ptr = ptr - 1;
          {
#line 622
          __cil_tmp650 = *ptr;
#line 622
          __cil_tmp651 = (int )__cil_tmp650;
#line 622
          if (__cil_tmp651 != 47) {
            _L___3: /* CIL Label */ 
            {
#line 624
            __cil_tmp652 = 0 * 1UL;
#line 624
            __cil_tmp653 = (unsigned long )(workpath) + __cil_tmp652;
#line 624
            __cil_tmp654 = (char *)__cil_tmp653;
#line 624
            __cil_tmp655 = (char const   *)__cil_tmp654;
#line 624
            tmp___46 = strlen(__cil_tmp655);
#line 624
            __cil_tmp656 = (char const   *)result;
#line 624
            tmp___47 = strlen(__cil_tmp656);
            }
            {
#line 624
            __cil_tmp657 = tmp___46 + tmp___47;
#line 624
            if (__cil_tmp657 > 46UL) {
              {
#line 626
              __cil_tmp658 = (char const   * __restrict  )"strlen(workpath) + strlen(result) > MAXPATHLEN\n";
#line 626
              printf(__cil_tmp658);
              }
              {
#line 627
              __cil_tmp659 = (void *)0;
#line 627
              return ((char *)__cil_tmp659);
              }
            } else {

            }
            }
            {
#line 631
            __cil_tmp660 = (char * __restrict  )result;
#line 631
            __cil_tmp661 = 0 * 1UL;
#line 631
            __cil_tmp662 = (unsigned long )(workpath) + __cil_tmp661;
#line 631
            __cil_tmp663 = (char *)__cil_tmp662;
#line 631
            __cil_tmp664 = (char const   * __restrict  )__cil_tmp663;
#line 631
            strcat(__cil_tmp660, __cil_tmp664);
#line 632
            __cil_tmp665 = (char const   * __restrict  )"canary=[%s]\n";
#line 632
            __cil_tmp666 = 0 * 1UL;
#line 632
            __cil_tmp667 = (unsigned long )(canary) + __cil_tmp666;
#line 632
            __cil_tmp668 = (char *)__cil_tmp667;
#line 632
            printf(__cil_tmp665, __cil_tmp668);
            }
          } else {
            {
#line 635
            __cil_tmp669 = 0 * 1UL;
#line 635
            __cil_tmp670 = (unsigned long )(workpath) + __cil_tmp669;
#line 635
            __cil_tmp671 = (char *)__cil_tmp670;
#line 635
            __cil_tmp672 = (char const   *)__cil_tmp671;
#line 635
            tmp___48 = strlen(__cil_tmp672);
#line 635
            __cil_tmp673 = (char const   *)result;
#line 635
            tmp___49 = strlen(__cil_tmp673);
            }
            {
#line 635
            __cil_tmp674 = tmp___48 + tmp___49;
#line 635
            if (__cil_tmp674 > 47UL) {
              {
#line 637
              __cil_tmp675 = (char const   * __restrict  )"strlen(workpath) + strlen(result) > MAXPATHLEN + 1\n";
#line 637
              printf(__cil_tmp675);
              }
              {
#line 638
              __cil_tmp676 = (void *)0;
#line 638
              return ((char *)__cil_tmp676);
              }
            } else {

            }
            }
            {
#line 642
            __cil_tmp677 = (char * __restrict  )result;
#line 642
            __cil_tmp678 = 1 * 1UL;
#line 642
            __cil_tmp679 = (unsigned long )(workpath) + __cil_tmp678;
#line 642
            __cil_tmp680 = (char *)__cil_tmp679;
#line 642
            __cil_tmp681 = (char const   * __restrict  )__cil_tmp680;
#line 642
            strcat(__cil_tmp677, __cil_tmp681);
#line 643
            __cil_tmp682 = (char const   * __restrict  )"canary=[%s]\n";
#line 643
            __cil_tmp683 = 0 * 1UL;
#line 643
            __cil_tmp684 = (unsigned long )(canary) + __cil_tmp683;
#line 643
            __cil_tmp685 = (char *)__cil_tmp684;
#line 643
            printf(__cil_tmp682, __cil_tmp685);
            }
          }
          }
        }
        }
      } else {

      }
      }
    }
    }
  }
  }
#line 647
  return (result);
}
}
