# This file is part of CPAchecker,
# a tool for configurable software verification:
# https://cpachecker.sosy-lab.org
#
# SPDX-FileCopyrightText: 2007-2020 Dirk Beyer <https://www.sosy-lab.org>
#
# SPDX-License-Identifier: Apache-2.0

[project]
name = "Scripts for CPAchecker"
requires-python = ">= 3.10"

[tool.ruff]
extend-include = ["bin/cpa-witness2test"]

[tool.ruff.lint]
ignore = [
    "LOG015",  # we always use the root logger
    "PIE790",  # arguably better readable if function contains "pass" instead of just docstring
]
