/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

#line 1 "lu-fig2.fixed-thr1.c"
int mThread  =    0;
#line 2 "lu-fig2.fixed-thr1.c"
int start_main  =    0;
#line 3 "lu-fig2.fixed-thr1.c"
int mStartLock  =    0;
#line 4 "lu-fig2.fixed-thr1.c"
int __COUNT__  =    0;
#line 10
extern int ( /* missing proto */  acquire)() ;
#line 16
extern int ( /* missing proto */  assert)() ;
#line 18
extern int ( /* missing proto */  release)() ;
#line 7 "lu-fig2.fixed-thr1.c"
void main(void) 
{ int PR_CreateThread__RES ;

  {
  {
#line 9
  PR_CreateThread__RES = 1;
#line 10
  acquire(mStartLock);
#line 11
  start_main = 1;
  }
  {   __blockattribute__(__atomic__) 
#line 13
  if (__COUNT__ == 0) {
#line 14
    mThread = PR_CreateThread__RES;
#line 15
    __COUNT__ = __COUNT__ + 1;
  } else {
    {
#line 16
    assert(0);
    }
  }
  }
  {
#line 18
  release(mStartLock);
  }
#line 19
  if (mThread == 0) {
#line 19
    return;
  } else {
#line 20
    return;
  }
}
}
