# This file is part of CPAchecker,
# a tool for configurable software verification:
# https://cpachecker.sosy-lab.org
#
# SPDX-FileCopyrightText: 2007-2021 Dirk Beyer <https://www.sosy-lab.org>
#
# SPDX-License-Identifier: Apache-2.0

analysis.useParallelAnalyses=true

# The analyses used for reachability properties. It is a parallel config of the native concurrency
# analysis and the sequential analysis run on the sequentialized program.
parallelAlgorithm.configFiles = concurrency-native.properties, \
                                concurrency-sequentialization.properties
