# This file is part of CPAchecker,
# a tool for configurable software verification:
# https://cpachecker.sosy-lab.org
#
# SPDX-FileCopyrightText: 2026 Dirk Beyer <https://www.sosy-lab.org>
#
# SPDX-License-Identifier: Apache-2.0

# Enable the sequentialization preprocessing
analysis.preprocessing.MPOR = true

# Set the partial order reduction (POR) options that performed best over all tasks.
analysis.algorithm.MPOR.reduceUntilConflict=true
analysis.algorithm.MPOR.bitVectorEncoding=HEXADECIMAL
analysis.algorithm.MPOR.reductionMode=ACCESS_ONLY
analysis.algorithm.MPOR.pruneBitVectorEvaluations=true