# This file is part of CPAchecker,
# a tool for configurable software verification:
# https://cpachecker.sosy-lab.org
#
# SPDX-FileCopyrightText: 2026 Dirk Beyer <https://www.sosy-lab.org>
#
# SPDX-License-Identifier: Apache-2.0

# Enables the sequentialization preprocessing for concurrent C programs and the Commuting Threads
# First (CTF) Partial Order Reduction (POR) options. This file can be included in another config
# without any additional settings for the sequentialization.

# Enable the sequentialization preprocessing
analysis.preprocessing.MPOR = true

# Enable the Commuting Threads First (CTF) partial order reduction (POR) options.
analysis.algorithm.MPOR.executeCommutingThreadsFirst=true
analysis.algorithm.MPOR.bitVectorEncoding=HEXADECIMAL
analysis.algorithm.MPOR.partialOrderReductionMode=ACCESS_ONLY
analysis.algorithm.MPOR.pruneBitVectorEvaluations=true