# This file is part of CPAchecker,
# a tool for configurable software verification:
# https://cpachecker.sosy-lab.org
#
# SPDX-FileCopyrightText: 2007-2026 Dirk Beyer <https://www.sosy-lab.org>
#
# SPDX-License-Identifier: Apache-2.0

# This config enables data-flow analysis for the overflow property
# (static precision is used with widening disabled), for use as one
# analysis of a parallel portfolio.

#include invariantGeneration-no-out--overflow.properties
cpa.invariants.interestingVariableLimit = 16
cpa.invariants.maximumFormulaDepth = 1
cpa.invariants.abstractionStateFactory = NEVER

limits.time.cpu.thread = 60s
