# This file is part of CPAchecker,
# a tool for configurable software verification:
# https://cpachecker.sosy-lab.org
#
# SPDX-FileCopyrightText: 2007-2026 Dirk Beyer <https://www.sosy-lab.org>
#
# SPDX-License-Identifier: Apache-2.0

# ----------------------------------------------------------------------
# Plain k-induction for the overflow property, for use as one analysis
# of a parallel portfolio.
# ----------------------------------------------------------------------

#include kInduction/kInduction--overflow.properties

limits.time.cpu.thread = 300s
