# This file is part of CPAchecker,
# a tool for configurable software verification:
# https://cpachecker.sosy-lab.org
#
# SPDX-FileCopyrightText: 2007-2025 Dirk Beyer <https://www.sosy-lab.org>
#
# SPDX-License-Identifier: Apache-2.0

# include svcomp27--parallel-memsafety.properties

analysis.preprocessing.MPOR = true

# Set the sequentialization options that performed best over all concurrency memory safety tasks.
analysis.algorithm.MPOR.nondeterminismSource=NEXT_THREAD
analysis.algorithm.MPOR.controlEncodingThread=SWITCH_CASE
analysis.algorithm.MPOR.reduceUntilConflict=true
analysis.algorithm.MPOR.bitVectorEncoding=HEXADECIMAL
analysis.algorithm.MPOR.reductionMode=ACCESS_ONLY
analysis.algorithm.MPOR.pruneBitVectorEvaluations=true

# No YAML witnesses for concurrency exist
cpa.arg.yamlProofWitness =
counterexample.export.yaml =
