# This file is part of CPAchecker,
# a tool for configurable software verification:
# https://cpachecker.sosy-lab.org
#
# SPDX-FileCopyrightText: 2007-2025 Dirk Beyer <https://www.sosy-lab.org>
#
# SPDX-License-Identifier: Apache-2.0

# ************** SV-COMP'27 specifics ***********************

# SEP allows us to produce precise counterexamples,
# which are better for witness validation.
cpa.bdd.merge = sep

cpa.callstack.skipVoidRecursion = true

analysis.useParallelAnalyses=true

# YAML witnesses configuration options
counterexample.export.yaml =
cpa.arg.yamlProofWitness =

limits.time.cpu::required =

analysis.checkCounterexamples=true
counterexample.checker=CPAchecker
counterexample.checker.config=../cex-checks/predicateAnalysis-concurrency-as-cex-check.properties

# The analyses used for reachability properties. It is a parallel config of the native concurrency
# analysis and the sequential analysis run on the sequentialized program.
parallelAlgorithm.configFiles = svcomp27--concurrency-native.properties, \
                                svcomp27--concurrency-sequentialization.properties