# This file is part of CPAchecker,
# a tool for configurable software verification:
# https://cpachecker.sosy-lab.org
#
# SPDX-FileCopyrightText: 2026 Dirk Beyer <https://www.sosy-lab.org>
#
# SPDX-License-Identifier: Apache-2.0

# ----------------------------------------------------------------------
# The main analyses for memory-safety properties in SV-COMP'27.
# This is a component of svcomp27--memorysafety.properties, which runs
# it next to the simple checks.
# ----------------------------------------------------------------------

# Use sequential combination of analyses.
analysis.restartAfterUnknown = true

# The analyses used for memsafety properties, necessary for the delegation to concurrency
# TODO: Why is recursion not delegated here?
restartAlgorithm.configFiles = svcomp27--parallel-memsafety.properties, \
                               svcomp27--concurrency-memsafety.properties::if-concurrent
