# This file is part of CPAchecker,
# a tool for configurable software verification:
# https://cpachecker.sosy-lab.org
#
# SPDX-FileCopyrightText: 2026 Dirk Beyer <https://www.sosy-lab.org>
#
# SPDX-License-Identifier: Apache-2.0

#include concurrency-sequentialization--overflow.properties

limits.time.cpu = 200s

# Disable redundant parsing of the sequentialization, because it is parsed anyway for the analysis.
# Parsing can take several seconds, so it should be optimized for the svcomp27 configs.
analysis.algorithm.MPOR.validateParse = false
