# This file is part of CPAchecker,
# a tool for configurable software verification:
# https://cpachecker.sosy-lab.org
#
# SPDX-FileCopyrightText: 2026 Dirk Beyer <https://www.sosy-lab.org>
#
# SPDX-License-Identifier: Apache-2.0

# ----------------------------------------------------------------------
# The main analyses for the overflow property in SV-COMP'27.
# This is a component of svcomp27--overflow.properties, which runs it
# next to the simple checks.
# ----------------------------------------------------------------------

# Use sequential combination of analyses.
analysis.restartAfterUnknown = true

# The analyses used for overflow properties.
restartAlgorithm.configFiles = parallel-overflow.properties, \
                               ../predicateAnalysis-bam-rec--overflow.properties::if-recursive, \
                               svcomp27--concurrency-overflow.properties::if-concurrent
