# This file is part of CPAchecker,
# a tool for configurable software verification:
# https://cpachecker.sosy-lab.org
#
# SPDX-FileCopyrightText: 2007-2025 Dirk Beyer <https://www.sosy-lab.org>
#
# SPDX-License-Identifier: Apache-2.0

# ************** SV-COMP'27 specifics ***********************

analysis.useParallelAnalyses=true

# YAML witnesses configuration options
counterexample.export.yaml =
cpa.arg.yamlProofWitness =

# These options are necessary for both the native concurrency and sequential analyses, otherwise
# false alarms are reported.
analysis.checkCounterexamples=true
counterexample.checker=CPAchecker
counterexample.checker.config=../cex-checks/predicateAnalysis-concurrency-as-cex-check.properties

# The analyses used for reachability properties. It is a parallel config of the native concurrency
# analysis and the sequential analysis run on the sequentialized program.
parallelAlgorithm.configFiles = svcomp27--concurrency-native.properties, \
                                svcomp27--concurrency-sequentialization.properties
