# This file is part of CPAchecker,
# a tool for configurable software verification:
# https://cpachecker.sosy-lab.org
#
# SPDX-FileCopyrightText: 2026 Dirk Beyer <https://www.sosy-lab.org>
#
# SPDX-License-Identifier: Apache-2.0

#include bddAnalysis-concurrency.properties

limits.time.cpu = 200s

# SEP allows us to produce precise counterexamples,
# which are better for witness validation.
cpa.bdd.merge = sep

cpa.callstack.skipVoidRecursion = true
