# This file is part of CPAchecker,
# a tool for configurable software verification:
# https://cpachecker.sosy-lab.org
#
# SPDX-FileCopyrightText: 2026 Dirk Beyer <https://www.sosy-lab.org>
#
# SPDX-License-Identifier: Apache-2.0

# ----------------------------------------------------------------------
# The main analyses for the termination property in SV-COMP'27.
# This is a component of svcomp27--termination.properties, which runs
# it next to the simple checks.
# ----------------------------------------------------------------------

# Use sequential combination of analyses.
analysis.restartAfterUnknown = true

# sequence of termination analyses used
restartAlgorithm.configFiles = svcomp27--parallel-termination.properties, \
                               svcomp27--termination-recursion.properties::if-recursive
