# This file is part of CPAchecker,
# a tool for configurable software verification:
# https://cpachecker.sosy-lab.org
#
# SPDX-FileCopyrightText: 2026 Dirk Beyer <https://www.sosy-lab.org>
#
# SPDX-License-Identifier: Apache-2.0

#include svcomp27--parallel-multipleLoops.properties

limits.time.cpu = 775s

analysis.preprocessing.MPOR = true

# 'strcpy' resulted in false alarms for multiple concurrent reachability tasks.
cpa.callstack.unsupportedFunctions=strcpy
