# This file is part of CPAchecker,
# a tool for configurable software verification:
# https://cpachecker.sosy-lab.org
#
# SPDX-FileCopyrightText: 2022 Dirk Beyer <https://www.sosy-lab.org>
#
# SPDX-License-Identifier: Apache-2.0

# ------------------------------------------------------------------------------
# This configuration file enables checking for overflows in a setup
# with concurrent threads.
# ------------------------------------------------------------------------------

analysis.useParallelAnalyses=true

# No YAML witnesses for concurrency exist currently
cpa.arg.yamlProofWitness = 
counterexample.export.yaml =

# The analyses used for overflow properties. It is a parallel config of the native concurrency
# analysis and the sequential analysis run on the sequentialized program.
parallelAlgorithm.configFiles = svcomp27--concurrency-native--overflow.properties, \
                                svcomp27--concurrency-sequentialization--overflow.properties