# This file is part of CPAchecker,
# a tool for configurable software verification:
# https://cpachecker.sosy-lab.org
#
# SPDX-FileCopyrightText: 2007-2025 Dirk Beyer <https://www.sosy-lab.org>
#
# SPDX-License-Identifier: Apache-2.0

# ----------------------------------------------------------------------
# This configuration file uses predicate-analysis to check for terminations
# in non-recursive programs.
# ----------------------------------------------------------------------

# We remove the ValueAnalysisCPA from terminationToSafety config, because it performs better
# in combination with other SV-COMP configs in the time limit.
#include ../includes/terminationToSafety-withoutVA.properties

limits.time.cpu.thread = 300s
