# This file is part of CPAchecker,
# a tool for configurable software verification:
# https://cpachecker.sosy-lab.org
#
# SPDX-FileCopyrightText: 2007-2026 Dirk Beyer <https://www.sosy-lab.org>
#
# SPDX-License-Identifier: Apache-2.0

# ------------------------------------------------------------------
# This configuration file uses symbolic execution to check for
# overflows, for use as one analysis of a parallel portfolio.
# ------------------------------------------------------------------

#include ../includes/symbolicExecution--overflow.properties

# Do not skip recursion to avoid false proofs
cpa.callstack.skipVoidRecursion = false

# stop if counterexample is infeasible
counterexample.continueAfterInfeasibleError = false

limits.time.cpu.thread = 180s
