/* Generated by CIL v. 1.3.6 */
/* print_CIL_Input is true */

int main(void) 
{ int st ;
  int ok ;
  int p ;
  int cmd ;

  {
  {
#line 7
  st = 0;
#line 8
  ok = 0;
#line 10
  //cmd = readcmd();
  }
  {
#line 12
  while (1) {
    while_0_continue: /* CIL Label */ ;
#line 14
    if (st == 0) {
      goto switch_1_0;
    } else {
#line 22
      if (st == 1) {
        goto switch_1_1;
      } else {
#line 31
        if (st == 2) {
          goto switch_1_2;
        } else {
#line 53
          if (st == 3) {
            goto switch_1_3;
          } else {
#line 63
            if (st == 4) {
              goto switch_1_4;
            } else {
#line 13
              if (0) {
                switch_1_0: /* CIL Label */ 
#line 15
                if (cmd == 177) {
#line 16
                  st = 1;
                } else {
#line 19
                  st = 2;
                }
                goto switch_1_break;
                switch_1_1: /* CIL Label */ 
#line 23
                if (cmd == 177) {
                  {
#line 24
                  st = 3;
#line 25
                  //cmd = readcmd();
                  }
                } else {
#line 28
                  st = 0;
                }
                goto switch_1_break;
                switch_1_2: /* CIL Label */ 
#line 32
                if (cmd != 177) {
#line 33
                  cmd = 79;
#line 34
                  st = 4;
#line 35
                  p = cmd;
                  {
#line 36
                  while (1) {
                    while_2_continue: /* CIL Label */ ;
#line 37
                    if (p <= 0) {
                      goto L1;
                    } else {
#line 41
                      p --;
                    }
                  }
                  while_2_break: /* CIL Label */ ;
                  }
                  L1: 
#line 45
                  if (p < 0) {
                    goto ERROR;
                  }
                } else {
                  goto ERROR;
                }
                goto switch_1_break;
                switch_1_3: /* CIL Label */ 
#line 54
                if (cmd == 78) {
#line 55
                  st = 4;
#line 56
                  ok = 1;
                } else {
                  {
#line 59
                  st = 0;
#line 60
                  //cmd = readcmd();
                  }
                }
                goto switch_1_break;
                switch_1_4: /* CIL Label */ 
#line 64
                if (ok != 0) {
#line 65
                  if (cmd != 78) {
                    goto ERROR;
                  }
                } else {
#line 70
                  if (cmd != 79) {
                    goto ERROR;
                  }
                }
                goto cont;
              } else {
                switch_1_break: /* CIL Label */ ;
              }
            }
          }
        }
      }
    }
  }
  while_0_break: /* CIL Label */ ;
  }
  cont: 
#line 78
  p = cmd;
  {
#line 79
  while (1) {
    while_3_continue: /* CIL Label */ ;
#line 80
    if (p <= 0) {
      goto L2;
    } else {
#line 84
      p --;
    }
  }
  while_3_break: /* CIL Label */ ;
  }
  L2: 
#line 88
  if (p > 0) {
    goto ERROR;
  }
#line 92
  return (0);
  ERROR: 
  printf("error");
#line 94
  return (-1);
}
}
