/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

#line 211 "/usr/lib/gcc/x86_64-linux-gnu/4.4.3/include/stddef.h"
typedef unsigned long size_t;
#line 73 "spe-sum.c"
typedef unsigned int addr64;
#line 339 "/usr/include/stdio.h"
extern int printf(char const   * __restrict  __format  , ...) ;
#line 211 "../spu_mfcio.h"
extern void mfc_get(void volatile   *ls , unsigned int ea , unsigned int size , unsigned int tag ,
                    unsigned int tid , unsigned int rid ) ;
#line 252
extern void mfc_write_tag_mask(unsigned int mask ) ;
#line 270
extern void mfc_read_tag_status_all() ;
#line 85 "spe-sum.c"
static char buf[(1 << 12) * 4]  __attribute__((__aligned__(128)))  ;
#line 87 "spe-sum.c"
int sum  =    0;
#line 88 "spe-sum.c"
size_t total_bytes  =    (size_t )0;
#line 114
extern int ( /* missing proto */  assert)() ;
#line 102 "spe-sum.c"
int spu_main(unsigned long long src , size_t outer_size ) 
{ unsigned int nbufs ;
  unsigned int i ;
  unsigned int size ;
  unsigned int nbufs_to_xfer ;
  addr64 _src ;
  unsigned int mask ;
  int tmp ;
  size_t __cil_tmp10 ;
  int __cil_tmp11 ;
  unsigned long __cil_tmp12 ;
  unsigned long __cil_tmp13 ;
  char *__cil_tmp14 ;
  void volatile   *__cil_tmp15 ;
  int __cil_tmp16 ;
  addr64 __cil_tmp17 ;
  int __cil_tmp18 ;
  unsigned long __cil_tmp19 ;
  unsigned long __cil_tmp20 ;
  char *__cil_tmp21 ;
  void volatile   *__cil_tmp22 ;
  int __cil_tmp23 ;
  addr64 __cil_tmp24 ;
  int __cil_tmp25 ;
  int __cil_tmp26 ;
  unsigned long __cil_tmp27 ;
  unsigned long __cil_tmp28 ;
  char *__cil_tmp29 ;
  void volatile   *__cil_tmp30 ;
  int __cil_tmp31 ;
  addr64 __cil_tmp32 ;
  int __cil_tmp33 ;
  int __cil_tmp34 ;
  unsigned long __cil_tmp35 ;
  unsigned long __cil_tmp36 ;
  char *__cil_tmp37 ;
  void volatile   *__cil_tmp38 ;
  int __cil_tmp39 ;
  addr64 __cil_tmp40 ;
  int __cil_tmp41 ;
  int __cil_tmp42 ;
  unsigned int __cil_tmp43 ;
  unsigned int __cil_tmp44 ;
  int __cil_tmp45 ;
  int __cil_tmp46 ;
  unsigned int __cil_tmp47 ;
  int __cil_tmp48 ;
  unsigned int __cil_tmp49 ;
  unsigned int __cil_tmp50 ;
  int __cil_tmp51 ;
  unsigned long __cil_tmp52 ;
  unsigned long __cil_tmp53 ;
  char *__cil_tmp54 ;
  void volatile   *__cil_tmp55 ;
  int __cil_tmp56 ;
  addr64 __cil_tmp57 ;
  int __cil_tmp58 ;
  unsigned int __cil_tmp59 ;
  unsigned int __cil_tmp60 ;
  unsigned long long __cil_tmp61 ;
  char const   * __restrict  __cil_tmp62 ;
  size_t __cil_tmp63 ;
  size_t __cil_tmp64 ;

  {
  {
#line 104
  __cil_tmp10 = outer_size >> 12;
#line 104
  nbufs = (unsigned int )__cil_tmp10;
#line 106
  i = 0U;
#line 107
  __cil_tmp11 = 1 << 12;
#line 107
  size = (unsigned int )__cil_tmp11;
#line 108
  nbufs_to_xfer = nbufs;
#line 111
  _src = (addr64 )src;
#line 114
  assert(1);
  }
#line 115
  if (nbufs > 0U) {
    {
#line 116
    __cil_tmp12 = 0 * 1UL;
#line 116
    __cil_tmp13 = (unsigned long )(buf) + __cil_tmp12;
#line 116
    __cil_tmp14 = (char *)__cil_tmp13;
#line 116
    __cil_tmp15 = (void volatile   *)__cil_tmp14;
#line 116
    mfc_get(__cil_tmp15, _src, size, 0U, 0U, 0U);
#line 117
    __cil_tmp16 = 1 << 12;
#line 117
    __cil_tmp17 = (addr64 )__cil_tmp16;
#line 117
    _src = _src + __cil_tmp17;
#line 118
    nbufs_to_xfer = nbufs_to_xfer - 1U;
    }
  } else {

  }
#line 120
  if (nbufs > 1U) {
    {
#line 121
    __cil_tmp18 = 1 << 12;
#line 121
    __cil_tmp19 = __cil_tmp18 * 1UL;
#line 121
    __cil_tmp20 = (unsigned long )(buf) + __cil_tmp19;
#line 121
    __cil_tmp21 = (char *)__cil_tmp20;
#line 121
    __cil_tmp22 = (void volatile   *)__cil_tmp21;
#line 121
    mfc_get(__cil_tmp22, _src, size, 1U, 0U, 0U);
#line 122
    __cil_tmp23 = 1 << 12;
#line 122
    __cil_tmp24 = (addr64 )__cil_tmp23;
#line 122
    _src = _src + __cil_tmp24;
#line 123
    nbufs_to_xfer = nbufs_to_xfer - 1U;
    }
  } else {

  }
#line 125
  if (nbufs > 2U) {
    {
#line 126
    __cil_tmp25 = 1 << 12;
#line 126
    __cil_tmp26 = 2 * __cil_tmp25;
#line 126
    __cil_tmp27 = __cil_tmp26 * 1UL;
#line 126
    __cil_tmp28 = (unsigned long )(buf) + __cil_tmp27;
#line 126
    __cil_tmp29 = (char *)__cil_tmp28;
#line 126
    __cil_tmp30 = (void volatile   *)__cil_tmp29;
#line 126
    mfc_get(__cil_tmp30, _src, size, 2U, 0U, 0U);
#line 127
    __cil_tmp31 = 1 << 12;
#line 127
    __cil_tmp32 = (addr64 )__cil_tmp31;
#line 127
    _src = _src + __cil_tmp32;
#line 128
    nbufs_to_xfer = nbufs_to_xfer - 1U;
    }
  } else {

  }
#line 130
  if (nbufs > 3U) {
    {
#line 131
    __cil_tmp33 = 1 << 12;
#line 131
    __cil_tmp34 = 3 * __cil_tmp33;
#line 131
    __cil_tmp35 = __cil_tmp34 * 1UL;
#line 131
    __cil_tmp36 = (unsigned long )(buf) + __cil_tmp35;
#line 131
    __cil_tmp37 = (char *)__cil_tmp36;
#line 131
    __cil_tmp38 = (void volatile   *)__cil_tmp37;
#line 131
    mfc_get(__cil_tmp38, _src, size, 3U, 0U, 0U);
#line 132
    __cil_tmp39 = 1 << 12;
#line 132
    __cil_tmp40 = (addr64 )__cil_tmp39;
#line 132
    _src = _src + __cil_tmp40;
#line 133
    nbufs_to_xfer = nbufs_to_xfer - 1U;
    }
  } else {

  }
#line 136
  i = 0U;
  {
#line 138
  while (1) {
    while_continue: /* CIL Label */ ;
#line 138
    if (nbufs > 0U) {

    } else {
#line 138
      goto while_break;
    }
    {
#line 139
    __cil_tmp41 = 1 << i;
#line 139
    mask = (unsigned int )__cil_tmp41;
#line 141
    mfc_write_tag_mask(mask);
#line 142
    mfc_read_tag_status_all();
    }
    {
#line 144
    __cil_tmp42 = 1 << 12;
#line 144
    __cil_tmp43 = (unsigned int )__cil_tmp42;
#line 144
    __cil_tmp44 = i * __cil_tmp43;
#line 144
    if (__cil_tmp44 >= 0U) {
      {
#line 144
      __cil_tmp45 = 1 << 12;
#line 144
      __cil_tmp46 = __cil_tmp45 * 4;
#line 144
      __cil_tmp47 = (unsigned int )__cil_tmp46;
#line 144
      __cil_tmp48 = 1 << 12;
#line 144
      __cil_tmp49 = (unsigned int )__cil_tmp48;
#line 144
      __cil_tmp50 = i * __cil_tmp49;
#line 144
      if (__cil_tmp50 < __cil_tmp47) {
#line 144
        tmp = 1;
      } else {
#line 144
        tmp = 0;
      }
      }
    } else {
#line 144
      tmp = 0;
    }
    }
    {
#line 144
    assert(tmp);
    }
#line 149
    if (nbufs_to_xfer > 0U) {
      {
#line 150
      __cil_tmp51 = 1 << 12;
#line 150
      __cil_tmp52 = __cil_tmp51 * 1UL;
#line 150
      __cil_tmp53 = (unsigned long )(buf) + __cil_tmp52;
#line 150
      __cil_tmp54 = (char *)__cil_tmp53;
#line 150
      __cil_tmp55 = (void volatile   *)__cil_tmp54;
#line 150
      mfc_get(__cil_tmp55, _src, size, i, 0U, 0U);
#line 157
      __cil_tmp56 = 1 << 12;
#line 157
      __cil_tmp57 = (addr64 )__cil_tmp56;
#line 157
      _src = _src + __cil_tmp57;
#line 158
      nbufs_to_xfer = nbufs_to_xfer - 1U;
      }
    } else {

    }
#line 160
    if (i >= 3U) {
#line 160
      i = 0U;
    } else {
#line 160
      i = i + 1U;
    }
#line 161
    nbufs = nbufs - 1U;
  }
  while_break: /* CIL Label */ ;
  }
  {
#line 164
  __cil_tmp58 = 1 << 12;
#line 164
  __cil_tmp59 = (unsigned int )__cil_tmp58;
#line 164
  __cil_tmp60 = nbufs * __cil_tmp59;
#line 164
  __cil_tmp61 = (unsigned long long )__cil_tmp60;
#line 164
  src = src + __cil_tmp61;
#line 166
  __cil_tmp62 = (char const   * __restrict  )"%05d %5lu\n";
#line 166
  __cil_tmp63 = total_bytes + 1023UL;
#line 166
  __cil_tmp64 = __cil_tmp63 >> 10;
#line 166
  printf(__cil_tmp62, sum, __cil_tmp64);
  }
#line 167
  return (0);
}
}
