# This file is part of CPAchecker,
# a tool for configurable software verification:
# https://cpachecker.sosy-lab.org
#
# SPDX-FileCopyrightText: 2007-2026 Dirk Beyer <https://www.sosy-lab.org>
#
# SPDX-License-Identifier: Apache-2.0

# ----------------------------------------------------------------------
# This configuration file uses a parallel portfolio of different
# SMG-Analyses for MemSafety/MemCleanup properties,
# modeled after SV-COMP 2024 (also used in 2025/2026) PredatorHP.
# This utilizes 4 distinct configurations:
# - a "verifier", i.e. SMGSymEx with abstraction and full merge, no bounds or limits
# - 2 DFS hunters (PredatorHP uses bounds of 900 and 1900 CL-IR instructions, no abstraction, but isomorph merge)
# - 1 BFS hunter (no time or instruction bounds, no abstraction, but isomorph merge)
# ----------------------------------------------------------------------

# Default resource limits
#include ../../resource-limits.properties

# Use parallel portfolio of analyses
analysis.useParallelAnalyses = true

# TODO: test whether this helps, simplifying the CFA is bad for witnesses, but we don't use witnesses
cfa.simplifyCfa = false

parallelAlgorithm.configFiles = smgSymbolicExecution-merge-noFalse-memsafety.properties, \
                                smgSymbolicExecution-dfsHunter900-memsafety.properties, \
                                smgSymbolicExecution-dfsHunter1900-memsafety.properties, \
                                smgSymbolicExecution-bfsHunter-memsafety.properties
