# This file is part of CPAchecker,
# a tool for configurable software verification:
# https://cpachecker.sosy-lab.org
#
# SPDX-FileCopyrightText: 2007-2026 Dirk Beyer <https://www.sosy-lab.org>
#
# SPDX-License-Identifier: Apache-2.0

# ------------------------------------------------------------------
# SMGv2 w symbolic execution as a BFS hunter.
# See smgHP.properties for more info.
# ------------------------------------------------------------------

# Default resource limits
#include ../../resource-limits.properties

#include ../smgSymbolicExecution.properties

# This configuration is used when verifying with MemSafety/MemCleanup properties
memorysafety.config = smgSymbolicExecution-bfsHunter-memsafety.properties
memorycleanup.config = smgSymbolicExecution-bfsHunter-memsafety.properties

# Set merge to isomorphic merge only (and only at certain locations)
cpa.smg2.merge.generalPolicy = NONE
cpa.smg2.merge.policyOnLoopClosing = ISOMORPHISM_ONLY
cpa.smg2.merge.policyOnLoopHead = ISOMORPHISM_ONLY
cpa.smg2.merge.mergePolicyOnFunctionExit = ISOMORPHISM_ONLY

# TODO: Do we need a selector for the MergePolicy in stop directly?
cpa.smg2.stop.policyForStopOperator = TRY_MERGE_SMART

cpa.smg2.merge.mergeOnlyWithAbstractionPresent = false

# Prevent the merge of two abstract states where one of them
# already has at least one child state.
# Needed when merging, irrelevant else.
cpa.arg.lateMerge = PREVENT

# We only merge states at equal locations in the program.
# We use PARTITIONED, resulting in a cross-product of the used CPAs distinct partitions.
# The LocationCPA uses only Merge-SEP and is used before SMG2CPA,
# hence we get only equal locations to merge with.
analysis.reachedSet = PARTITIONED


[analysis.traversal]
order               = bfs
useReversePostorder = false
useCallstack        = false
weightedDepth       = false
