/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

#line 9 "nested_structure_noptr.c"
struct Innermost {
   int c ;
};
#line 9 "nested_structure_noptr.c"
struct Inner {
   int b ;
   struct Innermost y ;
};
#line 9 "nested_structure_noptr.c"
struct Toplev {
   int a ;
   struct Inner x ;
};
#line 69 "/usr/include/assert.h"
extern  __attribute__((__nothrow__, __noreturn__)) void __assert_fail(char const   *__assertion ,
                                                                      char const   *__file ,
                                                                      unsigned int __line ,
                                                                      char const   *__function ) ;
#line 7 "nested_structure_noptr.c"
int VERDICT_SAFE  ;
#line 19 "nested_structure_noptr.c"
int main(void) 
{ struct Toplev good ;

  {
#line 21
  good.a = 1;
#line 21
  good.x.b = 2;
#line 21
  good.x.y.c = 3;
#line 22
  good.x.y.c = 4;
#line 23
  if (good.x.y.c == 4) {

  } else {
    {
#line 23
    __assert_fail("good.x.y.c == 4", "nested_structure_noptr.c", 23U, "main");
    }
  }
#line 24
  return (0);
}
}
