/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

#line 211 "/usr/lib64/gcc/x86_64-suse-linux/4.5/include/stddef.h"
typedef unsigned long size_t;
#line 9 "rule60_list.c"
struct list_head {
   struct list_head *prev ;
   struct list_head *next ;
   int inserted ;
};
#line 69 "/usr/include/assert.h"
extern  __attribute__((__nothrow__, __noreturn__)) void __assert_fail(char const   *__assertion ,
                                                                      char const   *__file ,
                                                                      unsigned int __line ,
                                                                      char const   *__function ) ;
#line 51 "/usr/include/malloc.h"
extern  __attribute__((__nothrow__)) void *malloc(size_t __size )  __attribute__((__malloc__)) ;
#line 6 "rule60_list.c"
int VERDICT_SAFE  ;
#line 7 "rule60_list.c"
int CURRENTLY_SAFE  ;
#line 14 "rule60_list.c"
static void list_add(struct list_head *new , struct list_head *head ) 
{ 

  {
#line 15
  if (new->inserted == 0) {

  } else {
    {
#line 15
    __assert_fail("new->inserted==0", "rule60_list.c", 15U, "list_add");
    }
  }
#line 16
  new->inserted = 1;
#line 17
  return;
}
}
#line 19 "rule60_list.c"
static void list_del(struct list_head *entry ) 
{ 

  {
#line 20
  if (entry->inserted == 1) {

  } else {
    {
#line 20
    __assert_fail("entry->inserted==1", "rule60_list.c", 20U, "list_del");
    }
  }
#line 21
  entry->inserted = 0;
#line 22
  return;
}
}
#line 24 "rule60_list.c"
static struct list_head head  ;
#line 26 "rule60_list.c"
int main(void) 
{ struct list_head *dev ;
  void *tmp ;

  {
  {
#line 28
  tmp = malloc(sizeof(*dev));
#line 28
  dev = (struct list_head *)tmp;
  }
#line 29
  if ((unsigned long )dev != (unsigned long )((void *)0)) {
    {
#line 30
    dev->inserted = 0;
#line 31
    list_add(dev, & head);
#line 32
    list_del(dev);
#line 33
    list_add(dev, & head);
    }
  } else {

  }
#line 35
  return (0);
}
}
