/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

#line 11 "regression-tests/blast_correct.c"
typedef int rr;
#line 71 "/usr/include/assert.h"
extern void __assert_fail(char const   *__assertion , char const   *__file , unsigned int __line ,
                          char const   *__function ) ;
#line 13 "regression-tests/blast_correct.c"
rr yyyy  ;
#line 16 "regression-tests/blast_correct.c"
rr *getrr(void) 
{ rr *r ;

  {
#line 18
  r = & yyyy;
#line 19
  *r = 1;
#line 20
  return (r);
}
}
#line 23 "regression-tests/blast_correct.c"
int main(void) 
{ rr *ptr1 ;
  rr *ptr2 ;
  rr __cil_tmp3 ;
  rr __cil_tmp4 ;

  {
#line 29
  ptr1 = & yyyy;
#line 29
  *ptr1 = 1;
#line 31
  ptr2 = ptr1;
  {
#line 32
  __cil_tmp3 = *ptr2;
#line 32
  if (__cil_tmp3 == 1) {

  } else {
#line 32
    __assert_fail("*ptr2 == 1", "regression-tests/blast_correct.c", 32U, "main");
  }
  }
#line 33
  *ptr2 = 2;
#line 35
  ptr2 = ptr1;
  {
#line 36
  __cil_tmp4 = *ptr2;
#line 36
  if (__cil_tmp4 == 1) {

  } else {
#line 36
    __assert_fail("*ptr2 == 1", "regression-tests/blast_correct.c", 36U, "main");
  }
  }
#line 37
  *ptr2 = 2;
#line 39
  return (0);
}
}
