/* Generated by CIL v. 1.3.6 */
/* print_CIL_Input is true */

#line 1 "test05.c"
int special_case(int x , int y ) ;
#line 3 "test05.c"
int foo(int x , int y , int z ) 
{ 

  {
#line 4
  z = 1;
#line 6
  if (z == 2) {
#line 7
    special_case(y, x);
  } else {
#line 10
    x = y;
  }
#line 13
  return (y);
}
}
#line 16 "test05.c"
int special_case(int x , int y ) 
{ 

  {
#line 18
  while (1) {
#line 18
    if (y < x) {

    } else {
#line 18
      break;
    }
#line 19
    x -= 1;
  }
#line 22
  return (10);
}
}
