# This file is part of CPAchecker,
# a tool for configurable software verification:
# https://cpachecker.sosy-lab.org
#
# SPDX-FileCopyrightText: 2007-2020 Dirk Beyer <https://www.sosy-lab.org>
#
# SPDX-License-Identifier: Apache-2.0

# ----------------------------------------------------------------------
# This configuration file uses the TestCaseGeneratorAlgorithm.
# ----------------------------------------------------------------------

analysis.useTestCaseGeneratorAlgorithm = true

cpa = cpa.arg.ARGCPA
ARGCPA.cpa = cpa.composite.CompositeCPA
CompositeCPA.cpas = cpa.location.LocationCPA, cpa.callstack.CallstackCPA, cpa.functionpointer.FunctionPointerCPA, cpa.value.ValueAnalysisCPA, cpa.constraints.ConstraintsCPA, cpa.testtargets.TestTargetCPA, cpa.automaton.ControlAutomatonCPA TerminatingFunctions

TerminatingFunctions.cpa.automaton.inputFile = ../../specification/test-comp-terminatingfunctions.spc

# harness export cannot deal with aggregated blocks
cpa.composite.aggregateBasicBlocks = false

cpa.value.optimizeBooleanVariables = false
cpa.value.assignEqualityAssumptions = false
cpa.value.unknownValueHandling = INTRODUCE_SYMBOLIC

cpa.constraints.removeOutdated = false

# use counterexample information from counterexample check
analysis.checkCounterexamples = true
counterexample.checker = CPACHECKER
counterexample.checker.config = ../../cex-checks/predicateAnalysis-as-cex-check-testgeneration.properties

cpa.predicate.ignoreIrrelevantVariables = false

# If not already done by the analysis, store a found counterexample in the ARG
# disable because storing occurs outside test generation algorithm
analysis.alwaysStoreCounterexamples = false

# needed to get proper test cases from value analysis (use model from CEX check)
counterexample.checker.changeCEXInfo = true

# allow imprecise counterexamples
counterexample.export.allowImpreciseCounterexamples = true

# deactivate, led to assertion failures
counterexample.continueAfterInfeasibleError = false

testcase.inStats = false

[analysis.traversal]
order = bfs
useReversePostorder = false
useCallstack = false
weightedDepth = true
random.exponent = 8