# This file is part of CPAchecker,
# a tool for configurable software verification:
# https://cpachecker.sosy-lab.org
#
# SPDX-FileCopyrightText: 2026 Dirk Beyer <https://www.sosy-lab.org>
#
# SPDX-License-Identifier: Apache-2.0

analysis.traversal.order = dfs
cpa.composite.aggregateBasicBlocks = false
cpa.composite.singleGlobalStatementPerBasicBlock = true
cpa.composite.callLocationCPAForAllEdgesInBasicBlocks = true
cpa.callstack.unsupportedFunctions={}

analysis.traversal.useReversePostorder = false
analysis.traversal.useNumberOfThreads  = true
analysis.traversal.weightedDepth       = false