# This file is part of CPAchecker,
# a tool for configurable software verification:
# https://cpachecker.sosy-lab.org
#
# SPDX-FileCopyrightText: 2026 Dirk Beyer <https://www.sosy-lab.org>
#
# SPDX-License-Identifier: Apache-2.0

cpa = cpa.arg.ARGCPA
ARGCPA.cpa = cpa.por.PORCPA
PORCPA.cpa = cpa.composite.CompositeCPA

analysis.traversal.order = dfs
cpa.composite.aggregateBasicBlocks = false
cpa.callstack.unsupportedFunctions=pthread_key_create,pthread_getspecific,pthread_setspecific,pthread_cond_wait,pthread_cond_signal,strcpy

cpa.por.aggregateBasicBlocks = true

analysis.traversal.useReversePostorder = false
analysis.traversal.useNumberOfThreads  = true
analysis.traversal.weightedDepth       = false