# This file is part of CPAchecker,
# a tool for configurable software verification:
# https://cpachecker.sosy-lab.org
#
# SPDX-FileCopyrightText: 2026 Dirk Beyer <https://www.sosy-lab.org>
#
# SPDX-License-Identifier: Apache-2.0

# ----------------------------------------------------------------------
# For SV-COMP 2027 leaf configurations that do not otherwise define
# cpa.callstack.unsupportedFunctions.
# This reproduces the top-level list
# from svcomp27.properties and additionally blacklists __VERIFIER_nondet_memory:
# analyses without support for this method may silently under-approximate the possible values
# of nondet memory. So this must be detected and aborted early.
# ----------------------------------------------------------------------

cpa.callstack.unsupportedFunctions=pthread_create,pthread_key_create,sin,cos,__builtin_uaddl_overflow,_longjmp,longjmp,siglongjmp,atexit,__VERIFIER_nondet_memory
