# This file is part of CPAchecker,
# a tool for configurable software verification:
# https://cpachecker.sosy-lab.org
#
# SPDX-FileCopyrightText: 2007-2026 Dirk Beyer <https://www.sosy-lab.org>
#
# SPDX-License-Identifier: Apache-2.0

# ------------------------------------------------------------------
# This configuration file uses symbolic execution to check for
# overflows.
# A bit-precise predicate analysis is used to cross-check
# counterexamples.
# ------------------------------------------------------------------

#include symbolicExecution.properties
#include overflow.properties

counterexample.checker.config = ../cex-checks/predicateAnalysis-as-cex-check-overflows.properties

CompositeCPA.cpas = cpa.location.LocationCPA, \
                    cpa.callstack.CallstackCPA, \
                    cpa.functionpointer.FunctionPointerCPA, \
                    cpa.value.ValueAnalysisCPA, \
                    cpa.constraints.ConstraintsCPA, \
                    cpa.overflow.OverflowCPA, \
                    $specification
