# This file is part of CPAchecker,
# a tool for configurable software verification:
# https://cpachecker.sosy-lab.org
#
# SPDX-FileCopyrightText: 2007-2020 Dirk Beyer <https://www.sosy-lab.org>
#
# SPDX-License-Identifier: Apache-2.0

# Variables classified as irrelevant might be in fact relevant,
cpa.predicate.ignoreIrrelevantVariables = false

# Memset enables us to solve around 1300 extra tasks
# in the overflow category. Analysis done for SV-COMP 27
cpa.predicate.enableMemoryAssignmentFunctions = true

# Termination analysis requires the TerminationToSafetyAlgorithm.
analysis.algorithm.terminationToSafety = true

cpa.predicate.blk.alwaysAtLoops=true
cpa.predicate.blk.alwaysAtFunctions = false

# Options for integer encoding
solver.nonLinearArithmetic=USE
cpa.predicate.encodeBitvectorAs=INTEGER
cpa.predicate.encodeFloatAs=RATIONAL
cpa.terminationviamemory.addConstraintsToPreventOverflows=true
cpa.terminationviamemory.checkUFsInIntegerEncoding=true

cpa = cpa.arg.ARGCPA
ARGCPA.cpa = cpa.composite.CompositeCPA

CompositeCPA.cpas = cpa.location.LocationCPA, \
                    cpa.predicate.PredicateCPA, \
                    cpa.callstack.CallstackCPA, \
                    cpa.terminationviamemory.TerminationToReachCPA

# reverse postorder (a more restrictive topological ordering) is better than dfs if elements may be merged
# callstack is necessary for ABE with blocks across function boundaries to work well
[analysis.traversal]
order = bfs
