// This file is part of CPAchecker,
// a tool for configurable software verification:
// https://cpachecker.sosy-lab.org
//
// SPDX-FileCopyrightText: 2026 Dirk Beyer <https://www.sosy-lab.org>
//
// SPDX-License-Identifier: Apache-2.0

package org.sosy_lab.cpachecker.core.algorithm.to_svlib;

import com.google.common.collect.ImmutableList;
import java.io.IOException;
import java.io.PrintStream;
import java.io.Serial;
import java.io.Writer;
import java.nio.charset.Charset;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;
import java.util.logging.Level;
import org.checkerframework.checker.nullness.qual.Nullable;
import org.sosy_lab.common.ShutdownNotifier;
import org.sosy_lab.common.configuration.Configuration;
import org.sosy_lab.common.configuration.FileOption;
import org.sosy_lab.common.configuration.FileOption.Type;
import org.sosy_lab.common.configuration.InvalidConfigurationException;
import org.sosy_lab.common.configuration.Option;
import org.sosy_lab.common.configuration.Options;
import org.sosy_lab.common.io.IO;
import org.sosy_lab.common.log.LogManager;
import org.sosy_lab.cpachecker.cfa.CFA;
import org.sosy_lab.cpachecker.cfa.CFACreator;
import org.sosy_lab.cpachecker.cfa.ImmutableCFA;
import org.sosy_lab.cpachecker.cfa.Language;
import org.sosy_lab.cpachecker.cfa.ast.FileLocation;
import org.sosy_lab.cpachecker.cfa.ast.svlib.SmtLibLogic;
import org.sosy_lab.cpachecker.cfa.model.FunctionEntryNode;
import org.sosy_lab.cpachecker.cfa.model.c.CFunctionEntryNode;
import org.sosy_lab.cpachecker.cfa.parser.svlib.antlr.SvLibCurrentScope;
import org.sosy_lab.cpachecker.cfa.parser.svlib.ast.SvLibProcedureDeclaration;
import org.sosy_lab.cpachecker.cfa.parser.svlib.ast.SvLibScript;
import org.sosy_lab.cpachecker.cfa.parser.svlib.ast.commands.SvLibCommand;
import org.sosy_lab.cpachecker.cfa.parser.svlib.ast.commands.SvLibProceduresRecDefinitionCommand;
import org.sosy_lab.cpachecker.cfa.parser.svlib.ast.commands.SvLibSetInfoCommand;
import org.sosy_lab.cpachecker.cfa.parser.svlib.ast.commands.SvLibSetLogicCommand;
import org.sosy_lab.cpachecker.cfa.parser.svlib.ast.commands.SvLibVerifyCallCommand;
import org.sosy_lab.cpachecker.cfa.parser.svlib.ast.statements.SvLibStatement;
import org.sosy_lab.cpachecker.core.AnalysisDirection;
import org.sosy_lab.cpachecker.core.CPAcheckerResult.Result;
import org.sosy_lab.cpachecker.core.CoreComponentsFactory;
import org.sosy_lab.cpachecker.core.algorithm.Algorithm;
import org.sosy_lab.cpachecker.core.interfaces.ConfigurableProgramAnalysis;
import org.sosy_lab.cpachecker.core.interfaces.Statistics;
import org.sosy_lab.cpachecker.core.interfaces.StatisticsProvider;
import org.sosy_lab.cpachecker.core.reachedset.AggregatedReachedSets;
import org.sosy_lab.cpachecker.core.reachedset.ReachedSet;
import org.sosy_lab.cpachecker.core.reachedset.UnmodifiableReachedSet;
import org.sosy_lab.cpachecker.core.specification.Specification;
import org.sosy_lab.cpachecker.exceptions.CPAException;
import org.sosy_lab.cpachecker.exceptions.CPATransferException;
import org.sosy_lab.cpachecker.exceptions.ParserException;
import org.sosy_lab.cpachecker.util.predicates.pathformula.PathFormulaManager;
import org.sosy_lab.cpachecker.util.predicates.pathformula.PathFormulaManagerImpl;
import org.sosy_lab.cpachecker.util.predicates.pathformula.ctoformula.CFormulaEncodingOptions;
import org.sosy_lab.cpachecker.util.predicates.pathformula.ctoformula.CtoFormulaConverter;
import org.sosy_lab.cpachecker.util.predicates.pathformula.ctoformula.CtoFormulaTypeHandler;
import org.sosy_lab.cpachecker.util.predicates.smt.FormulaManagerView;
import org.sosy_lab.cpachecker.util.predicates.smt.Solver;
import org.sosy_lab.cpachecker.util.statistics.StatTimer;
import org.sosy_lab.cpachecker.util.svlibwitnessexport.FormulaToSvLibVisitor;

@Options(prefix = "analysis.algorithm.toSvLib")
public class CToSvLibAlgorithm implements Algorithm, StatisticsProvider, AutoCloseable {

  @Option(
      secure = true,
      description =
          "Path to configuration file to be used for analysis of the transformed script. If no"
              + " path has been specified, the configuration for predicate analysis for SV-LIB"
              + " will be used as default.")
  @FileOption(Type.OPTIONAL_INPUT_FILE)
  private @Nullable Path svLibAnalysisConfiguration = null;

  @Option(
      secure = true,
      description =
          "If the transformation to SV-LIB should be performed as a preprocessing step"
              + " before the main analysis of the generated SV-LIB script begins, set to true."
              + "If the transformed SV-LIB script should just be exported and analyzed externally,"
              + " set to false.")
  private boolean runAnalysis = false;

  @Option(secure = true, description = "Export SV-LIB script generated by transformation to file.")
  @FileOption(Type.OUTPUT_FILE)
  private @Nullable Path scriptPath = Path.of("transformedScript.svlib");

  private final CFA cfa;

  private final LogManager logger;
  private final ShutdownNotifier shutdownNotifier;
  private final Configuration config;
  private final Specification specification;
  private final Solver solver;
  private final FormulaManagerView formulaManager;
  private final PathFormulaManager pathFormulaManager;
  private final CtoFormulaConverter converter;

  private final SvLibCurrentScope scope;
  private final FormulaToSvLibVisitor formulaToSvLibVisitor;

  private final TransformationStatistics transformationStatistics;

  /**
   * Transforms the CFA of a C program to a SvLibScript. At the moment in development and works
   * currently only for a limited subset of the C language.
   *
   * @throws InvalidConfigurationException If the program to be transformed is not a C program
   */
  public CToSvLibAlgorithm(
      Configuration pConfiguration,
      Specification pSpecification,
      LogManager pLogManager,
      ShutdownNotifier pShutdownNotifier,
      CFA pCfa)
      throws InvalidConfigurationException {
    pConfiguration.inject(this);

    if (pCfa.getLanguage() != Language.C) {
      throw new InvalidConfigurationException(
          "Currently only C programs can be transformed to SV-LIB");
    }
    if (runAnalysis && svLibAnalysisConfiguration == null) {
      throw new InvalidConfigurationException(
          "If runAnalysis is enabled, then a configuration for the analysis of the transformed"
              + " script has to be provided.");
    }

    config = pConfiguration;
    specification = pSpecification;
    logger = pLogManager;
    shutdownNotifier = pShutdownNotifier;
    cfa = pCfa;

    solver = Solver.create(config, logger, shutdownNotifier);
    formulaManager = solver.getFormulaManager();
    pathFormulaManager =
        new PathFormulaManagerImpl(
            solver.getFormulaManager(),
            config,
            logger,
            shutdownNotifier,
            cfa,
            AnalysisDirection.FORWARD);
    converter =
        new CtoFormulaConverter(
            new CFormulaEncodingOptions(config),
            solver.getFormulaManager(),
            cfa.getMachineModel(),
            cfa.getVarClassification(),
            logger,
            shutdownNotifier,
            new CtoFormulaTypeHandler(logger, cfa.getMachineModel()),
            AnalysisDirection.FORWARD);

    scope = new SvLibCurrentScope();
    formulaToSvLibVisitor = new FormulaToSvLibVisitor(solver.getFormulaManager(), scope);
    transformationStatistics = new TransformationStatistics();
  }

  /**
   * Transforms the {@link CFA} of a C program to a {@link SvLibScript}.
   *
   * @return The SvLibScript generated from the CFA
   */
  SvLibScript transformCfaToSvLibScript() throws CPATransferException, InterruptedException {
    ImmutableList.Builder<SvLibCommand> commandsCollector = ImmutableList.builder();
    commandsCollector.add(
        new SvLibSetLogicCommand(SmtLibLogic.ALL, FileLocation.DUMMY),
        new SvLibSetInfoCommand(":format-version", "1.0", FileLocation.DUMMY),
        new SvLibSetInfoCommand(
            ":source", cfa.getFileNames().getFirst().getFileName().toString(), FileLocation.DUMMY),
        new SvLibSetInfoCommand(":producer", "CPAchecker", FileLocation.DUMMY));

    // 1. Step: Initialize CurrentScope with declarations of procedures and global variables,
    // global variables are added to scope +  declaration commands are added to commandsCollector
    transformationStatistics.initializationTime.start();
    try {
      CToSvLibInitializer initializer =
          new CToSvLibInitializer(
              logger, cfa, scope, formulaManager, pathFormulaManager, converter);
      initializer.initialize(commandsCollector);
    } finally {
      transformationStatistics.initializationTime.stop();
    }

    // 2. Step: transform each function to a procedure body
    transformationStatistics.transformationTime.start();
    ImmutableList.Builder<SvLibProcedureDeclaration> procedureDeclarationCollector =
        ImmutableList.builder();
    ImmutableList.Builder<SvLibStatement> procedureBodiesCollector = ImmutableList.builder();

    CToSvLibTransformation transformation =
        new CToSvLibTransformation(
            cfa, formulaManager, pathFormulaManager, formulaToSvLibVisitor, scope);

    try {
      for (FunctionEntryNode functionEntryNode : cfa.entryNodes()) {
        SvLibStatement procedureBody =
            transformation.transformFunction((CFunctionEntryNode) functionEntryNode);

        procedureDeclarationCollector.add(
            scope.getProcedureDeclaration(functionEntryNode.getFunctionName()));
        procedureBodiesCollector.add(procedureBody);
      }
    } finally {
      transformationStatistics.transformationTime.stop();
    }

    SvLibProceduresRecDefinitionCommand proceduresRecDefinitionCommand =
        new SvLibProceduresRecDefinitionCommand(
            FileLocation.DUMMY,
            procedureDeclarationCollector.build(),
            procedureBodiesCollector.build());
    commandsCollector.add(proceduresRecDefinitionCommand);

    // 3. Step: encode property
    CToSvLibPropertyEncoder propertyEncoder = new CToSvLibPropertyEncoder(specification);
    propertyEncoder.encodeProperty(commandsCollector);

    commandsCollector.add(
        new SvLibVerifyCallCommand(
            scope.getProcedureDeclaration(cfa.getMainFunction().getFunctionName()),
            ImmutableList.of(),
            FileLocation.DUMMY));

    ImmutableList<SvLibCommand> commandsCollectorBuilt = commandsCollector.build();

    transformationStatistics.numberOfCommands = commandsCollectorBuilt.size();
    return new SvLibScript(commandsCollectorBuilt, FileLocation.DUMMY);
  }

  @Override
  public AlgorithmStatus run(ReachedSet pReachedSet) throws CPAException, InterruptedException {

    SvLibScript transformationResultScript;

    logger.log(Level.INFO, "Starting transformation of the input C program to SV-LIB.");
    transformationStatistics.totalTransformationTime.start();
    try {
      transformationResultScript = transformCfaToSvLibScript();
    } finally {
      transformationStatistics.totalTransformationTime.stop();
    }
    logger.log(Level.INFO, "Finished transformation of the input C program to SV-LIB.");

    if (!runAnalysis) {
      handleExport(transformationResultScript.toASTString());
      return AlgorithmStatus.NO_PROPERTY_CHECKED;
    }

    ImmutableCFA newSvLibCfa;
    final CoreComponentsFactory coreComponents;
    final ConfigurableProgramAnalysis cpa;
    Algorithm innerAlgorithm;
    try {
      // svLibAnalysisConfiguration != null is already check in the constructor
      assert svLibAnalysisConfiguration != null;
      Configuration innerConfig =
          Configuration.builder().loadFromFile(svLibAnalysisConfiguration).build();
      logger.log(Level.INFO, "Inner configuration loaded.");

      CFACreator cfaCreator = new CFACreator(innerConfig, logger, shutdownNotifier);
      logger.log(Level.INFO, "New CFACreator created.");
      newSvLibCfa = cfaCreator.parseSourceAndCreateCFA(transformationResultScript.toASTString());
      logger.log(Level.INFO, "CFA for SvLibScript created.");

      coreComponents =
          new CoreComponentsFactory(
              innerConfig, logger, shutdownNotifier, AggregatedReachedSets.empty(), newSvLibCfa);
      logger.log(Level.INFO, "New CoreComponentsFactory created.");

      Path innerSpecPath = Path.of("config", "specification", "correct-tags.spc");
      logger.log(
          Level.INFO,
          innerSpecPath.toAbsolutePath().toString());

      Specification svLibSpecification =
          Specification.fromFiles(
              ImmutableList.of(
                  innerSpecPath.toAbsolutePath()),
              newSvLibCfa,
              innerConfig,
              logger,
              shutdownNotifier);
      logger.log(Level.INFO, "Specification correct-tags.spc loaded.");

      cpa = coreComponents.createCPA(svLibSpecification);
      logger.log(Level.INFO, "CPA created.");
      if (cpa instanceof StatisticsProvider statisticsProvider) {
        statisticsProvider.collectStatistics(transformationStatistics.innerStatistics);
      }

      innerAlgorithm = coreComponents.createAlgorithm(cpa, svLibSpecification);
      if (innerAlgorithm instanceof StatisticsProvider statisticsProvider) {
        statisticsProvider.collectStatistics(transformationStatistics.innerStatistics);
      }
    } catch (InvalidConfigurationException e) {
      throw new UnsupportedTransformationException(
          "Building the algorithm which should be run on the transformed SV-LIB script failed.", e);
    } catch (ParserException e) {
      throw new UnsupportedOperationException(
          "Failed to create a CFA for the transformed SV-LIB script.", e);
    } catch (IOException e) {
      throw new UnsupportedOperationException(
          "Failed to load configuration for analysis of transformed SV-LIB script.", e);
    }

    // Prepare new reached set
    pReachedSet.clear();
    coreComponents.initializeReachedSet(pReachedSet, newSvLibCfa.getMainFunction(), cpa);

    AlgorithmStatus algorithmStatus;
    transformationStatistics.innerAnalysisTimer.start();
    try {
      algorithmStatus = innerAlgorithm.run(pReachedSet);
    } finally {
      transformationStatistics.innerAnalysisTimer.stop();
    }
    return algorithmStatus;
  }

  private void handleExport(String pOutputScript) {
    // write script, if the path is successfully determined
    if (scriptPath != null) {
      try {
        try (Writer writer = IO.openOutputFile(scriptPath, Charset.defaultCharset())) {
          writer.write(pOutputScript);
          logger.log(Level.INFO, "Transformed script exported to: " + scriptPath);
        }
      } catch (IOException e) {
        logger.logUserException(
            Level.WARNING,
            e,
            "An IO error occurred while writing the output script. The transformed script was not"
                + " exported.");
      }
    } else {
      logger.log(Level.WARNING, "Could not determine path for transformed script.");
    }
  }

  @Override
  public void collectStatistics(Collection<Statistics> statsCollection) {
    statsCollection.add(transformationStatistics);
  }

  @Override
  public void close() {
    solver.close();
  }

  private static class TransformationStatistics implements Statistics {

    private final List<Statistics> innerStatistics = new ArrayList<>();

    private final StatTimer totalTransformationTime = new StatTimer("Total transformation time");
    private final StatTimer initializationTime = new StatTimer("time to initialize scope");
    private final StatTimer transformationTime = new StatTimer("Transformation time");
    private int numberOfCommands;
    private final StatTimer innerAnalysisTimer = new StatTimer("Time for inner analysis");

    private TransformationStatistics() {
      numberOfCommands = 0;
    }

    @Override
    public void printStatistics(PrintStream out, Result result, UnmodifiableReachedSet reached) {
      out.println("Total time for transformation:     " + totalTransformationTime);
      out.println("Time to initialize scope:          " + initializationTime);
      out.println("Time for transformation:           " + transformationTime);
      out.println("Number of commands:                " + numberOfCommands);
      out.println("Time for inner analysis            " + innerAnalysisTimer);
      out.println("\n-- Inner statistics --\n");

      for (Statistics statistics : innerStatistics) {
        statistics.printStatistics(out, result, reached);
      }
    }

    @Override
    public String getName() {
      return "C to SV-LIB Transformation Statistics";
    }
  }

  private static class UnsupportedTransformationException extends CPAException {
    @Serial private static final long serialVersionUID = 7983804183988784111L;

    UnsupportedTransformationException(String msg, Throwable cause) {
      super(msg, cause);
    }
  }
}
