# This file is part of CPAchecker,
# a tool for configurable software verification:
# https://cpachecker.sosy-lab.org
#
# SPDX-FileCopyrightText: 2007-2026 Dirk Beyer <https://www.sosy-lab.org>
#
# SPDX-License-Identifier: Apache-2.0

# ----------------------------------------------------------------------
# This configuration file enables overflow checking with plain
# k-induction and exports the proven invariants as a YAML correctness
# witness.
# ----------------------------------------------------------------------

#include kInduction--overflow.properties

# Enable proof-witness export for k-induction
cpa.arg.yamlProofWitness = witness.yml
cpa.arg.exportYamlCorrectnessWitness = true
