/* Generated by CIL v. 1.5.1 */
/* print_CIL_Input is true */

#line 1 "../../scopingTest2.c"
int main(void) 
{ 
  int i ;
  int i___0 ;
  int a ;

  {
#line 2
  i = 0;
#line 5
  i___0 = 5;
#line 7
  a = 0;
#line 9
  return (0);
}
}
