# This file is part of CPAchecker,
# a tool for configurable software verification:
# https://cpachecker.sosy-lab.org
#
# SPDX-FileCopyrightText: 2020 Dirk Beyer <https://www.sosy-lab.org>
#
# SPDX-License-Identifier: Apache-2.0

#include valueAnalysis.properties

CompositeCPA.cpas = cpa.location.LocationCPA, cpa.callstack.CallstackCPA, cpa.functionpointer.FunctionPointerCPA, cpa.value.ValueAnalysisCPA, cpa.constraints.ConstraintsCPA, cpa.acsl.AcslCPA

cpa.value.unknownValueHandling = INTRODUCE_SYMBOLIC

analysis.traversal.order = bfs
analysis.traversal.weightedDepth = true
analysis.traversal.random.exponent = 8
analysis.traversal.useReversePostorder = false
analysis.traversal.useCallstack        = false

analysis.algorithm.CEGAR = true
cegar.refiner = cpa.value.symbolic.refiner.SymbolicValueAnalysisRefiner

cpa.value.refinement.restart=ROOT

cpa.value.optimizeBooleanVariables = false
cpa.value.assignEqualityAssumptions = false

cpa.constraints.removeOutdated = false

analysis.checkCounterexamples = true
