# This file is part of CPAchecker,
# a tool for configurable software verification:
# https://cpachecker.sosy-lab.org
#
# SPDX-FileCopyrightText: 2020 Dirk Beyer <https://www.sosy-lab.org>
#
# SPDX-License-Identifier: Apache-2.0

#include predicateAnalysis.properties
cpa.predicate.invariants.appendToPathFormula=true
cpa.predicate.invariants.appendToAbstractionFormula=true

solver.interpolationSolver=MATHSAT5
solver.solver=Z3

# ARGCPA is necessary for refinement and has to be the top-level CPA
cpa = cpa.arg.ARGCPA
ARGCPA.cpa = cpa.composite.CompositeCPA

CompositeCPA.cpas = cpa.location.LocationCPA, cpa.value.ValueAnalysisCPA, cpa.predicate.PredicateCPA, cpa.acsl.AcslCPA