# This file is part of CPAchecker,
# a tool for configurable software verification:
# https://cpachecker.sosy-lab.org
#
# SPDX-FileCopyrightText: 2020 Dirk Beyer <https://www.sosy-lab.org>
#
# SPDX-License-Identifier: Apache-2.0
# Use parallel portfolio of analyses
analysis.useParallelAnalyses=true

analysis.algorithm.CEGAR               = true
cegar.refiner                          = cpa.value.refiner.ValueAnalysisRefiner

# The analyses used for reachability properties.
parallelAlgorithm.configFiles = acslCpa-acsl.properties::supply-reached, \
                                acslCpa-predicate.properties::supply-reached