# This file is part of CPAchecker,
# a tool for configurable software verification:
# https://cpachecker.sosy-lab.org
#
# SPDX-FileCopyrightText: 2007-2026 Dirk Beyer <https://www.sosy-lab.org>
#
# SPDX-License-Identifier: Apache-2.0

// Data-flow analysis using abstract domain based on interval expression,
// checking for overflows.
// This configuration incrementally refines its precision
// until it can prove the program safe or it reaches the maximum precision.

#include includes/resource-limits.properties
#include includes/overflow.properties

specification = specification/overflow.spc

# This is the configuration used when verifying the overflow property
overflow.config = dataFlowAnalysis--overflow.properties

analysis.useParallelAnalyses = true
parallelAlgorithm.configFiles = components/dataFlowAnalysis--overflow.properties::refinable

[cpa.invariants]
  maximumFormulaDepth = 1
  interestingVariableLimit = 0
  abstractionStateFactory = ENTERING_EDGES
