# This file is part of CPAchecker,
# a tool for configurable software verification:
# https://cpachecker.sosy-lab.org
#
# SPDX-FileCopyrightText: 2007-2020 Dirk Beyer <https://www.sosy-lab.org>
#
# SPDX-License-Identifier: Apache-2.0

# allows the execution of a distributed predicate analysis by
# spawning workers parallely analyzing blocks
# workers can produce summaries for blocks in two directions: forward and backward
# the communication is based on messages

#include dss-symbolic.properties

[distributedSummaries.worker]
forwardConfiguration=distributed-summary-synthesis/dss-symbolic-execution-with-inlining.properties

[distributedSummaries]
# configure worker
decomposition.decompositionType=INLINING_DECOMPOSITION
