# This file is part of CPAchecker,
# a tool for configurable software verification:
# https://cpachecker.sosy-lab.org
#
# SPDX-FileCopyrightText: 2026 Dirk Beyer <https://www.sosy-lab.org>
#
# SPDX-License-Identifier: Apache-2.0

# Single-run DSS baseline with configurable analysis optimizations disabled.
#include distributed-summary-synthesis/dss-base.properties
#include includes/resource-limits.properties
specification=specification/default.spc

distributedSummaries.abstractAtBlockEntry=false
distributedSummaries.combineStates=false
distributedSummaries.sharePrecision=false
distributedSummaries.cacheViolationConditions=false
distributedSummaries.compressMessages=false
distributedSummaries.combineVcsByHash=false
distributedSummaries.blockAnalysisType=ALWAYS_REPLACE
distributedSummaries.decomposition.decompositionType=MERGE_DECOMPOSITION
distributedSummaries.decomposition.mergeBranchBoundaries=false
distributedSummaries.resetCallstackState=false
distributedSummaries.syntacticVcEquality=false
