# This file is part of CPAchecker,
# a tool for configurable software verification:
# https://cpachecker.sosy-lab.org
#
# SPDX-FileCopyrightText: 2026 Dirk Beyer <https://www.sosy-lab.org>
#
# SPDX-License-Identifier: Apache-2.0

# The optimized DSS configuration (dss.properties) with symbolic execution in the blocks.
#include dss-symbolic.properties

distributedSummaries.worker.forwardConfiguration=distributed-summary-synthesis/dss-block-analysis-symbolic-execution.properties
