# This file is part of CPAchecker,
# a tool for configurable software verification:
# https://cpachecker.sosy-lab.org
#
# SPDX-FileCopyrightText: 2007-2020 Dirk Beyer <https://www.sosy-lab.org>
#
# SPDX-License-Identifier: Apache-2.0

#include dss.properties

[distributedSummaries]
decomposition.decompositionType=MERGE_DECOMPOSITION
debug=false
combineVcsByHash=false
worker.forwardConfiguration=distributed-summary-synthesis/dss-symbolic-execution.properties