# This file is part of CPAchecker,
# a tool for configurable software verification:
# https://cpachecker.sosy-lab.org
#
# SPDX-FileCopyrightText: 2007-2020 Dirk Beyer <https://www.sosy-lab.org>
# SPDX-FileCopyrightText: 2026 Dirk Beyer <https://www.sosy-lab.org>
#
# SPDX-License-Identifier: Apache-2.0

# Default DSS coverage portfolio.
#include includes/resource-limits.properties
analysis.restartAfterUnknown=true
analysis.useLoopStructure=true
specification=specification/default.spc
restartAlgorithm.configFiles=distributed-summary-synthesis/dss-coverage-boolean.properties, distributed-summary-synthesis/dss-coverage-cartesian.properties, distributed-summary-synthesis/dss-coverage-fallback.properties
