# This file is part of CPAchecker,
# a tool for configurable software verification:
# https://cpachecker.sosy-lab.org
#
# SPDX-FileCopyrightText: 2007-2025 Dirk Beyer <https://www.sosy-lab.org>
#
# SPDX-License-Identifier: Apache-2.0

# ----------------------------------------------------------------------
# This configuration file executes a program with the SMG analysis and
# checks whether the execution violates the specification.
# Compared to execution.properties this is precise for programs that
# access memory through pointers, at the price of a higher effort per
# execution step.
# It is applicable only to programs without nondeterministic choices.
# ----------------------------------------------------------------------

#include includes/execution-smg.properties
#include includes/resource-limits.properties

specification = specification/default.spc
