# This file is part of CPAchecker,
# a tool for configurable software verification:
# https://cpachecker.sosy-lab.org
#
# SPDX-FileCopyrightText: 2026 CPAchecker contributors
#
# SPDX-License-Identifier: Apache-2.0

// ----------------------------------------------------------------------
// Variant of KInduction-prove-nontermination-strong.properties for evaluating
// only the termination fallback via unwinding assertions.
// ----------------------------------------------------------------------

#include KInduction-prove-nontermination-strong.properties

bmc.nonTerminationSkipProofForTerminationFallback = true

termination.config = KInduction-prove-nontermination-strong-fallback-only.properties
