# This file is part of CPAchecker,
# a tool for configurable software verification:
# https://cpachecker.sosy-lab.org
#
# SPDX-FileCopyrightText: 2026 CPAchecker contributors
#
# SPDX-License-Identifier: Apache-2.0

// ----------------------------------------------------------------------
// Experimental configuration for proving non-termination with a strong
// k-induction style check over loop-continuation conditions.
// ----------------------------------------------------------------------

#include components/kInduction/kInduction.properties

bmc.nonTerminationMode = true

termination.config = KInduction-prove-nontermination-strong.properties
