# This file is part of CPAchecker,
# a tool for configurable software verification:
# https://cpachecker.sosy-lab.org
#
# SPDX-FileCopyrightText: 2007-2026 Dirk Beyer <https://www.sosy-lab.org>
#
# SPDX-License-Identifier: Apache-2.0

// ----------------------------------------------------------------------
// This configuration file checks for overflows with plain k-induction,
// i.e., without an additional invariant generator.
// ----------------------------------------------------------------------

#include components/kInduction/kInduction--overflow.properties

// this automaton defines which locations are the error locations
specification = specification/overflow.spc

# This is the configuration used when verifying the overflow property
overflow.config = kInduction-plain--overflow.properties

#include includes/resource-limits.properties
