# This file is part of CPAchecker,
# a tool for configurable software verification:
# https://cpachecker.sosy-lab.org
#
# SPDX-FileCopyrightText: 2007-2020 Dirk Beyer <https://www.sosy-lab.org>
#
# SPDX-License-Identifier: Apache-2.0

#include includes/bmc-without-valueAnalysis.properties

language = SvLib

CompositeCPA.cpas = cpa.location.LocationCPA, cpa.callstack.CallstackCPA, cpa.predicate.PredicateCPA, cpa.loopbound.LoopBoundCPA, cpa.assumptions.storage.AssumptionStorageCPA, cpa.svlibsafetyspec.SvLibSafetySpecCPA, $specification

# We support non-linear arithmetic by default in SV-LIB,
# if some solver does not support it, we would like to crash
# since otherwise the results are wrong
# See also: https://gitlab.com/sosy-lab/software/cpachecker/-/issues/1464
solver.nonLinearArithmetic = USE

# Information taken from components/kInduction/kInduction-plain.properties
# since if imported directly the option cpa.value.merge is unused which our 
# pipeline does not like
# -------------------------------------------------------------------------

// enable induction for safety verification
bmc.induction = true

// do not use an additional, k-induction-based invariant generator to provide auxiliary invariants;
// just use the simple reached-set-based invariant generator
bmc.invariantGenerationStrategy = REACHED_SET

// activate iterative deepening (0 is infinite deepening)
cpa.loopbound.maxLoopIterationsUpperBound = 0

// start iterative deepening with an initial bound of 1
cpa.loopbound.maxLoopIterations = 1

// increment the bound by one in every iteration of deepening
cpa.loopbound.maxLoopIterationAdjusterFactory = INCREMENT

# ------------------------------------------------------------------------

specification = specification/correct-tags.spc
