# This file is part of CPAchecker,
# a tool for configurable software verification:
# https://cpachecker.sosy-lab.org
#
# SPDX-FileCopyrightText: 2007-2026 Dirk Beyer <https://www.sosy-lab.org>
#
# SPDX-License-Identifier: Apache-2.0

// ----------------------------------------------------------------------
// This configuration file checks for overflows with k-induction and a
// continuously-refined data-flow analysis that supplies the invariants.
// ----------------------------------------------------------------------

#include components/kInduction+Invariants/kInduction--overflow.properties

// this automaton defines which locations are the error locations
specification = specification/overflow.spc

# This is the configuration used when verifying the overflow property
overflow.config = kInduction--overflow.properties

#include includes/resource-limits.properties
