# This file is part of CPAchecker,
# a tool for configurable software verification:
# https://cpachecker.sosy-lab.org
#
# SPDX-FileCopyrightText: 2026 Dirk Beyer <https://www.sosy-lab.org>
#
# SPDX-License-Identifier: Apache-2.0

#include por-value-cegar-aa.properties
#include includes/overflow.properties

specification = specification/overflow.spc
overflow.config = por-value-cegar-aa-overflow.properties
# PointerCPA: see por-value.properties (soundness of writes through pointers).
CompositeCPA.cpas = cpa.mutex.MutexCPA, cpa.value.ValueAnalysisCPA, cpa.pointer2.PointerCPA, cpa.overflow.OverflowCPA
counterexample.checker.config = cex-checks/por-predicateAnalysis-as-cex-check-overflows.properties
