# This file is part of CPAchecker,
# a tool for configurable software verification:
# https://cpachecker.sosy-lab.org
#
# SPDX-FileCopyrightText: 2026 Dirk Beyer <https://www.sosy-lab.org>
#
# SPDX-License-Identifier: Apache-2.0

#include por-pred.properties
#include includes/witness-validation.properties

# A waypoint matches a single statement, so POR's block aggregation must be off here.
cpa.concurrent.aggregateBasicBlocks = false

witness.validation.violation.config = por-pred-validate.properties
