#include por-value.properties
#include includes/overflow.properties

specification = specification/overflow.spc
overflow.config = _test-por-value-overflow.properties
CompositeCPA.cpas = cpa.mutex.MutexCPA, cpa.value.ValueAnalysisCPA, cpa.overflow.OverflowCPA
counterexample.checker.config = cex-checks/_test-por-predicateAnalysis-as-cex-check-overflows.properties
