# This file is part of CPAchecker,
# a tool for configurable software verification:
# https://cpachecker.sosy-lab.org
#
# SPDX-FileCopyrightText: 2026 Dirk Beyer <https://www.sosy-lab.org>
#
# SPDX-License-Identifier: Apache-2.0

#include por-pred-cart.properties
# spec is inherited from por-pred-cart (default.spc); during actual witness
# validation the property file passed on the command line overrides it.
witness.validation.violation.config=por-pred-cart-validate.properties