#include por-pred.properties
#include includes/overflow.properties

specification = specification/overflow.spc
overflow.config = por-pred-overflow.properties
CompositeCPA.cpas = cpa.mutex.MutexCPA, cpa.predicate.PredicateCPA, cpa.overflow.OverflowCPA