# This file is part of CPAchecker,
# a tool for configurable software verification:
# https://cpachecker.sosy-lab.org
#
# SPDX-FileCopyrightText: 2026 Dirk Beyer <https://www.sosy-lab.org>
#
# SPDX-License-Identifier: Apache-2.0

specification = specification/sv-comp-reachability.spc
#include includes/valueAnalysis.properties
#include includes/por.properties

counterexample.checker.config = cex-checks/por-predicateAnalysis-as-cex-check.properties

CompositeCPA.cpas = cpa.mutex.MutexCPA, cpa.value.ValueAnalysisCPA

log.consoleLevel = INFO
counterexample.checker.path.file = cex.txt
cpa.value.alwaysUseQualifiedNames = true