# This file is part of CPAchecker,
# a tool for configurable software verification:
# https://cpachecker.sosy-lab.org
#
# SPDX-FileCopyrightText: 2026 Dirk Beyer <https://www.sosy-lab.org>
#
# SPDX-License-Identifier: Apache-2.0

specification = specification/sv-comp-reachability.spc
#include includes/valueAnalysis.properties
#include includes/por.properties
#include includes/nonlin-z3.properties

counterexample.checker.config = por-pred-z3.properties

CompositeCPA.cpas = cpa.mutex.MutexCPA, cpa.value.ValueAnalysisCPA

log.consoleLevel = INFO