# This file is part of CPAchecker,
# a tool for configurable software verification:
# https://cpachecker.sosy-lab.org
#
# SPDX-FileCopyrightText: 2026 Dirk Beyer <https://www.sosy-lab.org>
#
# SPDX-License-Identifier: Apache-2.0

specification = specification/sv-comp-reachability.spc
#include includes/predicateAnalysis-PredAbsRefiner-ABEl.properties
#include includes/por.properties

CompositeCPA.cpas = cpa.por.PORCPA, cpa.mutex.MutexCPA, cpa.predicate.PredicateCPA
cpa.predicate.precision.sharing = GLOBAL

log.consoleLevel = INFO
