# This file is part of CPAchecker,
# a tool for configurable software verification:
# https://cpachecker.sosy-lab.org
#
# SPDX-FileCopyrightText: 2026 Dirk Beyer <https://www.sosy-lab.org>
#
# SPDX-License-Identifier: Apache-2.0

specification = specification/default.spc
#include includes/valueAnalysis.properties
#include includes/por.properties

# path-precise cex check, not the CEGAR predicate analysis
counterexample.checker.config = cex-checks/por-predicateAnalysis-as-cex-check-z3.properties

# needed for soundness: value analysis otherwise drops pointer writes
CompositeCPA.cpas = cpa.mutex.MutexCPA, cpa.value.ValueAnalysisCPA, cpa.pointer2.PointerCPA

log.consoleLevel = INFO
cpa.value.alwaysUseQualifiedNames = true