#include por-value.properties
#include includes/overflow.properties

specification = specification/overflow.spc
overflow.config = por-value-overflow.properties
CompositeCPA.cpas = cpa.mutex.MutexCPA, cpa.value.ValueAnalysisCPA, cpa.overflow.OverflowCPA
counterexample.checker.config = cex-checks/por-predicateAnalysis-as-cex-check-overflows.properties
