# This file is part of CPAchecker,
# a tool for configurable software verification:
# https://cpachecker.sosy-lab.org
#
# SPDX-FileCopyrightText: 2026 Dirk Beyer <https://www.sosy-lab.org>
#
# SPDX-License-Identifier: Apache-2.0

specification = specification/sv-comp-reachability.spc
#include includes/predicateAnalysis-PredAbsRefiner-ABEl.properties

CompositeCPA.cpas = cpa.por.PORCPA, cpa.mutex.MutexCPA, cpa.predicate.PredicateCPA

# solver.solver = MATHSAT5

analysis.traversal.order = dfs
# cpa.composite.aggregateBasicBlocks  = false
# cpa.callstack.unsupportedFunctions = {}
# analysis.traversal.useReversePostorder = false

# cpa.predicate.ignoreIrrelevantFields = false
# cpa.predicate.ignoreIrrelevantVariables = false
log.consoleLevel = INFO
cpa.composite.aggregateBasicBlocks = false
# TODO concurrency-aware basic block aggregation is needed (at most one global access per block)
cpa.callstack.unsupportedFunctions={}