# This file is part of CPAchecker,
# a tool for configurable software verification:
# https://cpachecker.sosy-lab.org
#
# SPDX-FileCopyrightText: 2007-2020 Dirk Beyer <https://www.sosy-lab.org>
#
# SPDX-License-Identifier: Apache-2.0

#include predicateAnalysis.properties
#include includes/svlib.properties

CompositeCPA.cpas = cpa.location.LocationCPA, cpa.callstack.CallstackCPA, cpa.predicate.PredicateCPA, cpa.svlibsafetyspec.SvLibSafetySpecCPA, $specification

# We need to abstract at function heads in order to get
# reasonable function contracts
cpa.predicate.blk.alwaysAtFunctions = true

specification = specification/correct-tags.spc
