# This file is part of CPAchecker,
# a tool for configurable software verification:
# https://cpachecker.sosy-lab.org
#
# SPDX-FileCopyrightText: 2026 Dirk Beyer <https://www.sosy-lab.org>
#
# SPDX-License-Identifier: Apache-2.0

# ----------------------------------------------------------------------
# This configuration file is based on the file
# predicateAnalysis-PredAbsRefiner-ABEl.properties and extended
# by options relevant for the evaluation of the transformation
# of C programs to SV-LIB.
# ----------------------------------------------------------------------

#include includes/predicateAnalysis-PredAbsRefiner-ABEl.properties

#include includes/resource-limits.properties
specification = specification/default.spc

# For overflow checking we have an equivalent config.
overflow.config = predicateAnalysis--overflow.properties

cpa.predicate.ignoreIrrelevantVariables = false
cpa.predicate.useConstraintOptimization = false
cpa.predicate.encodeBitvectorAs = INTEGER
