# This file is part of CPAchecker,
# a tool for configurable software verification:
# https://cpachecker.sosy-lab.org
#
# SPDX-FileCopyrightText: 2026 Dirk Beyer <https://www.sosy-lab.org>
#
# SPDX-License-Identifier: Apache-2.0

# ----------------------------------------------------------------------
# This configuration file uses CEGAR with program transformations.
# ----------------------------------------------------------------------

#include includes/predicateAnalysis.properties
#include includes/resource-limits.properties

cegar.refiner = cpa.predicate.PredicateRefiner

specification = specification/default.spc

cfa.useProgramTransformations = true
algorithm.useProgramTransformationCGAR = true

analysis.checkCounterexamples = false
cpa.callstack.skipRecursion = true