# This file is part of CPAchecker,
# a tool for configurable software verification:
# https://cpachecker.sosy-lab.org
#
# SPDX-FileCopyrightText: 2026 Dirk Beyer <https://www.sosy-lab.org>
#
# SPDX-License-Identifier: Apache-2.0

# ----------------------------------------------------------------------
# This configuration file uses CEGAR with program transformations.
# ----------------------------------------------------------------------

#include predicateAnalysis.properties
#include valueAnalysis.properties

CompositeCPA.cpas = cpa.location.LocationCPA, cpa.callstack.CallstackCPA,  cpa.predicate.PredicateCPA, cpa.value.ValueAnalysisCPA

cfa.useProgramTransformations = TAIL_RECURSION_ELIMINATION
analysis.algorithm.useProgramTransformationCGAR = true

analysis.checkCounterexamples = true
cpa.arg.exportYamlCorrectnessWitness = true
cpa.callstack.skipRecursion = false
# prevent the removal of variable assignments from the abstract state
cpa.value.abstraction.alwaysAtBranch = false
cpa.value.abstraction.alwaysAtFunction = true
cpa.value.abstraction.alwaysAtLoop = false
cpa.value.abstraction.alwaysAtJoin = false