# This file is part of CPAchecker,
# a tool for configurable software verification:
# https://cpachecker.sosy-lab.org
#
# SPDX-FileCopyrightText: 2026 Dirk Beyer <https://www.sosy-lab.org>
#
# SPDX-License-Identifier: Apache-2.0

# ----------------------------------------------------------------------
# This configuration file uses CEGAR with program transformations.
# ----------------------------------------------------------------------

#include predicateAnalysis.properties

cegar.refiner = cpa.predicate.PredicateRefiner

cfa.useProgramTransformations =  LOOP_ACCELERATION, TAIL_RECURSION_ELIMINATION
analysis.algorithm.useProgramTransformationCGAR = true

analysis.checkCounterexamples = false
cpa.callstack.skipRecursion = false

# Temporary fix for failing witness export
cpa.arg.exportYamlCorrectnessWitness = true
cpa.arg.proofWitness = witness.graphml