# This file is part of CPAchecker,
# a tool for configurable software verification:
# https://cpachecker.sosy-lab.org
#
# SPDX-FileCopyrightText: 2026 Dirk Beyer <https://www.sosy-lab.org>
#
# SPDX-License-Identifier: Apache-2.0

# Run trivial rules and concrete execution in parallel, reporting the first conclusive result.
#include includes/simple-checks.properties
#include includes/resource-limits.properties

#include includes/overflow.properties

parallelAlgorithm.configFiles = trivialRules--overflow.properties, execution--overflow.properties

specification = specification/overflow.spc
