# This file is part of CPAchecker,
# a tool for configurable software verification:
# https://cpachecker.sosy-lab.org
#
# SPDX-FileCopyrightText: 2007-2025 Dirk Beyer <https://www.sosy-lab.org>
#
# SPDX-License-Identifier: Apache-2.0

# ----------------------------------------------------------------------
# This configuration file decides the reachability of an error with
# trivial rules, i.e., without reasoning about what the program
# computes. Cf. includes/trivial-rules.properties.
# ----------------------------------------------------------------------

#include includes/trivial-rules.properties
#include includes/resource-limits.properties

specification = specification/default.spc

counterexample.export.yaml = witness.yml
cpa.arg.yamlProofWitness = witness.yml