# This file is part of CPAchecker,
# a tool for configurable software verification:
# https://cpachecker.sosy-lab.org
#
# SPDX-FileCopyrightText: 2026 Dirk Beyer <https://www.sosy-lab.org>
#
# SPDX-License-Identifier: Apache-2.0

analysis.algorithm.transformToSvLib = true

# Z3 uses a formula representation that is easier to transform than that employed by MATHSAT5
solver.solver = Z3

# do not ignore variables that are irrelevant to reachability properties
cpa.predicate.ignoreIrrelevantVariables = false
cpa.predicate.encodeBitvectorAs = INTEGER
