# This file is part of CPAchecker,
# a tool for configurable software verification:
# https://cpachecker.sosy-lab.org
#
# SPDX-FileCopyrightText: 2026 Dirk Beyer <https://www.sosy-lab.org>
#
# SPDX-License-Identifier: Apache-2.0

# ----------------------------------------------------------------------
# This configuration first transforms a C input program to a SV-LIB
# script with an encoding of the sv-comp-reachability specification and
# uses predicate analysis for SV-LIB in a second step to analyse the
# script.
# ----------------------------------------------------------------------

analysis.algorithm.transformToSvLib = true
analysis.algorithm.toSvLib.runAnalysis = true
analysis.algorithm.toSvLib.svLibAnalysisConfiguration = predicateAnalysis-svlib.properties

specification = specification/sv-comp-reachability.spc

# Z3 uses a formula representation that is easier to transform than that employed by MATHSAT5
solver.solver = Z3

# do not ignore variables that are irrelevant to reachability properties
cpa.predicate.ignoreIrrelevantVariables = false
cpa.predicate.useConstraintOptimization = false
cpa.predicate.encodeBitvectorAs = INTEGER
