/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

#line 6 "dmalloc.c"

void test(int* value)
{
  *value = 256;
  *value = *value +5;
  
}


#line 4 "dmalloc.c"
int main(void) 
{ int *d ;
  int tmp ;

  {
#line 6
  tmp = CPAmalloc(8);
  
#line 6
  d = (int*)tmp;
  *d = 12;
  tmp = tmp +4;
  d = (int*)tmp;
  test(d);
  *d = *d + 75;
#line 12
  return (0);
}
}
