# This file is part of CPAchecker,
# a tool for configurable software verification:
# https://cpachecker.sosy-lab.org
#
# SPDX-FileCopyrightText: 2026 Dirk Beyer <https://www.sosy-lab.org>
#
# SPDX-License-Identifier: Apache-2.0

# Avoid expensive Boolean model enumeration if the first stage cannot finish.
#include dss-analysis.properties
distributedSummaries.worker.forwardConfiguration=dss-block-analysis-cartesian.properties
limits.time.wall=60s
