# This file is part of CPAchecker,
# a tool for configurable software verification:
# https://cpachecker.sosy-lab.org
#
# SPDX-FileCopyrightText: 2022 Dirk Beyer <https://www.sosy-lab.org>
#
# SPDX-License-Identifier: Apache-2.0
#include ../valueAnalysis-NoCegar-plain.properties
# configuration for a distributed forward predicate analysis
# see dss.properties for more information on the configuration of
# distributed summary synthesis
CompositeCPA.cpas=cpa.block.BlockCPA, cpa.location.LocationCPA, cpa.callstack.CallstackCPA, cpa.functionpointer.FunctionPointerCPA, cpa.value.ValueAnalysisCPA, $specification
# No CEGAR
dss.cpa.value.runSymExec=false
cpa.block.transfer.standardVcs=false

analysis.algorithm.CEGAR=false
analysis.checkCounterexamples=false
analysis.alwaysStoreCounterexamples=true

cpa.constraints.minimalSatCheck=false
cpa.constraints.removeOutdated=false
cpa.constraints.globalsResetIdentifiers=false

cpa.callstack.ignoreTransfer=true
cpa.callstack.domain=FLATPCC

limits.time.cpu =