# This file is part of CPAchecker,
# a tool for configurable software verification:
# https://cpachecker.sosy-lab.org
#
# SPDX-FileCopyrightText: 2026 Dirk Beyer <https://www.sosy-lab.org>
#
# SPDX-License-Identifier: Apache-2.0

# Retain finer abstraction boundaries for cases where coarsening is too expensive.
#include dss-analysis.properties
distributedSummaries.decomposition.largestHorizontalMerge=50
distributedSummaries.decomposition.mergeBranchBoundaries=false
