# This file is part of CPAchecker,
# a tool for configurable software verification:
# https://cpachecker.sosy-lab.org
#
# SPDX-FileCopyrightText: 2026 Dirk Beyer <https://www.sosy-lab.org>
#
# SPDX-License-Identifier: Apache-2.0

# Symbolic execution worker used by the optimized DSS configuration with symbolic execution.
#include dss-symbolic-execution.properties

# Allocate location states when visited, like the optimized predicate worker.
CompositeCPA.cpas=cpa.block.BlockCPA, core.algorithm.distributed_summaries.distributed_cpa.location.DssLocationCPA, cpa.callstack.DssCallstackCPA, cpa.functionpointer.FunctionPointerCPA, cpa.symbolicExecution.SymbolicExecutionCPA, $specification
