# This file is part of CPAchecker,
# a tool for configurable software verification:
# https://cpachecker.sosy-lab.org
#
# SPDX-FileCopyrightText: 2022 Dirk Beyer <https://www.sosy-lab.org>
#
# SPDX-License-Identifier: Apache-2.0
# configuration for a distributed forward predicate analysis
# see dss.properties for more information on the configuration of
# distributed summary synthesis
#include dss-value-analysis.properties
cpa.callstack.ignoreTransfer=false