/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.grammatech.cs;

public class ast_field_type implements Comparable<ast_field_type> {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected ast_field_type(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ast_field_type obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        csJNI.delete_ast_field_type(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected static long getCPtrAndDisown(ast_field_type obj) {
    if (obj != null) obj.swigCMemOwn= false;
    return getCPtr(obj);
  }

  public ast_field_type(long _inner) throws result {
    this(csJNI.new_ast_field_type(_inner), true);
  }

  public int compareTo(ast_field_type other) {
    return csJNI.ast_field_type_compareTo(swigCPtr, this, ast_field_type.getCPtr(other), other);
  }

  public boolean equals(ast_field_type other) throws result {
    return csJNI.ast_field_type_equals(swigCPtr, this, ast_field_type.getCPtr(other), other);
  }

  public int hashCode() {
    return csJNI.ast_field_type_hashCode(swigCPtr, this);
  }

  public String as_string() throws result {
    return csJNI.ast_field_type_as_string(swigCPtr, this);
  }

  public String toString() {
    return csJNI.ast_field_type_toString(swigCPtr, this);
  }

  public String name() throws result {
    return csJNI.ast_field_type_name(swigCPtr, this);
  }

  public static ast_field_type getNULL_() throws result {
    long cPtr = csJNI.ast_field_type_NULL__get();
    return (cPtr == 0) ? null : new ast_field_type(cPtr, false);
  }

  public static ast_field_type getAST() throws result {
    long cPtr = csJNI.ast_field_type_AST_get();
    return (cPtr == 0) ? null : new ast_field_type(cPtr, false);
  }

  public static ast_field_type getAST_CLASS() throws result {
    long cPtr = csJNI.ast_field_type_AST_CLASS_get();
    return (cPtr == 0) ? null : new ast_field_type(cPtr, false);
  }

  public static ast_field_type getBOOLEAN() throws result {
    long cPtr = csJNI.ast_field_type_BOOLEAN_get();
    return (cPtr == 0) ? null : new ast_field_type(cPtr, false);
  }

  public static ast_field_type getENUMERATION() throws result {
    long cPtr = csJNI.ast_field_type_ENUMERATION_get();
    return (cPtr == 0) ? null : new ast_field_type(cPtr, false);
  }

  public static ast_field_type getINT8() throws result {
    long cPtr = csJNI.ast_field_type_INT8_get();
    return (cPtr == 0) ? null : new ast_field_type(cPtr, false);
  }

  public static ast_field_type getUINT8() throws result {
    long cPtr = csJNI.ast_field_type_UINT8_get();
    return (cPtr == 0) ? null : new ast_field_type(cPtr, false);
  }

  public static ast_field_type getINT16() throws result {
    long cPtr = csJNI.ast_field_type_INT16_get();
    return (cPtr == 0) ? null : new ast_field_type(cPtr, false);
  }

  public static ast_field_type getUINT16() throws result {
    long cPtr = csJNI.ast_field_type_UINT16_get();
    return (cPtr == 0) ? null : new ast_field_type(cPtr, false);
  }

  public static ast_field_type getINT32() throws result {
    long cPtr = csJNI.ast_field_type_INT32_get();
    return (cPtr == 0) ? null : new ast_field_type(cPtr, false);
  }

  public static ast_field_type getUINT32() throws result {
    long cPtr = csJNI.ast_field_type_UINT32_get();
    return (cPtr == 0) ? null : new ast_field_type(cPtr, false);
  }

  public static ast_field_type getINT64() throws result {
    long cPtr = csJNI.ast_field_type_INT64_get();
    return (cPtr == 0) ? null : new ast_field_type(cPtr, false);
  }

  public static ast_field_type getUINT64() throws result {
    long cPtr = csJNI.ast_field_type_UINT64_get();
    return (cPtr == 0) ? null : new ast_field_type(cPtr, false);
  }

  public static ast_field_type getINT128() throws result {
    long cPtr = csJNI.ast_field_type_INT128_get();
    return (cPtr == 0) ? null : new ast_field_type(cPtr, false);
  }

  public static ast_field_type getUINT128() throws result {
    long cPtr = csJNI.ast_field_type_UINT128_get();
    return (cPtr == 0) ? null : new ast_field_type(cPtr, false);
  }

  public static ast_field_type getFLT32() throws result {
    long cPtr = csJNI.ast_field_type_FLT32_get();
    return (cPtr == 0) ? null : new ast_field_type(cPtr, false);
  }

  public static ast_field_type getFLT64() throws result {
    long cPtr = csJNI.ast_field_type_FLT64_get();
    return (cPtr == 0) ? null : new ast_field_type(cPtr, false);
  }

  public static ast_field_type getFLT96() throws result {
    long cPtr = csJNI.ast_field_type_FLT96_get();
    return (cPtr == 0) ? null : new ast_field_type(cPtr, false);
  }

  public static ast_field_type getFLT128() throws result {
    long cPtr = csJNI.ast_field_type_FLT128_get();
    return (cPtr == 0) ? null : new ast_field_type(cPtr, false);
  }

  public static ast_field_type getCONST_STR64() throws result {
    long cPtr = csJNI.ast_field_type_CONST_STR64_get();
    return (cPtr == 0) ? null : new ast_field_type(cPtr, false);
  }

  public static ast_field_type getCONST_STR() throws result {
    long cPtr = csJNI.ast_field_type_CONST_STR_get();
    return (cPtr == 0) ? null : new ast_field_type(cPtr, false);
  }

  public static ast_field_type getABS_LOC() throws result {
    long cPtr = csJNI.ast_field_type_ABS_LOC_get();
    return (cPtr == 0) ? null : new ast_field_type(cPtr, false);
  }

  public static ast_field_type getRESERVED() throws result {
    long cPtr = csJNI.ast_field_type_RESERVED_get();
    return (cPtr == 0) ? null : new ast_field_type(cPtr, false);
  }

}
