/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.grammatech.cs;

public class ast_traverse_flags implements Comparable<ast_traverse_flags> {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected ast_traverse_flags(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ast_traverse_flags obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        csJNI.delete_ast_traverse_flags(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected static long getCPtrAndDisown(ast_traverse_flags obj) {
    if (obj != null) obj.swigCMemOwn= false;
    return getCPtr(obj);
  }

  public ast_traverse_flags(long _inner) throws result {
    this(csJNI.new_ast_traverse_flags(_inner), true);
  }

  public int compareTo(ast_traverse_flags other) {
    return csJNI.ast_traverse_flags_compareTo(swigCPtr, this, ast_traverse_flags.getCPtr(other), other);
  }

  public boolean equals(ast_traverse_flags other) throws result {
    return csJNI.ast_traverse_flags_equals(swigCPtr, this, ast_traverse_flags.getCPtr(other), other);
  }

  public int hashCode() {
    return csJNI.ast_traverse_flags_hashCode(swigCPtr, this);
  }

  public String as_string() throws result {
    return csJNI.ast_traverse_flags_as_string(swigCPtr, this);
  }

  public String toString() {
    return csJNI.ast_traverse_flags_toString(swigCPtr, this);
  }

  public String name() throws result {
    return csJNI.ast_traverse_flags_name(swigCPtr, this);
  }

  public ast_traverse_flags or_(ast_traverse_flags b) throws result {
    return new ast_traverse_flags(csJNI.ast_traverse_flags_or_(swigCPtr, this, ast_traverse_flags.getCPtr(b), b), true);
  }

  public ast_traverse_flags and_(ast_traverse_flags b) throws result {
    return new ast_traverse_flags(csJNI.ast_traverse_flags_and_(swigCPtr, this, ast_traverse_flags.getCPtr(b), b), true);
  }

  public ast_traverse_flags not_() throws result {
    return new ast_traverse_flags(csJNI.ast_traverse_flags_not_(swigCPtr, this), true);
  }

  public static ast_traverse_flags getNONE() throws result {
    long cPtr = csJNI.ast_traverse_flags_NONE_get();
    return (cPtr == 0) ? null : new ast_traverse_flags(cPtr, false);
  }

  public static ast_traverse_flags getRIGHT_TO_LEFT() throws result {
    long cPtr = csJNI.ast_traverse_flags_RIGHT_TO_LEFT_get();
    return (cPtr == 0) ? null : new ast_traverse_flags(cPtr, false);
  }

  public static ast_traverse_flags getPOSTORDER() throws result {
    long cPtr = csJNI.ast_traverse_flags_POSTORDER_get();
    return (cPtr == 0) ? null : new ast_traverse_flags(cPtr, false);
  }

}
