/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.grammatech.cs;

public class basic_block_cfg_edge_set {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected basic_block_cfg_edge_set(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(basic_block_cfg_edge_set obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        csJNI.delete_basic_block_cfg_edge_set(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected static long getCPtrAndDisown(basic_block_cfg_edge_set obj) {
    if (obj != null) obj.swigCMemOwn= false;
    return getCPtr(obj);
  }

  public basic_block_cfg_edge_set(basic_block_cfg_edge_set other) throws result {
    this(csJNI.new_basic_block_cfg_edge_set(basic_block_cfg_edge_set.getCPtr(other), other), true);
  }

  public basic_block_cfg_edge_set_iterator begin() throws result {
    return new basic_block_cfg_edge_set_iterator(csJNI.basic_block_cfg_edge_set_begin(swigCPtr, this), true);
  }

  public basic_block_cfg_edge_set_iterator end() throws result {
    return new basic_block_cfg_edge_set_iterator(csJNI.basic_block_cfg_edge_set_end(swigCPtr, this), true);
  }

  public basic_block_cfg_edge_set_iterator cbegin() throws result {
    return new basic_block_cfg_edge_set_iterator(csJNI.basic_block_cfg_edge_set_cbegin(swigCPtr, this), true);
  }

  public basic_block_cfg_edge_set_iterator cend() throws result {
    return new basic_block_cfg_edge_set_iterator(csJNI.basic_block_cfg_edge_set_cend(swigCPtr, this), true);
  }

  public boolean empty() throws result {
    return csJNI.basic_block_cfg_edge_set_empty(swigCPtr, this);
  }

  public long size() throws result {
    return csJNI.basic_block_cfg_edge_set_size(swigCPtr, this);
  }

  public long count(basic_block_cfg_edge e) throws result {
    return csJNI.basic_block_cfg_edge_set_count(swigCPtr, this, basic_block_cfg_edge.getCPtr(e), e);
  }

  public basic_block_cfg_edge_set_iterator find(basic_block_cfg_edge e) throws result {
    return new basic_block_cfg_edge_set_iterator(csJNI.basic_block_cfg_edge_set_find(swigCPtr, this, basic_block_cfg_edge.getCPtr(e), e), true);
  }

  public int hashCode() {
    return csJNI.basic_block_cfg_edge_set_hashCode(swigCPtr, this);
  }

  public basic_block_cfg_edge_vector to_vector() throws result {
    return new basic_block_cfg_edge_vector(csJNI.basic_block_cfg_edge_set_to_vector(swigCPtr, this), true);
  }

  public String as_string() throws result {
    return csJNI.basic_block_cfg_edge_set_as_string(swigCPtr, this);
  }

  public String toString() {
    return csJNI.basic_block_cfg_edge_set_toString(swigCPtr, this);
  }

  public boolean equals(basic_block_cfg_edge_set other) throws result {
    return csJNI.basic_block_cfg_edge_set_equals(swigCPtr, this, basic_block_cfg_edge_set.getCPtr(other), other);
  }

}
