/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.grammatech.cs;

public class compunit_points {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected compunit_points(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(compunit_points obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        csJNI.delete_compunit_points(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected static long getCPtrAndDisown(compunit_points obj) {
    if (obj != null) obj.swigCMemOwn= false;
    return getCPtr(obj);
  }

  public compunit_points(compunit first, procedure_and_points_vector second) throws result {
    this(csJNI.new_compunit_points__SWIG_0(compunit.getCPtr(first), first, procedure_and_points_vector.getCPtr(second), second), true);
  }

  public compunit_points(compunit_points p) throws result {
    this(csJNI.new_compunit_points__SWIG_1(compunit_points.getCPtr(p), p), true);
  }

  public compunit get_first() throws result {
    return new compunit(csJNI.compunit_points_get_first(swigCPtr, this), false);
  }

  public procedure_and_points_vector get_second() throws result {
    return new procedure_and_points_vector(csJNI.compunit_points_get_second(swigCPtr, this), false);
  }

}
