/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.grammatech.cs;

public class predsucc_filter_pair {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected predsucc_filter_pair(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(predsucc_filter_pair obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        csJNI.delete_predsucc_filter_pair(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected static long getCPtrAndDisown(predsucc_filter_pair obj) {
    if (obj != null) obj.swigCMemOwn= false;
    return getCPtr(obj);
  }

  public predsucc_filter_pair(predsucc_filter_directive first, pdg_edge_kind second) throws result {
    this(csJNI.new_predsucc_filter_pair__SWIG_0(predsucc_filter_directive.getCPtr(first), first, pdg_edge_kind.getCPtr(second), second), true);
  }

  public predsucc_filter_pair(predsucc_filter_pair p) throws result {
    this(csJNI.new_predsucc_filter_pair__SWIG_1(predsucc_filter_pair.getCPtr(p), p), true);
  }

  public predsucc_filter_directive get_first() throws result {
    return new predsucc_filter_directive(csJNI.predsucc_filter_pair_get_first(swigCPtr, this), false);
  }

  public pdg_edge_kind get_second() throws result {
    return new pdg_edge_kind(csJNI.predsucc_filter_pair_get_second(swigCPtr, this), false);
  }

}
