/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.grammatech.cs;

public class sfile_metric_function {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected sfile_metric_function(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(sfile_metric_function obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        csJNI.delete_sfile_metric_function(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    csJNI.sfile_metric_function_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    csJNI.sfile_metric_function_change_ownership(this, swigCPtr, true);
  }

  protected static long getCPtrAndDisown(sfile_metric_function obj) {
    if (obj != null) obj.swigCMemOwn= false;
    return getCPtr(obj);
  }

  public sfile_metric_function() throws result {
    this(csJNI.new_sfile_metric_function__SWIG_0(), true);
    csJNI.sfile_metric_function_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

  public sfile_metric_function(sfile_metric_function arg0) throws result {
    this(csJNI.new_sfile_metric_function__SWIG_1(sfile_metric_function.getCPtr(arg0), arg0), true);
    csJNI.sfile_metric_function_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

  public double evaluate(sfile arg0) throws result {
    return csJNI.sfile_metric_function_evaluate(swigCPtr, this, sfile.getCPtr(arg0), arg0);
  }

}
