/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.grammatech.cs;

public class xr_kind implements Comparable<xr_kind> {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected xr_kind(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(xr_kind obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        csJNI.delete_xr_kind(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected static long getCPtrAndDisown(xr_kind obj) {
    if (obj != null) obj.swigCMemOwn= false;
    return getCPtr(obj);
  }

  public xr_kind(long _inner) throws result {
    this(csJNI.new_xr_kind(_inner), true);
  }

  public int compareTo(xr_kind other) {
    return csJNI.xr_kind_compareTo(swigCPtr, this, xr_kind.getCPtr(other), other);
  }

  public boolean equals(xr_kind other) throws result {
    return csJNI.xr_kind_equals(swigCPtr, this, xr_kind.getCPtr(other), other);
  }

  public int hashCode() {
    return csJNI.xr_kind_hashCode(swigCPtr, this);
  }

  public String as_string() throws result {
    return csJNI.xr_kind_as_string(swigCPtr, this);
  }

  public String toString() {
    return csJNI.xr_kind_toString(swigCPtr, this);
  }

  public String name() throws result {
    return csJNI.xr_kind_name(swigCPtr, this);
  }

  public static xr_kind getTYPE() throws result {
    long cPtr = csJNI.xr_kind_TYPE_get();
    return (cPtr == 0) ? null : new xr_kind(cPtr, false);
  }

  public static xr_kind getNAMESPACE() throws result {
    long cPtr = csJNI.xr_kind_NAMESPACE_get();
    return (cPtr == 0) ? null : new xr_kind(cPtr, false);
  }

  public static xr_kind getFUNC() throws result {
    long cPtr = csJNI.xr_kind_FUNC_get();
    return (cPtr == 0) ? null : new xr_kind(cPtr, false);
  }

  public static xr_kind getVAR() throws result {
    long cPtr = csJNI.xr_kind_VAR_get();
    return (cPtr == 0) ? null : new xr_kind(cPtr, false);
  }

  public static xr_kind getMACRO() throws result {
    long cPtr = csJNI.xr_kind_MACRO_get();
    return (cPtr == 0) ? null : new xr_kind(cPtr, false);
  }

  public static xr_kind getFIELD() throws result {
    long cPtr = csJNI.xr_kind_FIELD_get();
    return (cPtr == 0) ? null : new xr_kind(cPtr, false);
  }

  public static xr_kind getENUM() throws result {
    long cPtr = csJNI.xr_kind_ENUM_get();
    return (cPtr == 0) ? null : new xr_kind(cPtr, false);
  }

  public static xr_kind getSTRINGLIT() throws result {
    long cPtr = csJNI.xr_kind_STRINGLIT_get();
    return (cPtr == 0) ? null : new xr_kind(cPtr, false);
  }

  public static xr_kind getTLT() throws result {
    long cPtr = csJNI.xr_kind_TLT_get();
    return (cPtr == 0) ? null : new xr_kind(cPtr, false);
  }

  public static xr_kind getTLV() throws result {
    long cPtr = csJNI.xr_kind_TLV_get();
    return (cPtr == 0) ? null : new xr_kind(cPtr, false);
  }

  public static xr_kind getLABEL() throws result {
    long cPtr = csJNI.xr_kind_LABEL_get();
    return (cPtr == 0) ? null : new xr_kind(cPtr, false);
  }

  public static xr_kind getFILE() throws result {
    long cPtr = csJNI.xr_kind_FILE_get();
    return (cPtr == 0) ? null : new xr_kind(cPtr, false);
  }

  public static xr_kind getBUILTIN() throws result {
    long cPtr = csJNI.xr_kind_BUILTIN_get();
    return (cPtr == 0) ? null : new xr_kind(cPtr, false);
  }

}
