# This file is part of CPAchecker,
# a tool for configurable software verification:
# https://cpachecker.sosy-lab.org
#
# SPDX-FileCopyrightText: 2007-2026 Dirk Beyer <https://www.sosy-lab.org>
#
# SPDX-License-Identifier: Apache-2.0

# ------------------------------------------------------------------
# SMGv2 w symbolic execution with overflow detection for cex check
# ------------------------------------------------------------------

# TODO: do we need/want witness validation using this config?
# #include ../includes/witness-validation.properties

specification = ../specification/overflow.spc

#include ../includes/smg/smgSymbolicExecution-overflow.properties

# Secondary analysis should not produce output.
output.disable = true
