/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

#line 134 "/usr/include/bits/types.h"
typedef unsigned long __dev_t;
#line 135 "/usr/include/bits/types.h"
typedef unsigned int __uid_t;
#line 136 "/usr/include/bits/types.h"
typedef unsigned int __gid_t;
#line 137 "/usr/include/bits/types.h"
typedef unsigned long __ino_t;
#line 139 "/usr/include/bits/types.h"
typedef unsigned int __mode_t;
#line 140 "/usr/include/bits/types.h"
typedef unsigned long __nlink_t;
#line 141 "/usr/include/bits/types.h"
typedef long __off_t;
#line 149 "/usr/include/bits/types.h"
typedef long __time_t;
#line 164 "/usr/include/bits/types.h"
typedef long __blksize_t;
#line 169 "/usr/include/bits/types.h"
typedef long __blkcnt_t;
#line 180 "/usr/include/bits/types.h"
typedef long __ssize_t;
#line 120 "/usr/include/time.h"
struct timespec {
   __time_t tv_sec ;
   long tv_nsec ;
};
#line 84 "/usr/include/sys/stat.h"
typedef __uid_t uid_t;
#line 43 "/usr/include/bits/stat.h"
struct stat {
   __dev_t st_dev ;
   __ino_t st_ino ;
   __nlink_t st_nlink ;
   __mode_t st_mode ;
   __uid_t st_uid ;
   __gid_t st_gid ;
   int __pad0 ;
   __dev_t st_rdev ;
   __off_t st_size ;
   __blksize_t st_blksize ;
   __blkcnt_t st_blocks ;
   struct timespec st_atim ;
   struct timespec st_mtim ;
   struct timespec st_ctim ;
   long __unused[3] ;
};
#line 211 "/usr/lib/gcc/x86_64-linux-gnu/4.4.3/include/stddef.h"
typedef unsigned long size_t;
#line 110 "/usr/include/sys/types.h"
typedef __ssize_t ssize_t;
#line 29 "/usr/include/bits/sigset.h"
struct __anonstruct___sigset_t_5 {
   unsigned long __val[1024UL / (8UL * sizeof(unsigned long ))] ;
};
#line 29 "/usr/include/bits/sigset.h"
typedef struct __anonstruct___sigset_t_5 __sigset_t;
#line 38 "/usr/include/sys/select.h"
typedef __sigset_t sigset_t;
#line 263 "/usr/include/sys/stat.h"
extern  __attribute__((__nothrow__)) int lstat(char const   * __restrict  __file ,
                                               struct stat * __restrict  __buf )  __attribute__((__nonnull__(1,2))) ;
#line 43 "/usr/include/bits/errno.h"
extern  __attribute__((__nothrow__)) int *__errno_location(void)  __attribute__((__const__)) ;
#line 473 "/usr/include/stdlib.h"
extern  __attribute__((__nothrow__)) void *calloc(size_t __nmemb , size_t __size )  __attribute__((__malloc__)) ;
#line 488
extern  __attribute__((__nothrow__)) void free(void *__ptr ) ;
#line 127 "/usr/include/string.h"
extern  __attribute__((__nothrow__)) char *strcpy(char * __restrict  __dest , char const   * __restrict  __src )  __attribute__((__nonnull__(1,2))) ;
#line 130
extern  __attribute__((__nothrow__)) char *strncpy(char * __restrict  __dest , char const   * __restrict  __src ,
                                                   size_t __n )  __attribute__((__nonnull__(1,2))) ;
#line 135
extern  __attribute__((__nothrow__)) char *strcat(char * __restrict  __dest , char const   * __restrict  __src )  __attribute__((__nonnull__(1,2))) ;
#line 260
extern  __attribute__((__nothrow__)) char *strrchr(char const   *__s , int __c )  __attribute__((__pure__,
__nonnull__(1))) ;
#line 397
extern  __attribute__((__nothrow__)) size_t strlen(char const   *__s )  __attribute__((__pure__,
__nonnull__(1))) ;
#line 350 "/usr/include/unistd.h"
extern int close(int __fd ) ;
#line 493
extern  __attribute__((__nothrow__)) int chdir(char const   *__path )  __attribute__((__nonnull__(1))) ;
#line 497
extern  __attribute__((__nothrow__)) int fchdir(int __fd ) ;
#line 507
extern  __attribute__((__nothrow__)) char *getcwd(char *__buf , size_t __size ) ;
#line 695
extern  __attribute__((__nothrow__)) __uid_t geteuid(void) ;
#line 727
extern  __attribute__((__nothrow__)) int seteuid(__uid_t __uid ) ;
#line 825
extern  __attribute__((__nothrow__)) ssize_t readlink(char const   * __restrict  __path ,
                                                      char * __restrict  __buf , size_t __len )  __attribute__((__nonnull__(1,2))) ;
#line 73 "/usr/include/fcntl.h"
extern int open(char const   *__file , int __oflag  , ...)  __attribute__((__nonnull__(1))) ;
#line 222 "/usr/include/signal.h"
extern  __attribute__((__nothrow__)) int sigemptyset(sigset_t *__set )  __attribute__((__nonnull__(1))) ;
#line 228
extern  __attribute__((__nothrow__)) int sigaddset(sigset_t *__set , int __signo )  __attribute__((__nonnull__(1))) ;
#line 255
extern  __attribute__((__nothrow__)) int sigprocmask(int __how , sigset_t const   * __restrict  __set ,
                                                     sigset_t * __restrict  __oset ) ;
#line 339 "/usr/include/stdio.h"
extern int printf(char const   * __restrict  __format  , ...) ;
#line 102 "realpath-bad.c"
char *fb_realpath(char const   *path , char *resolved ) ;
#line 111 "realpath-bad.c"
static sigset_t saved_sigmask  ;
#line 112 "realpath-bad.c"
static sigset_t block_sigmask  ;
#line 113 "realpath-bad.c"
static int delaying  ;
#line 114 "realpath-bad.c"
static int init_done  ;
#line 118 "realpath-bad.c"
static void init_mask(void) 
{ int sig ;

  {
  {
#line 122
  init_done = 1;
#line 123
  sigemptyset(& block_sigmask);
#line 124
  sig = 1;
  }
  {
#line 124
  while (1) {
    while_continue: /* CIL Label */ ;
#line 124
    if (sig < 65) {

    } else {
#line 124
      goto while_break;
    }
    {
#line 125
    sigaddset(& block_sigmask, sig);
#line 124
    sig = sig + 1;
    }
  }
  while_break: /* CIL Label */ ;
  }
#line 126
  return;
}
}
#line 130 "realpath-bad.c"
int enable_signaling(void) 
{ int tmp ;
  sigset_t const   * __restrict  __cil_tmp2 ;
  sigset_t *__cil_tmp3 ;
  sigset_t * __restrict  __cil_tmp4 ;

  {
#line 132
  if (delaying != 0) {
    {
#line 133
    delaying = 0;
#line 134
    __cil_tmp2 = (sigset_t const   * __restrict  )(& saved_sigmask);
#line 134
    __cil_tmp3 = (sigset_t *)0;
#line 134
    __cil_tmp4 = (sigset_t * __restrict  )__cil_tmp3;
#line 134
    tmp = sigprocmask(2, __cil_tmp2, __cil_tmp4);
    }
#line 134
    if (tmp < 0) {
#line 136
      return (-1);
    } else {

    }
  } else {

  }
#line 139
  return (0);
}
}
#line 144 "realpath-bad.c"
int delay_signaling(void) 
{ int tmp ;
  sigset_t const   * __restrict  __cil_tmp2 ;
  sigset_t * __restrict  __cil_tmp3 ;

  {
#line 146
  if (init_done == 0) {
    {
#line 147
    init_mask();
    }
  } else {

  }
#line 148
  if (delaying == 0) {
    {
#line 149
    delaying = 1;
#line 150
    __cil_tmp2 = (sigset_t const   * __restrict  )(& block_sigmask);
#line 150
    __cil_tmp3 = (sigset_t * __restrict  )(& saved_sigmask);
#line 150
    tmp = sigprocmask(0, __cil_tmp2, __cil_tmp3);
    }
#line 150
    if (tmp < 0) {
#line 152
      return (-1);
    } else {

    }
  } else {

  }
#line 155
  return (0);
}
}
#line 159 "realpath-bad.c"
char *wu_realpath(char const   *path , char *resolved_path , char *chroot_path ) 
{ char *ptr ;
  char q[46] ;
  size_t tmp ;
  size_t tmp___0 ;
  size_t tmp___1 ;
  size_t tmp___2 ;
  size_t tmp___3 ;
  size_t tmp___4 ;
  size_t tmp___5 ;
  unsigned long __cil_tmp13 ;
  unsigned long __cil_tmp14 ;
  char *__cil_tmp15 ;
  unsigned long __cil_tmp16 ;
  unsigned long __cil_tmp17 ;
  char *__cil_tmp18 ;
  char const   *__cil_tmp19 ;
  char const   * __restrict  __cil_tmp20 ;
  char const   * __restrict  __cil_tmp21 ;
  unsigned long __cil_tmp22 ;
  unsigned long __cil_tmp23 ;
  char __cil_tmp24 ;
  int __cil_tmp25 ;
  void *__cil_tmp26 ;
  unsigned long __cil_tmp27 ;
  unsigned long __cil_tmp28 ;
  char * __restrict  __cil_tmp29 ;
  unsigned long __cil_tmp30 ;
  unsigned long __cil_tmp31 ;
  char *__cil_tmp32 ;
  char const   * __restrict  __cil_tmp33 ;
  char * __restrict  __cil_tmp34 ;
  char const   * __restrict  __cil_tmp35 ;
  unsigned long __cil_tmp36 ;
  unsigned long __cil_tmp37 ;
  char __cil_tmp38 ;
  int __cil_tmp39 ;
  char const   *__cil_tmp40 ;
  unsigned long __cil_tmp41 ;
  unsigned long __cil_tmp42 ;
  char *__cil_tmp43 ;
  char const   *__cil_tmp44 ;
  size_t __cil_tmp45 ;
  char * __restrict  __cil_tmp46 ;
  unsigned long __cil_tmp47 ;
  unsigned long __cil_tmp48 ;
  char *__cil_tmp49 ;
  char const   * __restrict  __cil_tmp50 ;
  void *__cil_tmp51 ;
  unsigned long __cil_tmp52 ;
  unsigned long __cil_tmp53 ;
  char __cil_tmp54 ;
  int __cil_tmp55 ;
  unsigned long __cil_tmp56 ;
  unsigned long __cil_tmp57 ;
  char __cil_tmp58 ;
  int __cil_tmp59 ;
  unsigned long __cil_tmp60 ;
  unsigned long __cil_tmp61 ;
  char __cil_tmp62 ;
  int __cil_tmp63 ;
  char const   *__cil_tmp64 ;
  unsigned long __cil_tmp65 ;
  unsigned long __cil_tmp66 ;
  char *__cil_tmp67 ;
  char const   *__cil_tmp68 ;
  size_t __cil_tmp69 ;
  char * __restrict  __cil_tmp70 ;
  unsigned long __cil_tmp71 ;
  unsigned long __cil_tmp72 ;
  char *__cil_tmp73 ;
  char const   * __restrict  __cil_tmp74 ;
  void *__cil_tmp75 ;
  char const   *__cil_tmp76 ;
  unsigned long __cil_tmp77 ;
  unsigned long __cil_tmp78 ;
  char *__cil_tmp79 ;
  char const   *__cil_tmp80 ;
  size_t __cil_tmp81 ;
  size_t __cil_tmp82 ;
  char * __restrict  __cil_tmp83 ;
  unsigned long __cil_tmp84 ;
  unsigned long __cil_tmp85 ;
  char *__cil_tmp86 ;
  char const   * __restrict  __cil_tmp87 ;
  void *__cil_tmp88 ;

  {
  {
#line 164
  __cil_tmp13 = 0 * 1UL;
#line 164
  __cil_tmp14 = (unsigned long )(q) + __cil_tmp13;
#line 164
  __cil_tmp15 = (char *)__cil_tmp14;
#line 164
  fb_realpath(path, __cil_tmp15);
#line 166
  __cil_tmp16 = 0 * 1UL;
#line 166
  __cil_tmp17 = (unsigned long )(q) + __cil_tmp16;
#line 166
  __cil_tmp18 = (char *)__cil_tmp17;
#line 166
  __cil_tmp19 = (char const   *)__cil_tmp18;
#line 166
  tmp = strlen(__cil_tmp19);
#line 166
  __cil_tmp20 = (char const   * __restrict  )"strlen(q) = %d\n";
#line 166
  printf(__cil_tmp20, tmp);
#line 167
  __cil_tmp21 = (char const   * __restrict  )"q[MAXPATHLEN - 1] = %c\n";
#line 167
  __cil_tmp22 = 45 * 1UL;
#line 167
  __cil_tmp23 = (unsigned long )(q) + __cil_tmp22;
#line 167
  __cil_tmp24 = *((char *)__cil_tmp23);
#line 167
  __cil_tmp25 = (int )__cil_tmp24;
#line 167
  printf(__cil_tmp21, __cil_tmp25);
  }
  {
#line 169
  __cil_tmp26 = (void *)0;
#line 169
  __cil_tmp27 = (unsigned long )__cil_tmp26;
#line 169
  __cil_tmp28 = (unsigned long )chroot_path;
#line 169
  if (__cil_tmp28 == __cil_tmp27) {
    {
#line 170
    __cil_tmp29 = (char * __restrict  )resolved_path;
#line 170
    __cil_tmp30 = 0 * 1UL;
#line 170
    __cil_tmp31 = (unsigned long )(q) + __cil_tmp30;
#line 170
    __cil_tmp32 = (char *)__cil_tmp31;
#line 170
    __cil_tmp33 = (char const   * __restrict  )__cil_tmp32;
#line 170
    strcpy(__cil_tmp29, __cil_tmp33);
    }
  } else {
    {
#line 172
    __cil_tmp34 = (char * __restrict  )resolved_path;
#line 172
    __cil_tmp35 = (char const   * __restrict  )chroot_path;
#line 172
    strcpy(__cil_tmp34, __cil_tmp35);
    }
    {
#line 173
    __cil_tmp36 = 0 * 1UL;
#line 173
    __cil_tmp37 = (unsigned long )(q) + __cil_tmp36;
#line 173
    __cil_tmp38 = *((char *)__cil_tmp37);
#line 173
    __cil_tmp39 = (int )__cil_tmp38;
#line 173
    if (__cil_tmp39 != 47) {
      {
#line 174
      __cil_tmp40 = (char const   *)resolved_path;
#line 174
      tmp___0 = strlen(__cil_tmp40);
#line 174
      __cil_tmp41 = 0 * 1UL;
#line 174
      __cil_tmp42 = (unsigned long )(q) + __cil_tmp41;
#line 174
      __cil_tmp43 = (char *)__cil_tmp42;
#line 174
      __cil_tmp44 = (char const   *)__cil_tmp43;
#line 174
      tmp___1 = strlen(__cil_tmp44);
      }
      {
#line 174
      __cil_tmp45 = tmp___0 + tmp___1;
#line 174
      if (__cil_tmp45 < 46UL) {
        {
#line 175
        __cil_tmp46 = (char * __restrict  )resolved_path;
#line 175
        __cil_tmp47 = 0 * 1UL;
#line 175
        __cil_tmp48 = (unsigned long )(q) + __cil_tmp47;
#line 175
        __cil_tmp49 = (char *)__cil_tmp48;
#line 175
        __cil_tmp50 = (char const   * __restrict  )__cil_tmp49;
#line 175
        strcat(__cil_tmp46, __cil_tmp50);
        }
      } else {
        {
#line 177
        __cil_tmp51 = (void *)0;
#line 177
        return ((char *)__cil_tmp51);
        }
      }
      }
    } else {
      {
#line 179
      __cil_tmp52 = 1 * 1UL;
#line 179
      __cil_tmp53 = (unsigned long )(q) + __cil_tmp52;
#line 179
      __cil_tmp54 = *((char *)__cil_tmp53);
#line 179
      __cil_tmp55 = (int )__cil_tmp54;
#line 179
      if (__cil_tmp55 != 0) {
#line 180
        __cil_tmp56 = 0 * 1UL;
#line 180
        __cil_tmp57 = (unsigned long )(q) + __cil_tmp56;
#line 180
        ptr = (char *)__cil_tmp57;
        {
#line 180
        while (1) {
          while_continue: /* CIL Label */ ;
          {
#line 180
          __cil_tmp58 = *ptr;
#line 180
          __cil_tmp59 = (int )__cil_tmp58;
#line 180
          if (__cil_tmp59 != 0) {

          } else {
#line 180
            goto while_break;
          }
          }
#line 180
          ptr = ptr + 1;
        }
        while_break: /* CIL Label */ ;
        }
        {
#line 181
        __cil_tmp60 = (unsigned long )resolved_path;
#line 181
        __cil_tmp61 = (unsigned long )ptr;
#line 181
        if (__cil_tmp61 == __cil_tmp60) {
#line 181
          goto _L;
        } else {
#line 181
          ptr = ptr - 1;
          {
#line 181
          __cil_tmp62 = *ptr;
#line 181
          __cil_tmp63 = (int )__cil_tmp62;
#line 181
          if (__cil_tmp63 != 47) {
            _L: /* CIL Label */ 
            {
#line 182
            __cil_tmp64 = (char const   *)resolved_path;
#line 182
            tmp___2 = strlen(__cil_tmp64);
#line 182
            __cil_tmp65 = 0 * 1UL;
#line 182
            __cil_tmp66 = (unsigned long )(q) + __cil_tmp65;
#line 182
            __cil_tmp67 = (char *)__cil_tmp66;
#line 182
            __cil_tmp68 = (char const   *)__cil_tmp67;
#line 182
            tmp___3 = strlen(__cil_tmp68);
            }
            {
#line 182
            __cil_tmp69 = tmp___2 + tmp___3;
#line 182
            if (__cil_tmp69 < 46UL) {
              {
#line 183
              __cil_tmp70 = (char * __restrict  )resolved_path;
#line 183
              __cil_tmp71 = 0 * 1UL;
#line 183
              __cil_tmp72 = (unsigned long )(q) + __cil_tmp71;
#line 183
              __cil_tmp73 = (char *)__cil_tmp72;
#line 183
              __cil_tmp74 = (char const   * __restrict  )__cil_tmp73;
#line 183
              strcat(__cil_tmp70, __cil_tmp74);
              }
            } else {
              {
#line 185
              __cil_tmp75 = (void *)0;
#line 185
              return ((char *)__cil_tmp75);
              }
            }
            }
          } else {
            {
#line 188
            __cil_tmp76 = (char const   *)resolved_path;
#line 188
            tmp___4 = strlen(__cil_tmp76);
#line 188
            __cil_tmp77 = 0 * 1UL;
#line 188
            __cil_tmp78 = (unsigned long )(q) + __cil_tmp77;
#line 188
            __cil_tmp79 = (char *)__cil_tmp78;
#line 188
            __cil_tmp80 = (char const   *)__cil_tmp79;
#line 188
            tmp___5 = strlen(__cil_tmp80);
            }
            {
#line 188
            __cil_tmp81 = tmp___4 + tmp___5;
#line 188
            __cil_tmp82 = __cil_tmp81 - 1UL;
#line 188
            if (__cil_tmp82 < 46UL) {
              {
#line 189
              __cil_tmp83 = (char * __restrict  )resolved_path;
#line 189
              __cil_tmp84 = 1 * 1UL;
#line 189
              __cil_tmp85 = (unsigned long )(q) + __cil_tmp84;
#line 189
              __cil_tmp86 = (char *)__cil_tmp85;
#line 189
              __cil_tmp87 = (char const   * __restrict  )__cil_tmp86;
#line 189
              strcat(__cil_tmp83, __cil_tmp87);
              }
            } else {
              {
#line 191
              __cil_tmp88 = (void *)0;
#line 191
              return ((char *)__cil_tmp88);
              }
            }
            }
          }
          }
        }
        }
      } else {

      }
      }
    }
    }
  }
  }
#line 196
  return ((char *)resolved_path);
}
}
#line 210 "realpath-bad.c"
char *fb_realpath(char const   *path , char *resolved ) 
{ struct stat sb ;
  int fd ;
  int rootd ;
  int serrno ;
  char *p ;
  char *q ;
  char wbuf[46] ;
  int resultcode ;
  int *tmp ;
  uid_t userid ;
  __uid_t tmp___0 ;
  int *tmp___1 ;
  int *tmp___2 ;
  uid_t userid___0 ;
  __uid_t tmp___3 ;
  int *tmp___4 ;
  int *tmp___5 ;
  int *tmp___6 ;
  int *tmp___7 ;
  uid_t userid___1 ;
  __uid_t tmp___8 ;
  int *tmp___9 ;
  int *tmp___10 ;
  int symlinks ;
  int n ;
  int *tmp___11 ;
  int *tmp___12 ;
  size_t len ;
  size_t tmp___13 ;
  char *tmp___14 ;
  void *tmp___15 ;
  int *tmp___16 ;
  ssize_t tmp___17 ;
  uid_t userid___2 ;
  __uid_t tmp___18 ;
  int *tmp___19 ;
  ssize_t tmp___20 ;
  int *tmp___21 ;
  int *tmp___22 ;
  uid_t userid___3 ;
  __uid_t tmp___23 ;
  int *tmp___24 ;
  int *tmp___25 ;
  int *tmp___26 ;
  char *tmp___28 ;
  uid_t userid___4 ;
  __uid_t tmp___29 ;
  int *tmp___30 ;
  char *tmp___32 ;
  int *tmp___33 ;
  size_t tmp___34 ;
  size_t tmp___35 ;
  size_t tmp___36 ;
  size_t tmp___37 ;
  int *tmp___38 ;
  size_t tmp___39 ;
  size_t tmp___40 ;
  size_t tmp___41 ;
  size_t tmp___42 ;
  size_t tmp___43 ;
  size_t tmp___44 ;
  int *tmp___45 ;
  uid_t userid___5 ;
  __uid_t tmp___46 ;
  int *tmp___47 ;
  int *tmp___48 ;
  int *tmp___49 ;
  int *tmp___50 ;
  uid_t userid___6 ;
  __uid_t tmp___51 ;
  int *tmp___52 ;
  int *tmp___53 ;
  int __cil_tmp77 ;
  __uid_t __cil_tmp78 ;
  char * __restrict  __cil_tmp79 ;
  char const   * __restrict  __cil_tmp80 ;
  void *__cil_tmp81 ;
  char * __restrict  __cil_tmp82 ;
  char const   * __restrict  __cil_tmp83 ;
  size_t __cil_tmp84 ;
  char *__cil_tmp85 ;
  char const   *__cil_tmp86 ;
  char const   * __restrict  __cil_tmp87 ;
  void *__cil_tmp88 ;
  unsigned long __cil_tmp89 ;
  unsigned long __cil_tmp90 ;
  unsigned long __cil_tmp91 ;
  unsigned long __cil_tmp92 ;
  unsigned long __cil_tmp93 ;
  unsigned long __cil_tmp94 ;
  char __cil_tmp95 ;
  int __cil_tmp96 ;
  char *__cil_tmp97 ;
  char const   * __restrict  __cil_tmp98 ;
  char const   *__cil_tmp99 ;
  int __cil_tmp100 ;
  __uid_t __cil_tmp101 ;
  char const   *__cil_tmp102 ;
  char const   * __restrict  __cil_tmp103 ;
  char __cil_tmp104 ;
  int __cil_tmp105 ;
  char const   * __restrict  __cil_tmp106 ;
  char const   * __restrict  __cil_tmp107 ;
  struct stat * __restrict  __cil_tmp108 ;
  char const   * __restrict  __cil_tmp109 ;
  char const   * __restrict  __cil_tmp110 ;
  int __cil_tmp111 ;
  int __cil_tmp112 ;
  __uid_t __cil_tmp113 ;
  char const   * __restrict  __cil_tmp114 ;
  struct stat * __restrict  __cil_tmp115 ;
  char const   * __restrict  __cil_tmp116 ;
  unsigned long __cil_tmp117 ;
  __mode_t __cil_tmp118 ;
  unsigned long __cil_tmp119 ;
  __mode_t __cil_tmp120 ;
  unsigned int __cil_tmp121 ;
  char const   * __restrict  __cil_tmp122 ;
  unsigned long __cil_tmp123 ;
  __mode_t __cil_tmp124 ;
  unsigned int __cil_tmp125 ;
  char const   * __restrict  __cil_tmp126 ;
  unsigned long __cil_tmp127 ;
  __mode_t __cil_tmp128 ;
  unsigned int __cil_tmp129 ;
  char const   * __restrict  __cil_tmp130 ;
  unsigned long __cil_tmp131 ;
  __mode_t __cil_tmp132 ;
  unsigned int __cil_tmp133 ;
  char const   * __restrict  __cil_tmp134 ;
  unsigned long __cil_tmp135 ;
  __mode_t __cil_tmp136 ;
  unsigned int __cil_tmp137 ;
  char const   * __restrict  __cil_tmp138 ;
  unsigned long __cil_tmp139 ;
  __mode_t __cil_tmp140 ;
  unsigned int __cil_tmp141 ;
  char const   * __restrict  __cil_tmp142 ;
  unsigned long __cil_tmp143 ;
  __mode_t __cil_tmp144 ;
  unsigned int __cil_tmp145 ;
  char const   * __restrict  __cil_tmp146 ;
  unsigned long __cil_tmp147 ;
  __mode_t __cil_tmp148 ;
  unsigned int __cil_tmp149 ;
  char const   *__cil_tmp150 ;
  size_t __cil_tmp151 ;
  char *__cil_tmp152 ;
  unsigned long __cil_tmp153 ;
  unsigned long __cil_tmp154 ;
  char * __restrict  __cil_tmp155 ;
  char const   * __restrict  __cil_tmp156 ;
  char const   * __restrict  __cil_tmp157 ;
  char * __restrict  __cil_tmp158 ;
  size_t __cil_tmp159 ;
  int __cil_tmp160 ;
  __uid_t __cil_tmp161 ;
  char const   * __restrict  __cil_tmp162 ;
  char * __restrict  __cil_tmp163 ;
  size_t __cil_tmp164 ;
  void *__cil_tmp165 ;
  void *__cil_tmp166 ;
  char *__cil_tmp167 ;
  unsigned long __cil_tmp168 ;
  __mode_t __cil_tmp169 ;
  unsigned int __cil_tmp170 ;
  char const   * __restrict  __cil_tmp171 ;
  char const   *__cil_tmp172 ;
  char const   * __restrict  __cil_tmp173 ;
  int __cil_tmp174 ;
  __uid_t __cil_tmp175 ;
  char const   *__cil_tmp176 ;
  unsigned long __cil_tmp177 ;
  unsigned long __cil_tmp178 ;
  char *__cil_tmp179 ;
  char * __restrict  __cil_tmp180 ;
  char const   * __restrict  __cil_tmp181 ;
  char const   * __restrict  __cil_tmp182 ;
  unsigned long __cil_tmp183 ;
  unsigned long __cil_tmp184 ;
  char *__cil_tmp185 ;
  size_t __cil_tmp186 ;
  void *__cil_tmp187 ;
  unsigned long __cil_tmp188 ;
  unsigned long __cil_tmp189 ;
  char const   * __restrict  __cil_tmp190 ;
  int __cil_tmp191 ;
  __uid_t __cil_tmp192 ;
  size_t __cil_tmp193 ;
  void *__cil_tmp194 ;
  unsigned long __cil_tmp195 ;
  unsigned long __cil_tmp196 ;
  char const   * __restrict  __cil_tmp197 ;
  char *__cil_tmp198 ;
  char __cil_tmp199 ;
  int __cil_tmp200 ;
  char *__cil_tmp201 ;
  char __cil_tmp202 ;
  int __cil_tmp203 ;
  char const   *__cil_tmp204 ;
  char const   * __restrict  __cil_tmp205 ;
  unsigned long __cil_tmp206 ;
  unsigned long __cil_tmp207 ;
  char *__cil_tmp208 ;
  char const   *__cil_tmp209 ;
  char const   * __restrict  __cil_tmp210 ;
  unsigned long __cil_tmp211 ;
  unsigned long __cil_tmp212 ;
  char *__cil_tmp213 ;
  char const   * __restrict  __cil_tmp214 ;
  char const   *__cil_tmp215 ;
  unsigned long __cil_tmp216 ;
  unsigned long __cil_tmp217 ;
  char *__cil_tmp218 ;
  char const   *__cil_tmp219 ;
  char const   * __restrict  __cil_tmp220 ;
  size_t __cil_tmp221 ;
  size_t __cil_tmp222 ;
  size_t __cil_tmp223 ;
  size_t __cil_tmp224 ;
  unsigned long __cil_tmp225 ;
  unsigned long __cil_tmp226 ;
  char const   *__cil_tmp227 ;
  unsigned long __cil_tmp228 ;
  unsigned long __cil_tmp229 ;
  char *__cil_tmp230 ;
  char const   *__cil_tmp231 ;
  size_t __cil_tmp232 ;
  size_t __cil_tmp233 ;
  size_t __cil_tmp234 ;
  size_t __cil_tmp235 ;
  char const   * __restrict  __cil_tmp236 ;
  char * __restrict  __cil_tmp237 ;
  char const   * __restrict  __cil_tmp238 ;
  char const   *__cil_tmp239 ;
  char const   * __restrict  __cil_tmp240 ;
  unsigned long __cil_tmp241 ;
  unsigned long __cil_tmp242 ;
  char *__cil_tmp243 ;
  char const   *__cil_tmp244 ;
  char const   * __restrict  __cil_tmp245 ;
  unsigned long __cil_tmp246 ;
  unsigned long __cil_tmp247 ;
  char *__cil_tmp248 ;
  char * __restrict  __cil_tmp249 ;
  unsigned long __cil_tmp250 ;
  unsigned long __cil_tmp251 ;
  char *__cil_tmp252 ;
  char const   * __restrict  __cil_tmp253 ;
  char const   *__cil_tmp254 ;
  char const   * __restrict  __cil_tmp255 ;
  char const   *__cil_tmp256 ;
  size_t __cil_tmp257 ;
  char const   * __restrict  __cil_tmp258 ;
  int __cil_tmp259 ;
  __uid_t __cil_tmp260 ;
  int __cil_tmp261 ;
  __uid_t __cil_tmp262 ;
  void *__cil_tmp263 ;

  {
  {
#line 225
  tmp = __errno_location();
#line 225
  *tmp = 0;
#line 233
  fd = open(".", 0);
#line 235
  tmp___1 = __errno_location();
  }
  {
#line 235
  __cil_tmp77 = *tmp___1;
#line 235
  if (13 == __cil_tmp77) {
    {
#line 236
    tmp___0 = geteuid();
#line 236
    userid = tmp___0;
#line 237
    delay_signaling();
#line 238
    __cil_tmp78 = (__uid_t )0;
#line 238
    seteuid(__cil_tmp78);
#line 246
    fd = open(".", 0);
#line 248
    seteuid(userid);
#line 249
    enable_signaling();
    }
  } else {

  }
  }
#line 254
  if (fd < 0) {
    {
#line 257
    __cil_tmp79 = (char * __restrict  )resolved;
#line 257
    __cil_tmp80 = (char const   * __restrict  )".";
#line 257
    strcpy(__cil_tmp79, __cil_tmp80);
    }
    {
#line 258
    __cil_tmp81 = (void *)0;
#line 258
    return ((char *)__cil_tmp81);
    }
  } else {

  }
  {
#line 270
  __cil_tmp82 = (char * __restrict  )resolved;
#line 270
  __cil_tmp83 = (char const   * __restrict  )path;
#line 270
  __cil_tmp84 = (size_t )45;
#line 270
  strncpy(__cil_tmp82, __cil_tmp83, __cil_tmp84);
#line 271
  __cil_tmp85 = resolved + 45;
#line 271
  *__cil_tmp85 = (char )'\000';
  }
  loop: 
  {
#line 274
  __cil_tmp86 = (char const   *)resolved;
#line 274
  q = strrchr(__cil_tmp86, '/');
#line 276
  __cil_tmp87 = (char const   * __restrict  )"q inside LOOP = %s\n";
#line 276
  printf(__cil_tmp87, q);
  }
  {
#line 278
  __cil_tmp88 = (void *)0;
#line 278
  __cil_tmp89 = (unsigned long )__cil_tmp88;
#line 278
  __cil_tmp90 = (unsigned long )q;
#line 278
  if (__cil_tmp90 != __cil_tmp89) {
#line 279
    p = q + 1;
    {
#line 281
    __cil_tmp91 = (unsigned long )resolved;
#line 281
    __cil_tmp92 = (unsigned long )q;
#line 281
    if (__cil_tmp92 == __cil_tmp91) {
#line 282
      q = (char *)"/";
    } else {
      {
#line 284
      while (1) {
        while_continue: /* CIL Label */ ;
#line 285
        q = q - 1;
        {
#line 284
        __cil_tmp93 = (unsigned long )resolved;
#line 284
        __cil_tmp94 = (unsigned long )q;
#line 284
        if (__cil_tmp94 > __cil_tmp93) {
          {
#line 284
          __cil_tmp95 = *q;
#line 284
          __cil_tmp96 = (int )__cil_tmp95;
#line 284
          if (__cil_tmp96 == 47) {

          } else {
#line 284
            goto while_break;
          }
          }
        } else {
#line 284
          goto while_break;
        }
        }
      }
      while_break: /* CIL Label */ ;
      }
#line 287
      __cil_tmp97 = q + 1;
#line 287
      *__cil_tmp97 = (char )'\000';
#line 288
      q = resolved;
    }
    }
    {
#line 290
    tmp___2 = __errno_location();
#line 290
    *tmp___2 = 0;
#line 292
    __cil_tmp98 = (char const   * __restrict  )"trying to chdir(%s)\n";
#line 292
    printf(__cil_tmp98, q);
#line 293
    __cil_tmp99 = (char const   *)q;
#line 293
    resultcode = chdir(__cil_tmp99);
#line 294
    tmp___5 = __errno_location();
    }
    {
#line 294
    __cil_tmp100 = *tmp___5;
#line 294
    if (13 == __cil_tmp100) {
      {
#line 295
      tmp___3 = geteuid();
#line 295
      userid___0 = tmp___3;
#line 296
      delay_signaling();
#line 297
      __cil_tmp101 = (__uid_t )0;
#line 297
      seteuid(__cil_tmp101);
#line 298
      tmp___4 = __errno_location();
#line 298
      *tmp___4 = 0;
#line 299
      __cil_tmp102 = (char const   *)q;
#line 299
      resultcode = chdir(__cil_tmp102);
#line 300
      seteuid(userid___0);
#line 301
      enable_signaling();
      }
    } else {

    }
    }
#line 303
    if (resultcode < 0) {
      {
#line 305
      __cil_tmp103 = (char const   * __restrict  )"error occurred while trying to chdir(%s)\n";
#line 305
      printf(__cil_tmp103, q);
      }
#line 306
      goto err1;
    } else {

    }
  } else {
#line 310
    p = resolved;
  }
  }
  {
#line 313
  __cil_tmp104 = *p;
#line 313
  __cil_tmp105 = (int )__cil_tmp104;
#line 313
  if (__cil_tmp105 != 0) {
    {
#line 314
    tmp___6 = __errno_location();
#line 314
    *tmp___6 = 0;
#line 315
    __cil_tmp106 = (char const   * __restrict  )"trying to lstat %s\n";
#line 315
    printf(__cil_tmp106, p);
#line 316
    __cil_tmp107 = (char const   * __restrict  )p;
#line 316
    __cil_tmp108 = (struct stat * __restrict  )(& sb);
#line 316
    resultcode = lstat(__cil_tmp107, __cil_tmp108);
#line 317
    __cil_tmp109 = (char const   * __restrict  )"Resultcode = %d\n";
#line 317
    printf(__cil_tmp109, resultcode);
#line 318
    tmp___7 = __errno_location();
#line 318
    __cil_tmp110 = (char const   * __restrict  )"errno=%d\n";
#line 318
    __cil_tmp111 = *tmp___7;
#line 318
    printf(__cil_tmp110, __cil_tmp111);
#line 320
    tmp___10 = __errno_location();
    }
    {
#line 320
    __cil_tmp112 = *tmp___10;
#line 320
    if (13 == __cil_tmp112) {
      {
#line 321
      tmp___8 = geteuid();
#line 321
      userid___1 = tmp___8;
#line 322
      delay_signaling();
#line 323
      __cil_tmp113 = (__uid_t )0;
#line 323
      seteuid(__cil_tmp113);
#line 324
      tmp___9 = __errno_location();
#line 324
      *tmp___9 = 0;
#line 325
      __cil_tmp114 = (char const   * __restrict  )p;
#line 325
      __cil_tmp115 = (struct stat * __restrict  )(& sb);
#line 325
      resultcode = lstat(__cil_tmp114, __cil_tmp115);
#line 326
      seteuid(userid___1);
#line 327
      enable_signaling();
      }
    } else {

    }
    }
#line 329
    if (resultcode == 0) {
      {
#line 332
      symlinks = 0;
#line 335
      __cil_tmp116 = (char const   * __restrict  )"sb.st_mode=%d\n";
#line 335
      __cil_tmp117 = (unsigned long )(& sb) + 24;
#line 335
      __cil_tmp118 = *((__mode_t *)__cil_tmp117);
#line 335
      printf(__cil_tmp116, __cil_tmp118);
      }
      {
#line 337
      __cil_tmp119 = (unsigned long )(& sb) + 24;
#line 337
      __cil_tmp120 = *((__mode_t *)__cil_tmp119);
#line 337
      __cil_tmp121 = __cil_tmp120 & 61440U;
#line 337
      if (__cil_tmp121 == 32768U) {
        {
#line 338
        __cil_tmp122 = (char const   * __restrict  )"isreg\n";
#line 338
        printf(__cil_tmp122);
        }
      } else {

      }
      }
      {
#line 339
      __cil_tmp123 = (unsigned long )(& sb) + 24;
#line 339
      __cil_tmp124 = *((__mode_t *)__cil_tmp123);
#line 339
      __cil_tmp125 = __cil_tmp124 & 61440U;
#line 339
      if (__cil_tmp125 == 16384U) {
        {
#line 340
        __cil_tmp126 = (char const   * __restrict  )"isdir\n";
#line 340
        printf(__cil_tmp126);
        }
      } else {

      }
      }
      {
#line 341
      __cil_tmp127 = (unsigned long )(& sb) + 24;
#line 341
      __cil_tmp128 = *((__mode_t *)__cil_tmp127);
#line 341
      __cil_tmp129 = __cil_tmp128 & 61440U;
#line 341
      if (__cil_tmp129 == 8192U) {
        {
#line 342
        __cil_tmp130 = (char const   * __restrict  )"ischr\n";
#line 342
        printf(__cil_tmp130);
        }
      } else {

      }
      }
      {
#line 343
      __cil_tmp131 = (unsigned long )(& sb) + 24;
#line 343
      __cil_tmp132 = *((__mode_t *)__cil_tmp131);
#line 343
      __cil_tmp133 = __cil_tmp132 & 61440U;
#line 343
      if (__cil_tmp133 == 24576U) {
        {
#line 344
        __cil_tmp134 = (char const   * __restrict  )"isblk\n";
#line 344
        printf(__cil_tmp134);
        }
      } else {

      }
      }
      {
#line 345
      __cil_tmp135 = (unsigned long )(& sb) + 24;
#line 345
      __cil_tmp136 = *((__mode_t *)__cil_tmp135);
#line 345
      __cil_tmp137 = __cil_tmp136 & 61440U;
#line 345
      if (__cil_tmp137 == 4096U) {
        {
#line 346
        __cil_tmp138 = (char const   * __restrict  )"isfifo\n";
#line 346
        printf(__cil_tmp138);
        }
      } else {

      }
      }
      {
#line 347
      __cil_tmp139 = (unsigned long )(& sb) + 24;
#line 347
      __cil_tmp140 = *((__mode_t *)__cil_tmp139);
#line 347
      __cil_tmp141 = __cil_tmp140 & 61440U;
#line 347
      if (__cil_tmp141 == 40960U) {
        {
#line 348
        __cil_tmp142 = (char const   * __restrict  )"islnk\n";
#line 348
        printf(__cil_tmp142);
        }
      } else {

      }
      }
      {
#line 349
      __cil_tmp143 = (unsigned long )(& sb) + 24;
#line 349
      __cil_tmp144 = *((__mode_t *)__cil_tmp143);
#line 349
      __cil_tmp145 = __cil_tmp144 & 61440U;
#line 349
      if (__cil_tmp145 == 49152U) {
        {
#line 350
        __cil_tmp146 = (char const   * __restrict  )"issock\n";
#line 350
        printf(__cil_tmp146);
        }
      } else {

      }
      }
      {
#line 352
      __cil_tmp147 = (unsigned long )(& sb) + 24;
#line 352
      __cil_tmp148 = *((__mode_t *)__cil_tmp147);
#line 352
      __cil_tmp149 = __cil_tmp148 & 61440U;
#line 352
      if (__cil_tmp149 == 40960U) {
#line 353
        symlinks = symlinks + 1;
#line 353
        if (symlinks > 5) {
          {
#line 354
          tmp___11 = __errno_location();
#line 354
          *tmp___11 = 40;
          }
#line 355
          goto err1;
        } else {

        }
        {
#line 357
        tmp___12 = __errno_location();
#line 357
        *tmp___12 = 0;
#line 359
        __cil_tmp150 = (char const   *)p;
#line 359
        tmp___13 = strlen(__cil_tmp150);
#line 359
        len = tmp___13;
#line 360
        __cil_tmp151 = len + 1UL;
#line 360
        tmp___15 = calloc(__cil_tmp151, 1UL);
#line 360
        tmp___14 = (char *)tmp___15;
        }
        {
#line 361
        __cil_tmp152 = (char *)0;
#line 361
        __cil_tmp153 = (unsigned long )__cil_tmp152;
#line 361
        __cil_tmp154 = (unsigned long )tmp___14;
#line 361
        if (__cil_tmp154 == __cil_tmp153) {
          {
#line 362
          tmp___16 = __errno_location();
#line 362
          serrno = *tmp___16;
          }
#line 363
          goto err1;
        } else {

        }
        }
        {
#line 365
        __cil_tmp155 = (char * __restrict  )tmp___14;
#line 365
        __cil_tmp156 = (char const   * __restrict  )p;
#line 365
        strcpy(__cil_tmp155, __cil_tmp156);
#line 366
        p = tmp___14;
#line 368
        __cil_tmp157 = (char const   * __restrict  )p;
#line 368
        __cil_tmp158 = (char * __restrict  )resolved;
#line 368
        __cil_tmp159 = (size_t )46;
#line 368
        tmp___17 = readlink(__cil_tmp157, __cil_tmp158, __cil_tmp159);
#line 368
        n = (int )tmp___17;
#line 369
        tmp___21 = __errno_location();
        }
        {
#line 369
        __cil_tmp160 = *tmp___21;
#line 369
        if (13 == __cil_tmp160) {
          {
#line 370
          tmp___18 = geteuid();
#line 370
          userid___2 = tmp___18;
#line 371
          delay_signaling();
#line 372
          __cil_tmp161 = (__uid_t )0;
#line 372
          seteuid(__cil_tmp161);
#line 373
          tmp___19 = __errno_location();
#line 373
          *tmp___19 = 0;
#line 374
          __cil_tmp162 = (char const   * __restrict  )p;
#line 374
          __cil_tmp163 = (char * __restrict  )resolved;
#line 374
          __cil_tmp164 = (size_t )46;
#line 374
          tmp___20 = readlink(__cil_tmp162, __cil_tmp163, __cil_tmp164);
#line 374
          n = (int )tmp___20;
#line 375
          seteuid(userid___2);
#line 376
          enable_signaling();
          }
        } else {

        }
        }
#line 378
        if (n < 0) {
          {
#line 379
          __cil_tmp165 = (void *)p;
#line 379
          free(__cil_tmp165);
          }
#line 380
          goto err1;
        } else {

        }
        {
#line 382
        __cil_tmp166 = (void *)p;
#line 382
        free(__cil_tmp166);
#line 383
        __cil_tmp167 = resolved + n;
#line 383
        *__cil_tmp167 = (char )'\000';
        }
#line 384
        goto loop;
      } else {

      }
      }
      {
#line 387
      __cil_tmp168 = (unsigned long )(& sb) + 24;
#line 387
      __cil_tmp169 = *((__mode_t *)__cil_tmp168);
#line 387
      __cil_tmp170 = __cil_tmp169 & 61440U;
#line 387
      if (__cil_tmp170 == 16384U) {
        {
#line 388
        __cil_tmp171 = (char const   * __restrict  )"S_ISDIR..\n";
#line 388
        printf(__cil_tmp171);
#line 389
        tmp___22 = __errno_location();
#line 389
        *tmp___22 = 0;
#line 390
        __cil_tmp172 = (char const   *)p;
#line 390
        resultcode = chdir(__cil_tmp172);
#line 391
        __cil_tmp173 = (char const   * __restrict  )"chdir(%s) = resultcode = %d\n";
#line 391
        printf(__cil_tmp173, p, resultcode);
#line 392
        tmp___25 = __errno_location();
        }
        {
#line 392
        __cil_tmp174 = *tmp___25;
#line 392
        if (13 == __cil_tmp174) {
          {
#line 393
          tmp___23 = geteuid();
#line 393
          userid___3 = tmp___23;
#line 394
          delay_signaling();
#line 395
          __cil_tmp175 = (__uid_t )0;
#line 395
          seteuid(__cil_tmp175);
#line 396
          tmp___24 = __errno_location();
#line 396
          *tmp___24 = 0;
#line 397
          __cil_tmp176 = (char const   *)p;
#line 397
          resultcode = chdir(__cil_tmp176);
#line 398
          seteuid(userid___3);
#line 399
          enable_signaling();
          }
        } else {

        }
        }
#line 401
        if (resultcode < 0) {
#line 402
          goto err1;
        } else {

        }
#line 404
        p = (char *)"";
      } else {

      }
      }
    } else {

    }
  } else {

  }
  }
  {
#line 414
  __cil_tmp177 = 0 * 1UL;
#line 414
  __cil_tmp178 = (unsigned long )(wbuf) + __cil_tmp177;
#line 414
  __cil_tmp179 = (char *)__cil_tmp178;
#line 414
  __cil_tmp180 = (char * __restrict  )__cil_tmp179;
#line 414
  __cil_tmp181 = (char const   * __restrict  )p;
#line 414
  strcpy(__cil_tmp180, __cil_tmp181);
#line 415
  __cil_tmp182 = (char const   * __restrict  )"wbuf now contains %s\n";
#line 415
  __cil_tmp183 = 0 * 1UL;
#line 415
  __cil_tmp184 = (unsigned long )(wbuf) + __cil_tmp183;
#line 415
  __cil_tmp185 = (char *)__cil_tmp184;
#line 415
  printf(__cil_tmp182, __cil_tmp185);
#line 416
  tmp___26 = __errno_location();
#line 416
  *tmp___26 = 0;
#line 418
  __cil_tmp186 = (size_t )46;
#line 418
  tmp___28 = getcwd(resolved, __cil_tmp186);
  }
  {
#line 418
  __cil_tmp187 = (void *)0;
#line 418
  __cil_tmp188 = (unsigned long )__cil_tmp187;
#line 418
  __cil_tmp189 = (unsigned long )tmp___28;
#line 418
  if (__cil_tmp189 == __cil_tmp188) {
#line 418
    resultcode = 0;
  } else {
#line 418
    resultcode = 1;
  }
  }
  {
#line 419
  __cil_tmp190 = (char const   * __restrict  )"getcwd: resultcode = %d\n";
#line 419
  printf(__cil_tmp190, resultcode);
#line 427
  tmp___33 = __errno_location();
  }
  {
#line 427
  __cil_tmp191 = *tmp___33;
#line 427
  if (13 == __cil_tmp191) {
    {
#line 428
    tmp___29 = geteuid();
#line 428
    userid___4 = tmp___29;
#line 429
    delay_signaling();
#line 430
    __cil_tmp192 = (__uid_t )0;
#line 430
    seteuid(__cil_tmp192);
#line 431
    tmp___30 = __errno_location();
#line 431
    *tmp___30 = 0;
#line 433
    __cil_tmp193 = (size_t )46;
#line 433
    tmp___32 = getcwd(resolved, __cil_tmp193);
    }
    {
#line 433
    __cil_tmp194 = (void *)0;
#line 433
    __cil_tmp195 = (unsigned long )__cil_tmp194;
#line 433
    __cil_tmp196 = (unsigned long )tmp___32;
#line 433
    if (__cil_tmp196 == __cil_tmp195) {
#line 433
      resultcode = 0;
    } else {
#line 433
      resultcode = 1;
    }
    }
    {
#line 441
    seteuid(userid___4);
#line 442
    enable_signaling();
    }
  } else {

  }
  }
#line 444
  if (resultcode == 0) {
    {
#line 446
    __cil_tmp197 = (char const   * __restrict  )"going to err1.. resultcode = %d\n";
#line 446
    printf(__cil_tmp197, resultcode);
    }
#line 447
    goto err1;
  } else {

  }
  {
#line 453
  __cil_tmp198 = resolved + 0;
#line 453
  __cil_tmp199 = *__cil_tmp198;
#line 453
  __cil_tmp200 = (int )__cil_tmp199;
#line 453
  if (__cil_tmp200 == 47) {
    {
#line 453
    __cil_tmp201 = resolved + 1;
#line 453
    __cil_tmp202 = *__cil_tmp201;
#line 453
    __cil_tmp203 = (int )__cil_tmp202;
#line 453
    if (__cil_tmp203 == 0) {
#line 454
      rootd = 1;
    } else {
#line 456
      rootd = 0;
    }
    }
  } else {
#line 456
    rootd = 0;
  }
  }
  {
#line 458
  __cil_tmp204 = (char const   *)resolved;
#line 458
  tmp___34 = strlen(__cil_tmp204);
#line 458
  __cil_tmp205 = (char const   * __restrict  )"resolved(%d) = %s\n";
#line 458
  printf(__cil_tmp205, tmp___34, resolved);
#line 459
  __cil_tmp206 = 0 * 1UL;
#line 459
  __cil_tmp207 = (unsigned long )(wbuf) + __cil_tmp206;
#line 459
  __cil_tmp208 = (char *)__cil_tmp207;
#line 459
  __cil_tmp209 = (char const   *)__cil_tmp208;
#line 459
  tmp___35 = strlen(__cil_tmp209);
#line 459
  __cil_tmp210 = (char const   * __restrict  )"wbuf(%d) = %s \n";
#line 459
  __cil_tmp211 = 0 * 1UL;
#line 459
  __cil_tmp212 = (unsigned long )(wbuf) + __cil_tmp211;
#line 459
  __cil_tmp213 = (char *)__cil_tmp212;
#line 459
  printf(__cil_tmp210, tmp___35, __cil_tmp213);
#line 460
  __cil_tmp214 = (char const   * __restrict  )"rootd=%d\n";
#line 460
  printf(__cil_tmp214, rootd);
#line 461
  __cil_tmp215 = (char const   *)resolved;
#line 461
  tmp___36 = strlen(__cil_tmp215);
#line 461
  __cil_tmp216 = 0 * 1UL;
#line 461
  __cil_tmp217 = (unsigned long )(wbuf) + __cil_tmp216;
#line 461
  __cil_tmp218 = (char *)__cil_tmp217;
#line 461
  __cil_tmp219 = (char const   *)__cil_tmp218;
#line 461
  tmp___37 = strlen(__cil_tmp219);
#line 461
  __cil_tmp220 = (char const   * __restrict  )"strlen(resolved) + strlen(wbuf) + rootd + 1 = %d\n";
#line 461
  __cil_tmp221 = (size_t )rootd;
#line 461
  __cil_tmp222 = tmp___36 + tmp___37;
#line 461
  __cil_tmp223 = __cil_tmp222 + __cil_tmp221;
#line 461
  __cil_tmp224 = __cil_tmp223 + 1UL;
#line 461
  printf(__cil_tmp220, __cil_tmp224);
  }
  {
#line 463
  __cil_tmp225 = 0 * 1UL;
#line 463
  __cil_tmp226 = (unsigned long )(wbuf) + __cil_tmp225;
#line 463
  if (*((char *)__cil_tmp226)) {
    {
#line 464
    __cil_tmp227 = (char const   *)resolved;
#line 464
    tmp___39 = strlen(__cil_tmp227);
#line 464
    __cil_tmp228 = 0 * 1UL;
#line 464
    __cil_tmp229 = (unsigned long )(wbuf) + __cil_tmp228;
#line 464
    __cil_tmp230 = (char *)__cil_tmp229;
#line 464
    __cil_tmp231 = (char const   *)__cil_tmp230;
#line 464
    tmp___40 = strlen(__cil_tmp231);
    }
    {
#line 464
    __cil_tmp232 = (size_t )rootd;
#line 464
    __cil_tmp233 = tmp___39 + tmp___40;
#line 464
    __cil_tmp234 = __cil_tmp233 + __cil_tmp232;
#line 464
    __cil_tmp235 = __cil_tmp234 + 1UL;
#line 464
    if (__cil_tmp235 > 46UL) {
      {
#line 465
      tmp___38 = __errno_location();
#line 465
      *tmp___38 = 36;
#line 466
      __cil_tmp236 = (char const   * __restrict  )"resolved path too long!\n";
#line 466
      printf(__cil_tmp236);
      }
#line 467
      goto err1;
    } else {

    }
    }
#line 469
    if (rootd == 0) {
      {
#line 470
      __cil_tmp237 = (char * __restrict  )resolved;
#line 470
      __cil_tmp238 = (char const   * __restrict  )"/";
#line 470
      strcat(__cil_tmp237, __cil_tmp238);
      }
    } else {

    }
    {
#line 472
    __cil_tmp239 = (char const   *)resolved;
#line 472
    tmp___41 = strlen(__cil_tmp239);
#line 472
    __cil_tmp240 = (char const   * __restrict  )"resolved=%s  len=%d \n";
#line 472
    printf(__cil_tmp240, resolved, tmp___41);
#line 473
    __cil_tmp241 = 0 * 1UL;
#line 473
    __cil_tmp242 = (unsigned long )(wbuf) + __cil_tmp241;
#line 473
    __cil_tmp243 = (char *)__cil_tmp242;
#line 473
    __cil_tmp244 = (char const   *)__cil_tmp243;
#line 473
    tmp___42 = strlen(__cil_tmp244);
#line 473
    __cil_tmp245 = (char const   * __restrict  )"wbuf=%s  len=%d \n";
#line 473
    __cil_tmp246 = 0 * 1UL;
#line 473
    __cil_tmp247 = (unsigned long )(wbuf) + __cil_tmp246;
#line 473
    __cil_tmp248 = (char *)__cil_tmp247;
#line 473
    printf(__cil_tmp245, __cil_tmp248, tmp___42);
    }
    {
#line 476
    __cil_tmp249 = (char * __restrict  )resolved;
#line 476
    __cil_tmp250 = 0 * 1UL;
#line 476
    __cil_tmp251 = (unsigned long )(wbuf) + __cil_tmp250;
#line 476
    __cil_tmp252 = (char *)__cil_tmp251;
#line 476
    __cil_tmp253 = (char const   * __restrict  )__cil_tmp252;
#line 476
    strcat(__cil_tmp249, __cil_tmp253);
#line 477
    __cil_tmp254 = (char const   *)resolved;
#line 477
    tmp___43 = strlen(__cil_tmp254);
#line 477
    __cil_tmp255 = (char const   * __restrict  )"after strcat, resolved = %s, strlen(resolved) = %d\n";
#line 477
    printf(__cil_tmp255, resolved, tmp___43);
#line 478
    __cil_tmp256 = (char const   *)resolved;
#line 478
    tmp___44 = strlen(__cil_tmp256);
    }
    {
#line 478
    __cil_tmp257 = tmp___44 + 1UL;
#line 478
    if (__cil_tmp257 > 46UL) {
      {
#line 479
      __cil_tmp258 = (char const   * __restrict  )"strlen(resolve) > MAXPATHLEN -- buffer overflow\n";
#line 479
      printf(__cil_tmp258);
      }
    } else {

    }
    }
  } else {

  }
  }
  {
#line 484
  tmp___45 = __errno_location();
#line 484
  *tmp___45 = 0;
#line 488
  resultcode = fchdir(fd);
#line 490
  tmp___48 = __errno_location();
  }
  {
#line 490
  __cil_tmp259 = *tmp___48;
#line 490
  if (13 == __cil_tmp259) {
    {
#line 491
    tmp___46 = geteuid();
#line 491
    userid___5 = tmp___46;
#line 492
    delay_signaling();
#line 493
    __cil_tmp260 = (__uid_t )0;
#line 493
    seteuid(__cil_tmp260);
#line 494
    tmp___47 = __errno_location();
#line 494
    *tmp___47 = 0;
#line 498
    resultcode = fchdir(fd);
#line 500
    seteuid(userid___5);
#line 501
    enable_signaling();
    }
  } else {

  }
  }
#line 503
  if (resultcode < 0) {
    {
#line 504
    tmp___49 = __errno_location();
#line 504
    serrno = *tmp___49;
    }
#line 505
    goto err2;
  } else {

  }
  {
#line 510
  close(fd);
  }
#line 512
  return (resolved);
  err1: 
  {
#line 514
  tmp___50 = __errno_location();
#line 514
  serrno = *tmp___50;
#line 518
  fchdir(fd);
#line 520
  tmp___52 = __errno_location();
  }
  {
#line 520
  __cil_tmp261 = *tmp___52;
#line 520
  if (13 == __cil_tmp261) {
    {
#line 521
    tmp___51 = geteuid();
#line 521
    userid___6 = tmp___51;
#line 522
    delay_signaling();
#line 523
    __cil_tmp262 = (__uid_t )0;
#line 523
    seteuid(__cil_tmp262);
#line 527
    fchdir(fd);
#line 529
    seteuid(userid___6);
#line 530
    enable_signaling();
    }
  } else {

  }
  }
  err2: 
  {
#line 535
  close(fd);
#line 536
  tmp___53 = __errno_location();
#line 536
  *tmp___53 = serrno;
  }
  {
#line 538
  __cil_tmp263 = (void *)0;
#line 538
  return ((char *)__cil_tmp263);
  }
}
}
