DEFINE_FUNC(J_lbool, interpolateSeq) WITH_9_ARGS(J_context, int, J_ast_array, J_ast_array, J_model_pointer, J_literals_pointer, int, int, J_ast_array)
CONTEXT_ARG(1)
INT_ARG(2)
AST_ARRAY_ARG(3)

AST_OUT_ARRAY_ARG(4)
MODEL_POINTER_ARG(5)
LITERALS_POINTER_ARG(6)
INT_ARG(7)
INT_ARG(8)
AST_ARRAY_ARG(9)

Z3_lbool retval = Z3_interpolate(z3_arg1, z3_arg2, z3_arg3, NULL, NULL, z3_arg4, z3_arg5, z3_arg6, z3_arg7, z3_arg8, z3_arg9);

CLEAN_AST_ARRAY_ARG(9)
CLEAN_INT_ARG(8)
CLEAN_INT_ARG(7)
SET_LITERALS_POINTER_ARG(6)
CLEAN_LITERALS_POINTER_ARG(6)
SET_MODEL_POINTER_ARG(5)
CLEAN_MODEL_POINTER_ARG(5)
SET_AST_OUT_ARRAY_ARG(4)
CLEAN_AST_OUT_ARRAY_ARG(4)

CLEAN_AST_ARRAY_ARG(3)
CLEAN_INT_ARG(2)
CLEAN_CONTEXT_ARG(1)
LBOOL_RETURN
