#!/usr/bin/env python

import sys
import os
import subprocess

# default is initial-mode ...
mode = '--init-upgrade-check'

# ... but if predecessor is igven and exists, change to upgrade-mode
if '--predecessor' in sys.argv and os.path.isfile(sys.argv[sys.argv.index('--predecessor') + 1]) :
    mode = '--do-upgrade-check'
    # remove pseudo-option
    sys.argv.pop(sys.argv.index('--predecessor'))

sys.argv.pop(0)

# run the actual tool
subprocess.Popen(['evolcheck'] + [mode] + sys.argv).wait()