/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

#line 214 "/usr/lib/gcc/i486-linux-gnu/4.3.3/include/stddef.h"
typedef unsigned int size_t;
#line 4 "test2.h"
struct device {
   int parent ;
};
#line 9 "test2.h"
struct i2o_controller {
   struct device device ;
};
#line 9 "test2.h"
typedef struct i2o_controller i2o_controller;
#line 471 "/usr/include/stdlib.h"
extern void *malloc(size_t __size ) ;
#line 488
extern void free(void *__ptr ) ;
#line 14 "test2.h"
i2o_controller *i2o_iop_alloc(void) ;
#line 15
void i2o_iop_free(i2o_controller *c ) ;
#line 16
void put_device(int i ) ;
#line 6 "test2_cpachecker.c"
i2o_controller *i2o_iop_alloc(void) 
{ i2o_controller *c ;
  void *tmp ;

  {
#line 8
  tmp = malloc(4U);
#line 8
  c = (i2o_controller *)tmp;
#line 9
  return (c);
}
}
#line 12 "test2_cpachecker.c"
void i2o_iop_free(i2o_controller *c ) 
{ void *__cil_tmp2 ;

  {
#line 13
  __cil_tmp2 = (void *)c;
#line 13
  free(__cil_tmp2);
#line 14
  return;
}
}
#line 16 "test2_cpachecker.c"
void put_device(int i ) 
{ 

  {
#line 16
  return;
}
}
#line 18 "test2_cpachecker.c"
int main(void) 
{ i2o_controller *c ;
  int __cil_tmp2 ;

  {
#line 20
  c = i2o_iop_alloc();
#line 21
  i2o_iop_free(c);
#line 22
  __cil_tmp2 = *((int *)c);
#line 22
  put_device(__cil_tmp2);
#line 23
  return (0);
}
}
